### PR TITLE
Replace `re2` with RegExp in timeline and add unit tests

### PR DESCRIPTION
**Pull request by ananzh**
### Description
Remove re2 usage and replace it with JavaScript built-in RegExp object. Also add more unit tests to make sure that using RegExp has same expressions as using re2 library.

### Issue Resolve
fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3901

### Check List

- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by joshuarrrr — APPROVED** [review]
Looks good to me, this is a nice bit of tech debt eliminated.

**Comment by joshuarrrr** [comment]
@ananzh Can/should we also backport to 1.x/1.3?

**Comment by ananzh** [comment]
> 

It was for node 18. But we could backport to 1.x.

**Review by abbyhu2000 — APPROVED** [review]

**Comment by kavilla** [comment]
One thing to note is the point of re2 dependency being:
```
node-re2 can protect your Node.js application from ReDoS. node-re2 makes vulnerable regular expression patterns safe by evaluating them in RE2 instead of the built-in Node.js regex engine.
```

Are we ensuring we are not potentially opening us to these problems?

Also a thing to note:
```
RE2 and the built-in regex engines disagree a bit. Before you switch to RE2, verify that your regular expressions continue to work as expected. They should do so in the vast majority of cases
```

Since Timeline is nearly impossible to catch every regex provided by the user is it worth mentioning ahead of time?

**Comment by AMoo-Miki** [comment]
Even if there is a redos, it is a self-redos as the library is only used for labels of a single type of visualization.

**Comment by ananzh** [comment]
I am seeing breaking changes and errors when I try to backport it to 1.x
```
ubuntu@ip-172-31-55-237:~/OpenSearch-Dashboards$ yarn osd bootstrap
yarn run v1.22.19
$ node scripts/osd bootstrap
 info [opensearch-dashboards] running yarn

$ node ./preinstall_check
[1/4] Resolving packages...
warning hapi > statehood > iron@5.0.6: This module has moved and is now available at @hapi/iron. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~4.8.4"
warning Resolution field "shelljs@0.8.5" is incompatible with requested version "shelljs@^0.6.0"
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > @elastic/eui@29.3.2" has incorrect peer dependency "typescript@^3.7.2".
warning " > @testing-library/react-hooks@3.4.1" has unmet peer dependency "react-test-renderer@>=16.9.0".
[4/4] Building fresh packages...
[1/17] ⡀ @elastic/eui
[6/17] ⡀ spawn-sync
[3/17] ⡀ core-js
[4/17] ⡀ msgpackr-extract
warning Error running install script for optional dependency: "/home/ubuntu/OpenSearch-Dashboards/node_modules/msgpackr-extract: Command failed.
Exit code: 7
Command: node-gyp-build
Arguments: 
Directory: /home/ubuntu/OpenSearch-Dashboards/node_modules/msgpackr-extract
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@10.24.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at \"/usr/bin/python3\"
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Object.fromEntries is not a function
gyp ERR! stack     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/@npmcli/fs/lib/fs.js:6:23)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:778:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:653:32)
gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:692:17)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:25:18)
gyp ERR! stack     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/@npmcli/fs/lib/index.js:2:6)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:778:30)
gyp ERR! System Linux 5.15.0-1023-aws
gyp ERR! command \"/home/ubuntu/.nvm/versions/node/v10.24.1/bin/node\" \"/home/ubuntu/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /home/ubuntu/OpenSearch-Dashboards/node_modules/msgpackr-extract
gyp ERR! node -v v10.24.1
[7/17] ⠈ puppeteer
[10/17] ⠈ yo
[11/17] ⠈ backport
[9/17] ⠈ lmdb-store
error /home/ubuntu/OpenSearch-Dashboards/node_modules/lmdb-store: Command failed.
Exit code: 7
Command: node-gyp-build
Arguments: 
Directory: /home/ubuntu/OpenSearch-Dashboards/node_modules/lmdb-store
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.1.0
gyp info using node@10.24.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp ERR! UNCAUGHT EXCEPTION 
gyp ERR! stack TypeError: Object.fromEntries is not a function
gyp ERR! stack     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/@npmcli/fs/lib/fs.js:6:23)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:778:30)
gyp ERR! stack     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
gyp ERR! stack     at Module.load (internal/modules/cjs/loader.js:653:32)
gyp ERR! stack     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
gyp ERR! stack     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
gyp ERR! stack     at Module.require (internal/modules/cjs/loader.js:692:17)
gyp ERR! stack     at require (internal/modules/cjs/helpers.js:25:18)
gyp ERR! stack     at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/@npmcli/fs/lib/index.js:2:6)
gyp ERR! stack     at Module._compile (internal/modules/cjs/loader.js:778:30)
gyp ERR! System Linux 5.15.0-1023-aws
gyp ERR! command "/home/ubuntu/.nvm/versions/node/v10.24.1/bin/node" "/home/ubuntu/.nvm/versions/node/v10.24.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ubuntu/OpenSearch-Dashboards/node_modules/lmdb-store
gyp ERR! node -v v10.24.1




ERROR [bootstrap] failed:
ERROR Error: Command failed with exit code 7: /home/ubuntu/.nvm/versions/node/v10.24.1/lib/node_modules/yarn/bin/yarn.js install --non-interactive
          at makeError (/home/ubuntu/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:25139:11)
          at handlePromise (/home/ubuntu/OpenSearch-Dashboards/packages/osd-pm/dist/index.js:24074:26)
          at process._tickCallback (internal/process/next_tick.js:68:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

By googling, the error messages here is related to the building of native dependencies using `node-gyp`. The `Object.fromEntries` function is a JavaScript method which was added in ES2019. The error message indicates that the `Object.fromEntries` is being used in a script from the `@npmcli/fs` module, which is a dependency for `node-gyp`. This script is used for file system operations. This feature was added in ECMAScript 2019 (ES10) and is not supported in Node.js versions earlier than 12.0.0. Since we are using Node.js v10.24.1 for 1.x, we don't have support for this function.

**Comment by manasvinibs** [comment]
Backported to 2.x here https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4203

**Comment by joshuarrrr** [comment]
@ananzh @manasvinibs We still need to backport this to `1.3`, right?

**Comment by manasvinibs** [comment]
> @ananzh @manasvinibs We still need to backport this to `1.3`, right?

I think you're right! adding back the failed backport label. @ananzh Can you confirm?

**Comment by joshuarrrr** [comment]
@AMoo-Miki Given the challenges @ananzh ran into in trying to backport to `1.x`/`1.3`, any real need to do so, or can we skip?

**Comment by joshuarrrr** [comment]
Not security related, so no need to backport to 1.x or 1.3.

**Pull request merged**
