### PR TITLE
Bump OUI to 1.1.0

### PR DESCRIPTION
**Pull request by joshuarrrr**
### Description

Initial commit - will need to bootstrap once OUI 1.1.0 is published to npm.

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by AMoo-Miki** [comment]
Looks like some some tests are failing. snapshot issues?

**Comment by BSFishy** [comment]
> Looks like some some tests are failing. snapshot issues?

Yes, in my testing, one snapshot needed to be updated. Not sure about cypress tests, and I have no clue how to decipher that output

**Comment by joshuali925** [comment]
observability 2.7 depends on this, will the PR be merged and backported by today? If not please let me know, thanks

**Comment by ashwin-pc** [comment]
@joshuali925 we are trying to fix the broken changes. If we can get them fixed soon, we will have this merged and backported in the next hour or so, if not we wont.

**Review by ashwin-pc — APPROVED** [review]

**Comment by joshuarrrr** [comment]
obsolete via #3884

**Pull request closed without merging**
