### PR TITLE
[Multiple Datasource] Remove experimental banner & badge

### LINKED ISSUE #3579: [Multiple Datasource]Remove experiment feature banner.
- [ ] Remove experiment feature banner
image

- [x] ~~Currently to enable the feature, user needs to set `data_source.enabled: false` to `data_source.enabled: true` and save the `opensearch-dashboards.yml` -> restart opensearch dashboards. [ reference](https://opensearch.org/docs/2.6/dashboards/discover/multi-data-sources/#modifying-the-multiple-data-sources-settings)] Wonder if in GA, we should turn it on by default @ahopp @zengyan-amazon @seraphjiang~~

### PR DESCRIPTION
**Pull request by zhongnansu**
### Description
[Multiple Datasource] Remove experimental banner
image
image

 
### Issues Resolved
#3579 
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by seanneumann — APPROVED** [review]
LGTM

**Comment by kristenTian** [comment]
LGTM

**Review by kristenTian — APPROVED** [review]

**Comment by zhongnansu** [comment]
update with another commit to remove the "Experimental" badge

**Review by seanneumann — APPROVED** [review]
👍

**Pull request merged**
