### PR TITLE
Update dev docs

### PR DESCRIPTION
**Pull request by gaobinlong**
### Description

Update dev docs for the new features such as data source, workspace etc.

### Issues Resolved

No issue, this PR only impacts the dev docs, no code change.

### Check List

- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by gaobinlong** [comment]
@ashwin-pc , could you help to review this PR, thanks you!

**Review by ashwin-pc — APPROVED** [review]
LGTM, thanks!

**Review by SuZhou-Joe — APPROVED** [review]

**Comment by BionIT** [comment]
@gaobinlong should this PR be backported to 2.x?

**Comment by gaobinlong** [comment]
> @gaobinlong should this PR be backported to 2.x?
I think no, because the changed file in this PR doesn't exist in 2.x branch.

**Pull request merged**
