### PR TITLE
[RFC] [WIP] [FEATURE] Integrate dashboards observability

### PR DESCRIPTION
**Pull request by pjfitzgibbons**
### Description
This is a WIP - Interim code-change - RFC - RequestForComments. Any input on code-style, approach, or general implementation is greatly appreciated.

DCO sign-off will be completed when this change is completed and ready for merge.

Extend src/plugin/dashboard Setup to expose a registry fn for other plugins to hook to dashboards-list fetch process.
 
### Issues WIP
[[FEATURE] Integrate Observability Panels/Apps lists into OpenSearch-Dashboards main List View](https://github.com/opensearch-project/observability/issues/830)

## Related PR 
Observability Plugin : [[WIP] [FEATURE] Integrate Dashboards/Observability](https://github.com/opensearch-project/observability/pull/831)

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
    - [ ] `yarn test:jest`
    - [ ] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ashwin-pc** [comment]
@pjfitzgibbons The diff seems to contain changes that are already in mainline. Do you know what happened here? There is also a conflict in the PR that needs to be resolved.

**Comment by kavilla** [comment]
> @pjfitzgibbons The diff seems to contain changes that are already in mainline. Do you know what happened here? There is also a conflict in the PR that needs to be resolved.

I believe it might have been checked out on a 2.x branch but it's targeting. 

I think it's an WIP can we make this a draft PR and clean this up to see the actual changes?

Thanks!

**Review by kavilla — CHANGES_REQUESTED** [review]
Blocking

**Comment by pjfitzgibbons** [comment]
@kavilla Made this Draft, fixed DCO, and fixed the base-branch, so my one commit is now clear.  Any advice/recommended changes on my approach or code-style on this?

**Pull request closed without merging**
