### PR TITLE
Bump axios related dependencies

### PR DESCRIPTION
**Pull request by tmarkley**
### Description
Dependabot bumped axios from 0.19.2 to 0.21.1 in #434, but the older version of axios remained in the lockfile. Using `yarn why axios`, we can see that the older version is a dependency of `@percy/agent`, `backport`, and `chromedriver`. By bumping each of these to the latest compatible versions we can properly eliminate the old version of axios from the lockfile.

Signed-off-by: Tommy Markley <markleyt@amazon.com>

**Before:**
```
$ yarn why axios
yarn why v1.22.10
[1/4] Why do we have the module "axios"...?
[2/4] Initialising dependency graph...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~3.7.2"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "axios@0.19.2"
info Has been hoisted to "axios"
info Reasons this module exists
   - "workspace-aggregator-6cba5d43-7bd2-4aa7-b2fe-6e970afdd553" depends on it
   - Hoisted from "_project_#@percy#agent#axios"
   - Hoisted from "_project_#chromedriver#axios"
   - Hoisted from "_project_#backport#axios"
info Disk size without dependencies: "652KB"
info Disk size with unique dependencies: "696KB"
info Disk size with transitive dependencies: "696KB"
info Number of shared dependencies: 1
=> Found "@osd/dev-utils#axios@0.21.1"
info This module exists because "_project_#@osd#dev-utils" depends on it.
info Disk size without dependencies: "504KB"
info Disk size with unique dependencies: "548KB"
info Disk size with transitive dependencies: "548KB"
info Number of shared dependencies: 1
=> Found "@osd/release-notes#axios@0.21.1"
info This module exists because "_project_#@osd#release-notes" depends on it.
info Disk size without dependencies: "504KB"
info Disk size with unique dependencies: "548KB"
info Disk size with transitive dependencies: "548KB"
info Number of shared dependencies: 1
Done in 1.54s.
```

**After**:
```
$ yarn why axios
yarn why v1.22.10
[1/4] Why do we have the module "axios"...?
[2/4] Initialising dependency graph...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~3.7.2"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "axios@0.21.1"
info Reasons this module exists
   - "_project_#@percy#agent" depends on it
   - Hoisted from "_project_#@percy#agent#axios"
   - Hoisted from "_project_#@osd#release-notes#axios"
   - Hoisted from "_project_#backport#axios"
   - Hoisted from "_project_#chromedriver#axios"
   - Hoisted from "_project_#@osd#dev-utils#axios"
info Disk size without dependencies: "504KB"
info Disk size with unique dependencies: "548KB"
info Disk size with transitive dependencies: "548KB"
info Number of shared dependencies: 1
Done in 1.48s.
```

### Testing
Changes for #456, #457, #458, #460, #461, and #476 were merged into the same branch and tested together. All tests passed.

#### Unit
```
$ yarn test:jest
...
Test Suites: 23 skipped, 1411 passed, 1411 of 1434 total
Tests:       256 skipped, 9 todo, 10364 passed, 10629 total
Snapshots:   2363 passed, 2363 total
Time:        156.76 s
Ran all test suites.
Done in 159.62s.
```

#### Integration
```
$ yarn test:jest_integration
...
Test Suites: 2 skipped, 48 passed, 48 of 50 total
Tests:       19 skipped, 418 passed, 437 total
Snapshots:   73 passed, 73 total
Time:        222.992 s
Ran all test suites.
Done in 225.23s.
```

#### Functional
Screen Shot 2021-06-10 at 10 31 39 PM

 
### Issues Resolved
N/A
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by boktorbb-amzn — DISMISSED** [review]
LGTM

**Review by ananzh — APPROVED** [review]

**Comment by kavilla** [comment]
Now has conflicts which Im sure you are fixing, but I smoke tested this but not positive if I touched stuff related to these changes. But it seems good to me.

**Comment by tmarkley** [comment]
> Now has conflicts which Im sure you are fixing, but I smoke tested this but not positive if I touched stuff related to these changes. But it seems good to me.

@kavilla Yeah I just realized that when I tested all of these changes together there was a minor conflict with the lockfile. Going to resolve and then merge.

**Review by boktorbb-amzn — APPROVED** [review]
LGTM

**Review by ananzh — APPROVED** [review]

**Comment by kavilla** [comment]
`1.x` and `1.0` are updated, should feel free to backport this commit if it needs to be.

**Pull request merged**
