### PR TITLE
Cleanup and rebuild @osd/pm

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description

* Fixed the build failures
* Removed some unused packages
* Rebuilt dist of @osd/pm
 
### Check List
- [X] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [X] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by seraphjiang** [comment]
Has the build issue caught by any automation test?

**Comment by seraphjiang** [comment]
For process to update dust/index.Js do we have it covered in any release doc or developer guideline doc

**Comment by AMoo-Miki** [comment]
Link Checker complaining about `https://codeload.github.com/gist/{project}/tar.gz/{committish}` can be ignored.

**Comment by AMoo-Miki** [comment]
> Has the build issue caught by any automation test?

No. `dist` contains a prebuilt one and no changes have gone into `@osd/pm` to warrant a rebuild.

**Comment by AMoo-Miki** [comment]
> For process to update dust/index.Js do we have it covered in any release doc or developer guideline doc

The package has complete documentation of this.

**Comment by joshuarrrr** [comment]
> Link Checker complaining about `https://codeload.github.com/gist/{project}/tar.gz/{committish}` can be ignored.

@AMoo-Miki You need to add that to `.lycheexclude`. Otherwise it will fail for all other subsequent PRs. Or are you saying it's a transient issue?

**Comment by AMoo-Miki** [comment]
> > Link Checker complaining about `https://codeload.github.com/gist/{project}/tar.gz/{committish}` can be ignored.
> 
> @AMoo-Miki You need to add that to `.lycheexclude`. Otherwise it will fail for all other subsequent PRs. Or are you saying it's a transient issue?

I think it only complains in changed files as it is not complaining about it right now.

**Review by ashwin-pc — APPROVED** [review]

**Review by joshuarrrr — APPROVED** [review]

**Pull request merged**
