### PR TITLE
Fix Lint Checker error due to unvisiable URL

### PR DESCRIPTION
**Pull request by ananzh**
### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6412

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by AMoo-Miki** [comment]
This seems to be a flaw with the link checker. Is there an updated version or a better way than adding ignores?

**Review by AMoo-Miki — APPROVED** [review]

**Comment by yujin-emma** [comment]
Thanks for quickly fixing the lint issue

**Review by ashwin-pc — APPROVED** [review]

**Review by bandinib-amzn — APPROVED** [review]

**Comment by yujin-emma** [comment]
Seems there is a flaky test fail

**Comment by tianleh** [comment]
Thanks for the fix!

**Pull request merged**
