### PR TITLE
[Manual][Backport 2.x]Add sidecar service (#5920)

### PR DESCRIPTION
**Pull request by raintygao**
This is cherry pick of https://github.com/opensearch-project/OpenSearch-Dashboards/commit/c2c4f53f140a655705e0e8830ea14e8d958a8de9 from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5920

### CODE REVIEW

**Comment by wanglam** [comment]
@raintygao We may need backport the `CHANGELOG.md` too.

**Comment by raintygao** [comment]
> @raintygao We may need backport the `CHANGELOG.md` too.

As i see other backport PRs to 2.x, they don't contain changelog changes, and there is no feature content in changelog of 2.x.

**Review by SuZhou-Joe — APPROVED** [review]
Confused on the CHANGELOG, but it seems many commit pushed to 2.x do not have CHANGELOG.md either.

**Comment by raintygao** [comment]
> Confused on the CHANGELOG, but it seems many commit pushed to 2.x do not have CHANGELOG.md either.

Confused too, so I will keep consistent with other backport PRs to 2.x for now.

**Review by ruanyl — APPROVED** [review]

**Pull request merged**
