### PR TITLE
[Data Explorer] Fix darkmode for histogram

### PR DESCRIPTION
**Pull request by abbyhu2000**
### Description
Fix darkmode for histogram. Previously after switching to darkmode, histogram still have light mode color scheme.

## Screenshot

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/43937633/ff12ff69-9513-474e-a585-31036f444806

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ananzh** [comment]
Screenshot 2023-08-30 at 13 21 27

Compared with legacy, seems the LineAnnotation is not fetching dark mode properly? But I think we should merge in this one and then create an issue to research on it.

**Review by ananzh — APPROVED** [review]

**Review by ashwin-pc — APPROVED** [review]

**Comment by joshuarrrr** [comment]
It looks like you were able to grab the changes necessary; the PR that fixed this for legacy discover is https://forum.opensearch.org/t/feedback-experimental-feature-connect-to-external-data-sources/11144

**Comment by joshuarrrr** [comment]
@abbyhu2000 Did you test with the new `next` theme?

**Comment by ashwin-pc** [comment]
@joshuarrrr how do you do that?

**Comment by joshuarrrr** [comment]
You can toggle it in Advanced Settings - just search for "theme"

**Comment by abbyhu2000** [comment]
> @abbyhu2000 Did you test with the new `next` theme?

No i have not, how do we enable the `next` theme? @joshuarrrr

**Comment by joshuarrrr** [comment]
See https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4858#issuecomment-1700295629. Just choose Next (preview) from the theme selector.

**Pull request merged**
