### PR TITLE
[Backwards Compatibility][OSD]add test data

### PR DESCRIPTION
**Pull request by ananzh**
### Description
This PR contains 13 zipped bwc test data for osd without bundle.
The data has been tested by osd-1.1 and osd-1.2. To use, here are
the steps:
1)unzip the data to opensearch, for example:
tar -xvf odfe-1.13.2.tar.gz
You need to remove data folder first if there is one in opensearch
2)run opensearch: ./bin/opensearch
3)run dashboards: ./bin/opensearch-dashboards
4)run any cypress test

### Partially Resolved:
https://github.com/opensearch-project/opensearch-build/issues/705

Signed-off-by: Anan Zhuang <ananzh@amazon.com>

 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by boktorbb-amzn — APPROVED** [review]

**Comment by kavilla** [comment]
nit: does the file path have to `test-data/osd/$data.tar.gz`?  Could it just be like `data/$data.tar.gz`. Reflecting there is a `integration/osd` as well. Do we need the `osd` part?

**Comment by tmarkley** [comment]
> The data has been tested by osd-1.1 and osd-1.2. To use, here are the steps: ...

Can we add this documentation somewhere? Maybe in [TESTING.md](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/TESTING.md)? Overall, it might be good to describe the state of backwards compatibility tests there as well.

**Comment by ananzh** [comment]
> 

will check where could document. Once all the PRs get merged especially the scripts get approved, I will submit a PR.

**Review by tmarkley — APPROVED** [review]
I see that you're adding instructions in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1030, thanks! This PR looks good.

**Pull request merged**
