### PR TITLE
Functional test updates

### PR DESCRIPTION
**Pull request by kavilla**
### Description
More updates related to functional tests that need to be fix for them to pass. Ignoring the map related functional tests for now (link to [issue](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/221)). This does not fix all of the functional tests but there is a remaining ~10 functional tests that are passing.
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/247
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass (besides some functional)
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by kavilla** [comment]
Current failures: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/247#issuecomment-823909899

Please note two failures: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/247#issuecomment-823910562

**Review by mihirsoni — APPROVED** [review]
LGTM !! Thanks @kavilla  for all the hard work and making great progress. 
Couple of question, the `.ndjson` file would be great if we can add some documentation around what is significance of it as well as are these somehow auto generated ?.

I see many new files but no deletion, were they deleted as part of previous wipeout ?

**Comment by kavilla** [comment]
> Couple of question, the `.ndjson` file would be great if we can add some documentation around what is significance of it as well as are these somehow auto generated ?.

I manually updated the `.ndjson` files but from my understanding it must have been originally exported while the sample data was originally created. Basically it loads all the saved data for functional tests.

> I see many new files but no deletion, were they deleted as part of previous wipeout ?

Some files were deleted due to logos. But I believe most of them (for example the zip files) is just github showing them as 100% modified but it's not good at showing diffs in zip files. But I had to unzip them and replace values in there.

**Review by boktorbb-amzn — APPROVED** [review]
LGTM

**Review by ananzh — APPROVED** [review]

**Pull request merged**
