### PR TITLE
fix(vis_type_vega): Use default categorical color palette directly

### PR DESCRIPTION
**Pull request by joshuarrrr**
### Description

rather than relying on vega.scheme. Also update vega.scheme name

#### Before

https://user-images.githubusercontent.com/1679762/228105161-4688eba4-cb85-4fea-9149-18e1df25cde9.mov

#### After

(note that the color palette scale is still applied correctly)
 
https://user-images.githubusercontent.com/1679762/228105170-39bdadb5-1d1c-4dcd-b520-9b37fada789b.mov

#### Possible Breaking Change

The only usage of the `elastic` custom scheme previously was to set the default value for `config.range.category`, and that behavior is restored by this PR. However, it was previously possible to explicitly set `scheme: "elastic"` within a spec - that's no longer possible. I think it's highly unlikely that there's a vega property that accepts a `scheme` property that doesn't also use the default `config.range.category`, but it may be possible. I'm also unsure if elastic ever documented any such usage. But my personal judgement is that this is unlikely to break any real user specs.

### Issues Resolved
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3582
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by lezzago — APPROVED** [review]

**Comment by abbyhu2000** [comment]
@joshuarrrr I think this is missing a changelog entry?

**Comment by joshuarrrr** [comment]
@abbyhu2000 Yeah, it also needs a regression test case.

**Comment by joshuarrrr** [comment]
I looked more deeply into this, and I can't really figure out what the root cause is. It appears this is a regression caused by bumping vega from 5.22.1 to 5.22.3: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3533

But none of the changes really jump out at me as a possible cause: https://github.com/vega/vega/releases/tag/v5.23.0

Using a reference to the `elastic` scheme still parses correctly from vega-lite to vega, but fails when executing the vega spec.

Given the above I'm not sure a regression test is particularly helpful in this case. While using the `scheme` would be nice, the fix here is probably more robust and just as good given our current vega implementation.

**Comment by joshuarrrr** [comment]
Changelog isn't necessary, as this is a minor re-implementation to fix an unreleased regression.

**Review by ananzh — APPROVED** [review]
I think the change seems to be beneficial for improved accessibility and error resolution. If the assessment is correct, the risks should be minimal. I also see tests been added which is good.

**Review by ashwin-pc — APPROVED** [review]

**Pull request merged**
