### PR TITLE
[CI][BWC] Date range for tests incorrect params

### PR DESCRIPTION
**Pull request by kavilla**
### Description
Incorrectly set the date range of the library. This sets the value
correctly and turns the dates into constants.

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Resolved
n/a
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by joshuarrrr** [comment]
What was actually incorrect with the previous inlined version? I'm not spotting the obvious bug...

**Review by ananzh — APPROVED** [review]
LGTM

**Comment by kavilla** [comment]
> What was actually incorrect with the previous inlined version? I'm not spotting the obvious bug...

I was passing in a single string instead of 2. So it was treated as a single interpolated string 😢

**Comment by joshuarrrr** [comment]
> > What was actually incorrect with the previous inlined version? I'm not spotting the obvious bug...
> 
> I was passing in a single string instead of 2. So it was treated as a single interpolated string 😢

Aha! Yeah, my eyes totally glazed over that - each time I saw it as 2 args 😭

**Pull request merged**
