### PR TITLE
Retain the original sample data interface

### PR DESCRIPTION
**Pull request by kristenTian**
### Description

In previous sample data commits, the sample data interface was updated to accept data source related params. This change is to add back the original interface given they are actively used by other plugins.

e.g. Map plugin: 

`home.sampleData.addSavedObjectsToSampleDataset('flights', getFlightsSavedObjects(config));`

## Screenshot

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/105667444/3dea31e6-9f80-486b-a7a4-c424dadb53d3

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by ZilongX — DISMISSED** [review]

**Comment by ZilongX** [comment]
Missing a change log entry and would need to pick up from latest main branch

**Comment by seraphjiang** [comment]
What test has been done for the change? how did we find the issue?

**Comment by kristenTian** [comment]
> What test has been done for the change? how did we find the issue?

There are UTs and cypress, also see the screenshot for manual testing. We got notified by Map team for this issue.

**Comment by ZilongX** [comment]
Also are we planning to add this change back (with coordination with impacted plugin teams)  say in next minor release ?

**Comment by kristenTian** [comment]
> Also are we planning to add this change back (with coordination with impacted plugin teams) say in next minor release ?

I didn't revert anything. The new feature is still supported, see the screenshot vedio. Adding back the original interface for existing plugin client support.

**Comment by ZilongX** [comment]
> > Also are we planning to add this change back (with coordination with impacted plugin teams) say in next minor release ?
> 
> I didn't revert anything. The new feature is still supported, see the screenshot vedio. Adding back the original interface for existing plugin client support.

I see, so instead of overwrite the old interface now you give it a new name so both could co-exist.

**Comment by junqiu-lei** [comment]
Thanks @kristenTian. Currently maps-dashboards plugin got error when yarn start with OSD due to https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4526 , which may block 2.9 release. Just tested the latest change on this PR that can help fix the error.

cc @vamshin 

error logs:
```
islib,visTypeTimeseries,visTypeTagcloud,visTypeMetric,discover,savedObjectsManagement,bfetch]
server    log   [21:08:37.718] [fatal][root] TypeError: sampleDataset.savedObjects.concat is not a function
    at Object.addSavedObjectsToSampleDataset (/Users/junqiu/WebstormProjects/OpenSearch-Dashboards/src/plugins/home/server/services/sample_data/sample_data_registry.ts:119:65)
    at CustomImportMapPlugin.addMapsSavedObjects (/Users/junqiu/WebstormProjects/OpenSearch-Dashboards/plugins/dashboards-maps/server/plugin.ts:45:21)
    at CustomImportMapPlugin.setup (/Users/junqiu/WebstormProjects/OpenSearch-Dashboards/plugins/dashboards-maps/server/plugin.ts:74:20)
    at PluginsSystem.setupPlugins (/Users/junqiu/WebstormProjects/OpenSearch-Dashboards/src/core/server/plugins/plugins_system.ts:115:24)
    at PluginsService.setup (/Users/junqiu/WebstormProjects/OpenSearch-Dashboards/src/core/server/plugins/plugins_service.ts:142:19)
    at Server.setup (/Users/junqiu/WebstormProjects/OpenSearch-Dashboards/src/core/server/server.ts:217:26)
    at Root.setup (/Users/junqiu/WebstormProjects/OpenSearch-Dashboards/src/core/server/root/index.ts:64:14)
    at bootstrap (/Users/junqiu/WebstormProjects/OpenSearch-Dashboards/src/core/server/bootstrap.ts:132:5)
    at Command.<anonymous> (/Users/junqiu/WebstormProjects/OpenSearch-Dashboards/src/cli/serve/serve.js:226:5)
server    log   [21:08:37.806] [info][plugins-system] Stopping all plugins.
```

**Review by ZilongX — APPROVED** [review]

**Comment by Flyingliuhub** [comment]
Is it possible to include all other plugins when starting OSD for testing, and make sure all other plugins not affected and can start during OSD.  @joshuali925 got the same error when starting OSD with observability.

**Comment by kristenTian** [comment]
> Is it possible to include all other plugins when starting OSD for testing, and make sure all other plugins not affected and can start OSD. @joshuali925 got the same error when starting OSD with observability.

@Flyingliuhub This change will help with all similar use cases.

**Review by zhongnansu — APPROVED** [review]
thx for the fix

**Pull request merged**
