### PR TITLE
[Deangular] OSD without angular

### PR DESCRIPTION
**Pull request by ashwin-pc**
### Description

Removes Angular from the OpenSearch Dashboards and all related angular dependencies.

### Issues Resolved

mostly closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1560

## Testing the changes

OSD should work as expected without any issues

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by kavilla** [comment]
I think ciGroup1 for build and test failed the linter step if we want to fix?

**Comment by kavilla** [comment]
Barring the linter failer, I think it's good to go to bake. I was clicking around trying weird workflows and it is working as expected.

Example: Dashboards required the bootstrap Angular for Discover otherwise it wouldn't render the Discover.

Tmrw I will run the build repo script with the plugins but I don't think that should block this PR once the linter is fixed.

**Review by ananzh — APPROVED** [review]

**Comment by ananzh** [comment]
I have reviewed this in the feature branch. We also opened issues for existing bugs and un-updated documents.

**Review by abbyhu2000 — APPROVED** [review]

**Comment by ashwin-pc** [comment]
All cypress test failures are unrelated to the PR, there is a cypress test issue in main as well. Changelog will be added in a followup PR and linked to this PR

**Comment by seanneumann** [comment]
OMGOMGOMGOMG!!!!! w0000tttt!!!!

**Pull request merged**
