### PR TITLE
Don't terminate the server on NodeDeprecationWarning

### PR DESCRIPTION
**Pull request by ginkel**
The last AWS SDK for Javascript that supports Node 10 (v3.45.0) emits a NodeDeprecationWarning to indicate that Node 10
is no longer supported. Without this workaround, this crashes the OSD server, so it becomes impossible to interact with
other AWS services from within OSD (e.g., in a custom plugin) until the Node 14 upgrade is done.

Signed-off-by: Thilo-Alexander Ginkel <tg@tgbyte.de>

### Description
See above. Without this fix the OSD server crashes with the following warning as soon as any AWS SDK functionality is used:

```
(node:74504) NodeDeprecationWarning: The AWS SDK for JavaScript (v3) will
no longer support Node.js v10.24.1 as of January 1, 2022.
To continue receiving updates to AWS services, bug fixes, and security
updates please upgrade to Node.js 12.x or later.

More information can be found at: https://a.co/1l6FLnu
Node.js process-warning detected:

NodeDeprecationWarning: The AWS SDK for JavaScript (v3) will
no longer support Node.js v10.24.1 as of January 1, 2022.
To continue receiving updates to AWS services, bug fixes, and security
updates please upgrade to Node.js 12.x or later.

More information can be found at: https://a.co/1l6FLnu
    at Object.emitWarningIfUnsupportedVersion (/home/tg/workspace/OpenSearch-Dashboards/plugins/.../node_modules/@aws-sdk/smithy-client/dist-cjs/emitWarningIfUnsupportedVersion.js:8:17)
    at Object.getRuntimeConfig (/home/tg/workspace/OpenSearch-Dashboards/plugins/.../node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js:24:21)
    at new S3Client (/home/tg/workspace/OpenSearch-Dashboards/plugins/.../node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js:19:43)
    at <redcated>
    at <redcated>
    at /home/tg/workspace/OpenSearch-Dashboards/src/core/utils/context.ts:261:14
    at process._tickCallback (internal/process/next_tick.js:68:7)

Terminating process...
 server crashed  with status code 1
```
 
### Issues Resolved
n/a
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [x] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by boktorbb-amzn** [comment]
Hello @ginkel could you post some replication steps for this error and some info on Dashboards version used? Currently, the node 14 upgrade is merged into main.

**Comment by ginkel** [comment]
> Hello @ginkel could you post some replication steps for this error and some info on Dashboards version used? Currently, the node 14 upgrade is merged into main.

Ah, the issue is happening with 1.2.0. Depending on the 2.0.0 timeline we can wait until that's available instead of needing a workaround for 1.2.0.

**Comment by boktorbb-amzn** [comment]
Hey @ginkel I think it may still be valuable to merge these changes into our branch since we may run into this again in the future. I will finish running some tests and will approve the PR at that time

**Comment by ginkel** [comment]
Excellent, thanks for your positive feedback!

**Review by boktorbb-amzn — APPROVED** [review]
Sorry for the delay. Looks good

**Review by tmarkley — APPROVED** [review]

**Comment by tmarkley** [comment]
Should we target the `1.x` branch for this instead of `main` since `main` is our latest 2.0 code which won't need this change?

**Comment by ginkel** [comment]
> Should we target the `1.x` branch for this instead of `main` since `main` is our latest 2.0 code which won't need this change?

A fix for 1.x was my original intention, so that would make sense from my point of view. I can change the target if everyone agrees.

**Comment by boktorbb-amzn** [comment]
> Should we target the `1.x` branch for this instead of `main` since `main` is our latest 2.0 code which won't need this change?

I think having this in main to cover any possible future node deprecation warnings would be a good thing. We can backport this change to 1.x as well.

**Comment by tmarkley** [comment]
> > Should we target the `1.x` branch for this instead of `main` since `main` is our latest 2.0 code which won't need this change?
> 
> I think having this in main to cover any possible future node deprecation warnings would be a good thing. We can backport this change to 1.x as well.

That makes sense.

**Pull request merged**
