### PR TITLE
[Bug] fix incorrect import for opensearch aggs

### PR DESCRIPTION
**Pull request by kavilla**
### Description
Incorrect import statement that was introduced here:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/688

Verified other imports and the rest look fine.

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Resolved
n/a
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by tmarkley — APPROVED** [review]
So is this broken in 1.2?

**Comment by kavilla** [comment]
> So is this broken in 1.2?

It would appear so.

**Review by ananzh — APPROVED** [review]

**Review by tmarkley — APPROVED** [review]
LGTM! Are we targeting `1.3.0`?

**Comment by kavilla** [comment]
> LGTM! Are we targeting `1.3.0`?

We should! Will backport!

**Pull request merged**
