### PR TITLE
Bump `joi` to v14 to avoid the possibility of prototype poisoning in a nested dependency

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description

The `clone` method in `hoek@5`, a dependency of `joi@13`, uses [techniques](https://github.com/hapijs/hoek/blob/v5.0.4/lib/index.js#L80) that make prototype poisoning possible. The flaw [doesn't exist](https://github.com/hapijs/hoek/blob/v6.1.3/lib/index.js#L97-L102) in `hoek@6`, a dependency of `joi@14`.

### Check List

- [X] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by zhongnansu — COMMENTED** [review]
@AMoo-Miki Do we need to update joi in `osd-config-schema` as well?
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/ac2ee3a3ee5c0d56243c7a2d731b8743bbd77ab8/packages/osd-config-schema/package.json#L19

**Review by zhongnansu — DISMISSED** [review]

**Review by seanneumann — DISMISSED** [review]
Looks good. Would be great to get this into 2.7.

**Review by zhongnansu — APPROVED** [review]

**Review by ashwin-pc — APPROVED** [review]

**Comment by joshuarrrr** [comment]
This didn't actually ship in 1.3.10, so I've updated the label.

**Comment by manasvinibs** [comment]
Backported to 2.x here https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4206

**Pull request merged**
