### PR TITLE
Bump the version to 1.3.1

### PR DESCRIPTION
**Pull request by zelinh**
Signed-off-by: Zelin Hao <zelinhao@amazon.com>

### Description
Increment to the next patch version 1.3.1
Version bumps have been done for main branch and 1.x branch. 

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [x] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by kavilla** [comment]
Shall we bump all the patch versions on every branch? Will this be standardize across every repo?

**Comment by zelinh** [comment]
> Shall we bump all the patch versions on every branch? Will this be standardize across every repo?

I think currently after 1.3 release, we bump the patch version on 1.3 branch for core and dashboards in case of any potential release. We don't increment patch version on 1.x or main since 1.x should be bumped with Minor and main for major version change.

**Comment by kavilla** [comment]
More so, should we bump other branches like [1.2](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1.2/package.json#L14) to be on 1.2.1?

**Comment by zelinh** [comment]
> More so, should we bump other branches like [1.2](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1.2/package.json#L14) to be on 1.2.1?

No. I don't think that's needed since we already released 1.3. Our 1.2.1 release was about log4j so we don't concern with Dashboards.

**Comment by kavilla** [comment]
> > More so, should we bump other branches like [1.2](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/1.2/package.json#L14) to be on 1.2.1?
> 
> No. I don't think that's needed since we already released 1.3. Our 1.2.1 release was about log4j so we don't concern with Dashboards.

Is there a plan for OpenSearch Dashboards `1.3.1` then? I'm not sure if we have any changes planned for that on our side.

**Comment by tmarkley** [comment]
Seems like since we [canceled 1.4.0](https://github.com/orgs/opensearch-project/projects/1) we can target `1.x` for this change.

**Review by kavilla — APPROVED** [review]

**Review by boktorbb-amzn — APPROVED** [review]

**Pull request merged**
