### PR TITLE
Refactor hardcode color to use OUI in `maps_legacy`

### PR DESCRIPTION
**Pull request by BSFishy**
### Description

Changes a hardcoded color to use a color from the OUI theme. This is a black color, so I changed it to `euiColorInk`, which is meant to be either black or close to it.

### Issues Resolved

Partial js component of #4289

### Screenshots

**New**
Screenshot (82)

**Orange for reference**
Screenshot (80)

## Testing the changes

Ran:
 - `yarn test:jest`
 - `yarn test:jest_integration`
 - `yarn test:mocha`
 - `yarn build-platform --linux --release`

### Check List

- [ ] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by BSFishy** [comment]
Need UX guidance on whether or not this is the correct color to use @KrooshalUX

**Comment by KrooshalUX** [comment]
In general, that is correct - any hard coded black can/should be replaced with reference to OuiColorInk. 

However, before I can verify that its the right color overall - is there a screenshot of the use of the color?

**Comment by BSFishy** [comment]
> However, before I can verify that its the right color overall - is there a screenshot of the use of the color?

@KrooshalUX updated PR description to include screenshots

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Review by manasvinibs — APPROVED** [review]

**Comment by BSFishy** [comment]
@manasvinibs @joshuarrrr should this be backported?

**Review by KrooshalUX — APPROVED** [review]
LGTM

**Review by joshuarrrr — APPROVED** [review]

**Review by manasvinibs — APPROVED** [review]

**Pull request merged**
