### PR TITLE
Remove duplicate sample data as id 90943e30-9a47-11e8-b64d-95841ca0b2…

### PR DESCRIPTION
**Pull request by zhyuanqi**
### Description

Remove duplicate sample data as id 90943e30-9a47-11e8-b64d-95841ca0b247 appears twice on line 273 and 404. Duplicate entry.

### Issues Resolved
No related issue with it. 

## Testing the changes
Since we only delete old record of id 90943e30-9a47-11e8-b64d-95841ca0b247. No record still exists on line 404. Visualization stays the same

### Check List

- [ ] All tests pass
  - [N] `yarn test:jest` (Two tests failed in my local.  log_rotator.test.ts and create_os_package_tasks.test.ts. I don't think they are related to my change though)
  - [Y] `yarn test:jest_integration`
- [N] New functionality includes testing.
- [N] New functionality has been documented.
- [N] Update [CHANGELOG.md](./../CHANGELOG.md)
- [N] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by manasvinibs — DISMISSED** [review]

**Comment by SuZhou-Joe** [comment]
1. Firstly, could you please fix the DCO error?
2. Change log entry is missing.
3. Could you please confirm that if the duplicate entry was added by mistake or by intention(as it may used for checking if OpenSearch can filter the duplicate import in bulk)? If you already know the answer, please add that in your PR's description so that we can safely approve this PR.

**Comment by joshuarrrr** [comment]
> Could you please confirm that if the duplicate entry was added by mistake or by intention(as it may used for checking if OpenSearch can filter the duplicate import in bulk)? If you already know the answer, please add that in your PR's description so that we can safely approve this PR.

It looks like this was my mistake, introduced in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4339, so I can vouch for it being unintentional 😁 

I am interested to understand what error or issues it causes - @zhyuanqi how did you happen to discover it?

**Comment by zhyuanqi** [comment]
Hi I will add the change log and signoff in the next revision. Thanks.
So we found out this error when we try to import the sample data to S3 use id as key. It showed duplicate key. This is how to found out about this error.

**Comment by zhyuanqi** [comment]
Close this pull request as created a new one https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5668

**Comment by zhyuanqi** [comment]
Close this pull request as created a new one https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5668

**Comment by zhyuanqi** [comment]
Close this pull request as created a new one https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5668

**Pull request closed without merging**
