### PR TITLE
[Navigation] Update dev tools tab css for new left navigation

### PR DESCRIPTION
**Pull request by ps48**
### Description

As part of new left navigation Workbench would be moved to dev tools. To make this happen we have registered workbench based on the new nav condition. The css in devtools is making the tabs justify apart `justify-content: space-between;`. Removing this css is fixing the UI and keeping it as expected. This PR removes the unnecessary css on dev tools Tab.

### Issues Resolved

Related Workbench PR: https://github.com/opensearch-project/dashboards-query-workbench/pull/349 

## Screenshot

Before:
Screenshot 2024-07-19 at 3 14 04 PM

After:
Screenshot 2024-07-19 at 3 15 11 PM
Screenshot 2024-07-19 at 3 15 21 PM

## Testing the changes

1. Load dashboards core in local setup
2. Add workbench plugin from main/2.x branch
3. Add the feature flag for new nav. 
4. Move to dev tools and looks at the tabs spacing. 

## Changelog 
- fix: [Navigation] Update dev tools tab css for new left navigation

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ps48** [comment]
@mengweieric @SuZhou-Joe Can you please help review the PR and backport this to 2.x? I am a first time contributor to OSD core. Would be grateful to understand if I am missing something here.

**Review by SuZhou-Joe — APPROVED** [review]

**Comment by SuZhou-Joe** [comment]
Could you please post a screenshot of how the devTools will look like without query workbench plugin installed under your change?

**Comment by mengweieric** [comment]
Could we check if the failing CI is relevant?

**Review by mengweieric — APPROVED** [review]

**Comment by ps48** [comment]
> Could you please post a screenshot of how the devTools will look like without query workbench plugin installed under your change?

Hi @SuZhou-Joe, This is how dev tool looks like without workbench
Screenshot 2024-07-20 at 8 02 05 AM

**Pull request merged**
