### PR TITLE
Fixes misleading embeddable plugin error message

### LINKED ISSUE #1479: [BUG] Maps license error is misleading
**Describe the bug**

Coming from https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1431

image

**Expected behavior**
The error shouldn't reference a license; it should say that the maps service is unavailable.

**OpenSearch Version**
1.x

**Dashboards Version**
1.x

**Plugins**

N/A

### PR DESCRIPTION
**Pull request by tmarkley**
### Description
I took the initiative to decide what the new message should say, but I'm open to suggestions.
 
### Issues Resolved
Resolves #1479, #3083
 
### Check List
- [x] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [x] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ashwin-pc** [comment]
I like the wording, I only wonder if service is the right word. Object or even component might make more sense here. 

cc: @KrooshalUX

**Comment by tmarkley** [comment]
> I like the wording, I only wonder if service is the right word. Object or even component might make more sense here.
> 
> cc: @KrooshalUX

Yeah I can definitely make that change! At this point almost anything is better than what it is currently.

**Comment by joshuarrrr** [comment]
lol, I'm glad I happened to look at this PR today - we had another issue opened up about this exact error string: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3083

We also got some finalized wording to use https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3083#issuecomment-1353742791: `OpenSearch Dashboards can't load "{type}" visualizations. Check for a missing plugin or an incompatible visualization type.`

**Review by ashwin-pc — APPROVED** [review]

**Comment by KrooshalUX** [comment]
@natebower @vagimeli would you mind taking a look at what @ashwin-pc is asking about copy? Thanks!

**Comment by natebower** [comment]
> @natebower @vagimeli would you mind taking a look at what @ashwin-pc is asking about copy? Thanks!

@KrooshalUX I think this may have already been resolved. Or I'm just not seeing what needs my attention.

**Comment by vagimeli** [comment]
> > @natebower @vagimeli would you mind taking a look at what @ashwin-pc is asking about copy? Thanks!
> 
> @KrooshalUX I think this may have already been resolved. Or I'm just not seeing what needs my attention.

I don't see that verbiage in the copy.

**Review by joshuarrrr — APPROVED** [review]

**Review by ashwin-pc — APPROVED** [review]

**Pull request merged**
