### PR TITLE
[OSCI][Fix][Discover]Prevent Adding Timefield to the Side Nav Selected Fields on Column Removal

### PR DESCRIPTION
**Pull request by MadaniKK**
### Description
Issue #5527: Now the time field of an index pattern would not get wrongly added to the selected field when we click `remove column` on canvas.

Issue #5538:  When doc_table:hideTimeColumn is enabled, removing the last columns from the canvas would automatically add "_source" to the selected fields in the left nav bar.

### Issues Resolved
issue #5527 #5538 

## Screenshot
For #5527
image
image

For #5538 
 
image

image

### Check List

- [x ] All tests pass
  - [x ] `yarn test:jest`
  - [ x] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by joshuarrrr** [comment]
@MadaniKK Can you add a changelog entry?

**Comment by MadaniKK** [comment]
> @MadaniKK Can you add a changelog entry?

Hi, Josh, I found another bug (issue #5538) when I wrote this PR, and I found out I could fix it within the same PR. should I make a new PR or fix these two issues in the same PR? ( I just needed to reorder two lines of codes that I wrote in this PR and it will fix issue #5538  too)

**Comment by ananzh** [comment]
@MadaniKK love these fixes and thanks a lot. I will re-run the failed cypress tests and update you.

**Comment by ananzh** [comment]
@MadaniKK, for https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5538, your understanding seems not quite right.

This advanced setting `doc_table:hideTimeColumn` is to allow Discover and Saved Search in Dashboard to not display `timestamp` column (first column) when enabled for a time based index pattern . Without this setting, for time based index pattern, display `timestamp` column is default and user can't remove it.

For the legacy Discover, we could have a better understanding

* after enabling `doc_table:hideTimeColumn`
Screenshot 2023-12-01 at 4 53 02 PM

The buildColumns fun itself will make sure when no columns `return ['_source']`:
```
export function buildColumns(columns: string[]) {
  if (columns.length > 1 && columns.indexOf('_source') !== -1) {
    return columns.filter((col) => col !== '_source');
  } else if (columns.length !== 0) {
    return columns;
  }
  return ['_source'];
}
```

Therefore, the problem is why enabling `doc_table:hideTimeColumn` will cause https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5538 and how could fix it. I think we haven't implement the logic for this advanced settings.

**Comment by ananzh** [comment]
@MadaniKK I would suggest targeting https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5527 in this PR and re-check if all logics are needed if just fixing this specific issue. 

Then start another PR to make sure we have time field removed when enabling `doc_table:hideTimeColumn`. What do you think?

**Review by ananzh — CHANGES_REQUESTED** [review]
Would like to research on `doc_table:hideTimeColumn` and find out the root cause of the break. Thanks a lot for carefully checking these settings.

**Review by ananzh — DISMISSED** [review]
I think this is an acceptable change to fix all the bugs together. @MadaniKK could you select and add more explains here from public slack? Also there is a conflict on CHANGELOG. Thanks.

**Review by ananzh — APPROVED** [review]

**Review by ashwin-pc — APPROVED** [review]

**Pull request merged**
