### PR TITLE
Rename files on disk needed for systemd and service start.

### PR DESCRIPTION
**Pull request by shdubsh**
### Description
Files renamed to where systemd expects and runtime username
and group name changed to a supported form.

### Issues Resolved
The Debian packages build ok with fpm, but installing it fails due
to an invalid username and group name (see useradd(8): CAVEATS).
Once this was fixed, the service failed to start due to parts of the startup
configuration wanting files that did not exist on disk.
  
### Check List
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by dblock — APPROVED** [review]

**Review by mihirsoni — APPROVED** [review]
LGTM !! Thanks for your changes. I also created issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/303

**Review by mihirsoni — COMMENTED** [review]
@shdubsh Just realized the filename changes as well, any reason for renaming the file ? We are following overall naming convention and file names are following mostly `_` notion instead of `-`

**Comment by shdubsh** [comment]
> @shdubsh Just realized the filename changes as well, any reason for renaming the file ? We are following overall naming convention and file names are following mostly `_` notion instead of `-`

A few reasons to consider:

### Underscores for system configuration files makes the compiled package inconsistent.

Prior to this patch, these files and folders are created by fpm:

1. File `/etc/default/opensearch_dashboards`
2. File `/etc/init.d/opensearch_dashboards`
3. File `/usr/lib/tmpfiles.d/opensearch_dashboards.conf`
4. File `/etc/systemd/system/opensearch_dashboards.service`
5. Directory `/etc/opensearch-dashboards`
6. Directory `/usr/share/opensearch-dashboards`
7. Directory `/usr/share/doc/opensearch-dashboards`

In addition `/etc/systemd/system/opensearch_dashboards.service` is looking for the environment file at `EnvironmentFile=-/etc/default/opensearch-dashboards` which systemd will not find.

After this patch, these files and folders are created by fpm:

1. File `/etc/default/opensearch-dashboards`
2. File `/etc/init.d/opensearch-dashboards`
3. File `/usr/lib/tmpfiles.d/opensearch-dashboards.conf`
4. File `/etc/systemd/system/opensearch-dashboards.service`
5. Directory `/etc/opensearch-dashboards`
6. Directory `/usr/share/opensearch-dashboards`
7. Directory `/usr/share/doc/opensearch-dashboards`

All files and directories captured in the package after this patch are consistent.

Renaming these files to be hyphenated also fixes systemd unable to start due to not being able to locate configuration files at `/usr/share/opensearch-dashboards/config` due to being unaware of `OSD_PATH_CONF="/etc/opensearch_dashboards"` in `/etc/default/opensearch_dashboards`.  It was quite confusing to look and see that OpenSearch-Dashboards was configured to find its config in `/etc/opensearch_dashboards`, yet no folder `/etc/opensearch_dashboards` exists.  Even if a user were to edit `/etc/default/opensearch_dashboards` to `OSD_PATH_CONF="/etc/opensearch-dashboards"`, the same runtime error would be presented because systemd isn't loading `/etc/default/opensearch_dashboards` into the environment in the first place.

### Underscores here may be contrary to Debian policy

Although it may be possible to coerce fpm to rename the Package so that opensearch-dashboards takes the underscore in `/etc/` and `/usr/share`, this may fall foul with [Debian policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-source).  `Package names (both source and binary, see Package) must consist only of lower case letters (a-z), digits (0-9), plus (+) and minus (-) signs, and periods (.).`  I recognize that this reason may be invalid as OpenSearch-Dashboards isn't built in a way to follow Debian policy.

### Simplicity

Renaming these files is a simple way to resolve the problems in the built Debian artifact.

**Review by kavilla — APPROVED** [review]
> https://github.com/opensearch-project/OpenSearch-Dashboards/pull/302#issuecomment-823718064

Thank you for the explanation!

**Pull request merged**
