### PR TITLE
[FIX]: panel header

### LINKED ISSUE #5145: [BUG][Discover] Panel header says `Open search`
**Describe the bug**
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/discover/public/application/components/top_nav/open_search_panel.tsx#L70

**To Reproduce**
Navigate to Discover page, click on `Open`. Notice the header says `Open search`

**Expected behavior**
I believe it should say `OpenSearch` but even still I'm not quite that makes sense.

**Dashboards Version**
All

### PR DESCRIPTION
**Pull request by bibaswan7**
### Description

When navigated to discover page and clicked on Open, the header shows "Open search", while it should be showing "OpenSearch"

### Issues Resolved

#5145 

### Check List

- [ ] All tests pass
  - [x] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ashwin-pc** [comment]
@bibaswan7 your PR diff looks like it contains changes that are unrelated to the issue here

**Comment by bibaswan7** [comment]
> @bibaswan7 your PR diff looks like it contains changes that are unrelated to the issue here

The first commit contains the necessary change to fix the issue, while the second commit is about updating the snapshot. Please let me know if I made any mistake.

**Comment by bibaswan7** [comment]
I really want to make my first contribution, please help me

**Comment by ashwin-pc** [comment]
Judging by the changes in your PR, it looks like the updating snapshots command is the cause of the issue. Make sure to only commit changes that you intend. I'd suggest reverting the update snapshots commit. If a snapshot needs to be updated, only update the required snapshot.

My hunch for why you see this issue is that your editor is auto formatting all these files even though it should not. But thats just a hunch since i dont know more about what the issue here is.

**Comment by bibaswan7** [comment]
Oh I didn't realize my VS code was auto formatting these files. Thanks for your insight.
Anyway, I have reverted the update snapshots commit. Please let me know if its okay now.

**Comment by ananzh** [comment]
I see current fix is good. Seems previous problems are all resolved. I am re-running the failed test. Meanwhile, @bibaswan7 could you add a CHANGELOG?

**Comment by bibaswan7** [comment]
Hi @ananzh I have just added a changelog just like you asked

**Comment by kavilla** [comment]
> I'd suggest reverting the update snapshots commit. If a snapshot needs to be updated, only update the required snapshot.

@bibaswan7, I believe the suggestion here was to ensure the snapshot that is required to successfully run the test is updated and to avoid unrelated updates.

So to check here at the failing test: https://github.com/opensearch-project/OpenSearch-Dashboards/actions/runs/6400770684/job/17378924045?pr=5152

 We can see the failing snapshot coming from this test file:
` src/plugins/discover/public/application/components/top_nav/open_search_panel.test.tsx`

which the suggestion from Ashwin could be accomplished by running:
`yarn test:jest src/plugins/discover/public/application/components/top_nav/open_search_panel.test.tsx -u' and only pushing those changes.

Also, would you be willing to provide your local development env details?

**Comment by Willie-The-Lord** [comment]
Hi @bibaswan7, are you still working on this PR, since I've updated the snapshots for this specific problem and it works on my end. Thanks!

**Comment by bibaswan7** [comment]
> Hi @bibaswan7, are you still working on this PR, since I've updated the snapshots for this specific problem and it works on my end. If you encounter any problem, I'm also glad to help. If you don't mind I can open a PR to fix this issue right now too. Thanks!

Yes, please do @Willie-The-Lord , I am really interested to see what to do with snapshots actually

**Comment by Willie-The-Lord** [comment]
@bibaswan7 Based on the test you failed, which is `ciGroup3`, i ran the following command `yarn test:jest:ci:coverage  --ci-group=3 -u` to update the snapshots.

**Comment by bibaswan7** [comment]
> @bibaswan7 Based on the test you failed, which is `ciGroup3`, i ran the following command `yarn test:jest:ci:coverage --ci-group=3 -u` to update the snapshots.

Ohh thanks @Willie-The-Lord  for clarifying, I wasn't able to figure out what I was supposed to do

**Comment by joshuarrrr** [comment]
I think we can close this one in favor of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5304 ?

**Comment by joshuarrrr** [comment]
@bibaswan7 I'm closing as a duplicate of #5304, but please reopen if that was a mistake.

**Pull request closed without merging**
