### PR TITLE
Validation succeed as long as status code in response is 200

### PR DESCRIPTION
**Pull request by cliu123**
### Description
Data source validation should pass as long as response code is `200` even if response body is empty, for example:
```
{
  body: '',
  statusCode: 200,
  headers: {
    'content-type': 'text/plain; charset=UTF-8',
    'content-length': '0',
    'x-envoy-upstream-service-time': '44',
    date: 'Wed, 10 Apr 2024 06:10:28 GMT',
    server: 'aoss-amazon-m',
    'x-request-id': '284bf59f-4601-9ce9-ba7b-2c2282e34c17'
  },
  meta: {
    context: null,
    request: { params: [Object], options: {}, id: 1 },
    name: 'opensearch-js',
    connection: {
      url: 'https://vywd1o523wrumu9h3q05.gamma-us-east-1.aoss.amazonaws.com/',
      id: 'https://vywd1o523wrumu9h3q05.gamma-us-east-1.aoss.amazonaws.com/',
      headers: {},
      deadCount: 0,
      resurrectTimeout: 0,
      _openRequests: 0,
      status: 'alive',
      roles: [Object]
    },
    attempts: 0,
    aborted: false
  }
}
```

### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6396

### Check List

- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by cliu123** [comment]
@bbarani @gaiksaya @kavilla Could we include this fix in 1.13.1?
Cc: @seraphjiang

**Comment by cliu123** [comment]
@opensearch-project/engineering-effectiveness @opensearch-project/opensearch-dashboards-core  Could we include the fix in 2.13.1?
Cc: @seraphjiang

**Comment by cliu123** [comment]
This fix will be backported to 2.13 branch for next patch release of 2.13.x. 
Discussion: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6396#issuecomment-2048873318

**Comment by seraphjiang** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6396

**Comment by seraphjiang** [comment]
@xinruiba  @bandinib-amzn @Flyingliuhub @ZilongX @BionIT @zhongnansu 

please help to take a look when you got time

**Review by xinruiba — APPROVED** [review]

**Comment by xinruiba** [comment]
LGTM, thanks for this change

**Review by BionIT — APPROVED** [review]

**Pull request merged**
