### PR TITLE
adding documentation on files in util in addition to a README.md with an overview of each file and its exported functions

### PR DESCRIPTION
**Pull request by tanupa**
### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by joshuarrrr** [comment]
Thanks @tanupa , this is an awesome contribution. Can you add an entry to the CHANGELOG file under the Documentation section?

Assigned to @BSFishy and @kavilla to review, as they built out this package and are most familiar to validate the accuracy of the docs.

**Review by kavilla — APPROVED** [review]
Thank you so much!

**Comment by kavilla** [comment]
@joshuarrrr we should consider executing some doc generator to see what we get.

**Review by BSFishy — APPROVED** [review]
LGTM

**Pull request merged**
