### PR TITLE
Add null auth header to child client spawn

### LINKED ISSUE #2182: [BUG] [MD] Update credentials that attached to datasource doesn't give the correct client.
**Describe the bug**

Update credentials that attached to datasource doesn't give the correct client.

**To Reproduce**
1. create 2 credentials. `cred-1`(right username/password) and `cred-2`(in-correct username/password)
2. create a data source `ds-1` attached to `cred-1`
3. create index-pattern `ip-1` that attached to `ds-1`
4. Use `Discover` to search on `ip-1`
5. Able to see data from the `ds-1`
6. update `ds-1` to use `cred-2`, and save
7. Use `Discover` to search on `ip-1`
8. Still seeing data from `ds-1`, which is not supposed to happen, because `cred-2` is not even a correct crendential for `ds-1`

**Expected behavior**

### PR DESCRIPTION
**Pull request by zhongnansu**
Signed-off-by: Su <szhongna@amazon.com>

### Description
Add null auth header to child client spawn. See issue below for more details  and discussion
 
### Issues Resolved
#2182 
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
    - [ ] `yarn test:jest`
    - [ ] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by noCharger** [comment]
Curious if we can add some unit test to cover this edge case.

**Comment by zhongnansu** [comment]
> Curious if we can add some unit test to cover this edge case.

Cypress test is probably a better way to cover this case

**Review by zengyan-amazon — COMMENTED** [review]
shall we use the same way to create no auth client?

**Review by zengyan-amazon — APPROVED** [review]

**Review by noCharger — APPROVED** [review]

**Comment by zhongnansu** [comment]
> shall we use the same way to create no auth client?

Form the manual test result, we don't need the same change in for no auth part

**Pull request merged**
