### PR TITLE
[Manual][Backport 2.x][Vis colors] Update legacy mapped colors in charts plugin to use ouiPaletteColorBlind()

### PR DESCRIPTION
**Pull request by manasvinibs**
### Backport PR:
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4398

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by ashwin-pc — DISMISSED** [review]

**Review by ashwin-pc — COMMENTED** [review]
@manasvinibs can you resolve the conflicts in the PR?

**Review by ananzh — APPROVED** [review]

**Comment by AMoo-Miki** [comment]
I guess the test failure is in `src/plugins/charts/public/services/colors/colors.test.ts` which is one of the conflicting files.

**Comment by manasvinibs** [comment]
This requires more manual testing and might need iterative changes based on feedback from product. Not backporting this PR to 2.x till 2.9 is out as this needs to go in 2.10.

**Comment by manasvinibs** [comment]
Re-opening the PR as 2.9 branch is already cut and this will go as part of 2.10.

**Comment by joshuarrrr** [comment]
@manasvinibs Looks like there are some conflicts to resolve here.

**Review by BSFishy — APPROVED** [review]

**Review by joshuarrrr — CHANGES_REQUESTED** [review]
@manasvinibs I want to hold off on merging this backport for a bit until we figure out the color mapping.

No changes needed to this PR, it's a question of deciding with UX.

**Comment by manasvinibs** [comment]
> @manasvinibs I want to hold off on merging this backport for a bit until we figure out the color mapping.
> 
> No changes needed to this PR, it's a question of deciding with UX.

Sounds good!

**Comment by joshuarrrr** [comment]
I think we should go ahead and merge this and then iterate on top

**Review by joshuarrrr — APPROVED** [review]

**Pull request merged**
