### PR TITLE
[Test] Enable unit test suite: get_local_stats.test.ts

### PR DESCRIPTION
**Pull request by ananzh**
### Description

All the unit tests related to unused telemetry are temporarily
skipped after the fork. Unit tests of the disabled telemetry
functions should also be modified correspondingly. To build
a clean unit test, we decide to modify and enable all the
working unit tests. This PR checks and enables
get_local_stats.test.ts.

Signed-off-by: Anan Zhuang <ananzh@amazon.com>

### Issues Resolved
[#512](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/512)

### Test results
unit test for get_local_stats.test.ts
```
yarn test:jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_local_stats.test.ts
yarn run v1.22.10
$ node scripts/jest /home/anan/work/OpenSearch-Dashboards/src/plugins/telemetry/server/telemetry_collection/get_local_stats.test.ts
 PASS  src/plugins/telemetry/server/telemetry_collection/get_local_stats.test.ts
  get_local_stats
    handleLocalStats
      ✓ returns expected object without OpenSearch Dashboards data (21 ms)
      ✓ returns expected object with xpack (6 ms)
    getLocalStats
      ✓ returns expected object with OpenSearch Dashboards data (30 ms)
      ✓ returns an empty array when no cluster uuid is provided (15 ms)

  console.warn
    No OpenSearchDashboards stats returned from usage collectors

      60 | ) {
      61 |   if (!response) {
    > 62 |     logger.warn('No OpenSearchDashboards stats returned from usage collectors');
         |            ^
      63 |     return;
      64 |   }
      65 |   const {

      at handleOpenSearchDashboardsStats (src/plugins/telemetry/server/telemetry_collection/get_opensearch_dashboards.ts:62:12)
      at handleLocalStats (src/plugins/telemetry/server/telemetry_collection/get_local_stats.ts:73:30)
      at Object.it (src/plugins/telemetry/server/telemetry_collection/get_local_stats.test.ts:199:22)

  console.warn
    No OpenSearchDashboards stats returned from usage collectors

      60 | ) {
      61 |   if (!response) {
    > 62 |     logger.warn('No OpenSearchDashboards stats returned from usage collectors');
         |            ^
      63 |     return;
      64 |   }
      65 |   const {

      at handleOpenSearchDashboardsStats (src/plugins/telemetry/server/telemetry_collection/get_opensearch_dashboards.ts:62:12)
      at handleLocalStats (src/plugins/telemetry/server/telemetry_collection/get_local_stats.ts:73:30)
      at Object.it (src/plugins/telemetry/server/telemetry_collection/get_local_stats.test.ts:216:22)

Test Suites: 1 passed, 1 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        2.618 s
```

Overall test result:
Screen Shot 2021-06-21 at 9 42 20 PM

 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by tmarkley — DISMISSED** [review]

**Comment by kavilla** [comment]
```
✓ returns expected object with xpack (6 ms)
```

We can probably delete this test. Also I see the warning:
```
  No OpenSearchDashboards stats returned from usage collectors
```
Local to me implies no external dependencies. Should this logging this warning message? Not so much related to this PR but we might have broken basic (free) telemetry that is stored in the engine. If it was still suppose to depend on a third party then should we update the test to expect a warning for now that way we know we correctly implemented as expected in the current code base when the warning is no longer being thrown.

**Review by kavilla — COMMENTED** [review]
Mostly looks good. Just a few comments.

**Comment by ananzh** [comment]
> ```
> ✓ returns expected object with xpack (6 ms)
> ```
> 
> We can probably delete this test. Also I see the warning:
> 
> ```
>   No OpenSearchDashboards stats returned from usage collectors
> ```
> 
> Local to me implies no external dependencies. Should this logging this warning message? Not so much related to this PR but we might have broken basic (free) telemetry that is stored in the engine. If it was still suppose to depend on a third party then should we update the test to expect a warning for now that way we know we correctly implemented as expected in the current code base when the warning is no longer being thrown.

I removed the xpack test. Thanks for pointing it out. For the warning message, I will open an issue later and will do more investigation.

**Comment by ananzh** [comment]
Follow up issue: [#556 ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/556)

**Review by tmarkley — APPROVED** [review]

**Review by kavilla — APPROVED** [review]

**Pull request merged**
