### PR TITLE
Fix readme URL

### PR DESCRIPTION
**Pull request by jkowall**
Fix readme with proper instructions to clone the repo for OpenSearch-Dashboards

### Description
Fixes the URL for this repo
 
### Issues Resolved
No issue opened yet

### CODE REVIEW

**Review by mihirsoni — APPROVED** [review]
Thanks @jkowall  for the change. LGTM !!

**Review by ananzh — APPROVED** [review]

**Review by boktorbb-amzn — DISMISSED** [review]

**Comment by kavilla** [comment]
Looks good just the commit needs a sign-off 

`Use git commit with -s to add 'Signed-of-by: {EMAIL}' on impacted commits`

**Comment by jkowall** [comment]
> Looks good just the commit needs a sign-off
> 
> `Use git commit with -s to add 'Signed-of-by: {EMAIL}' on impacted commits`

Thanks, I hope I did it right. I'm used to CLA not DCO :)

**Comment by kavilla** [comment]
> > Looks good just the commit needs a sign-off
> > `Use git commit with -s to add 'Signed-of-by: {EMAIL}' on impacted commits`
> 
> Thanks, I hope I did it right. I'm used to CLA not DCO :)

Yes perfect! The only thing is it is the bot is checking each commit to be signed off, so for it to pass the automated checks, you should be able to do an interactive rebase to squash the commits so it's one big commit that includes the sign off with the first commit or amend the first commit to also have the sign off message.

The bot basically only check if the commit description has `Signed-off-by: name <email>`.

Let me know if I should clarify anything, and thank you for the help!

**Pull request closed without merging**
