### PR TITLE
Runs GitHub workflow unit tests in band

### LINKED ISSUE #1231: [CI] Unit tests are failing in GitHub Action for all PRs and Pushes
I just noticed that unit tests are not passing in the `Build and Verify` GitHub Action for any current PRs.

Example run for [PR 1229](https://github.com/opensearch-project/OpenSearch-Dashboards/runs/5132841918?check_suite_focus=true) - see `Run echo Unit tests completed unsuccessfully.`

I went back through the [commit history](https://github.com/opensearch-project/OpenSearch-Dashboards/commits/main) and it looks like unit tests have been failing for all commits since https://github.com/opensearch-project/OpenSearch-Dashboards/commit/fc96cc3e685f94285073c919e7fa309fa2e6abb2: [Build and Verify unit tests failing](https://github.com/opensearch-project/OpenSearch-Dashboards/runs/5058947670?check_suite_focus=true)

This might not be the cause, but the unit tests in each of the commits before this passed. The commit before that was https://github.com/opensearch-project/OpenSearch-Dashboards/commit/8777eb3c7068af74de7001d1842138c157a134b5: [Build and Verify unit tests passing](https://github.com/opensearch-project/OpenSearch-Dashboards/runs/4886751966?check_suite_focus=true)

### PR DESCRIPTION
**Pull request by tmarkley**
### Description
* Removes caching from GitHub test workflow to simplify.
* Removes "bad apples" check from GitHub workflow since those tests now pass consistently.
* Runs unit tests in band to reduce execution time from ~90 minutes to ~20 minutes.
* Removes the logic that ignored failing unit tests.
* Adds mocha tests to the workflow.
* Adds ci-specific scripts to simplify the commands.
  * `yarn test:jest:ci` and `yarn test:jest_integration:ci` are now used in the workflow.
 
### Issues Resolved
Resolves #1231
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [x] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by tmarkley** [comment]
@kavilla I'm testing this for `1.x` in my forked repo: https://github.com/tmarkley/OpenSearch-Dashboards/runs/5396077731?check_suite_focus=true

**Comment by kavilla** [comment]
> @kavilla I'm testing this for `1.x` in my forked repo: https://github.com/tmarkley/OpenSearch-Dashboards/runs/5396077731?check_suite_focus=true

Looks like we need the jest upgrade to be able to use the runInBand.

**Comment by tmarkley** [comment]
> > @kavilla I'm testing this for `1.x` in my forked repo: https://github.com/tmarkley/OpenSearch-Dashboards/runs/5396077731?check_suite_focus=true
> 
> Looks like we need the jest upgrade to be able to use the runInBand.

Actually I think the `UnhandledPromiseRejectionWarning` doesn't require the upgrade. I think those tests just aren't handling promises correctly. I made changes to fix this in the jest upgrade PR, I can do that here too: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1301/files#diff-bef055a839e9b33dd53173ea66b575211e8e794624ae65a4c011c78e28ca2858

**Review by kavilla — APPROVED** [review]
Awesome! Thanks!

**Review by ananzh — APPROVED** [review]
LGTM

**Pull request merged**
