### PR TITLE
update re2 for linux, darwin, and windows

### PR DESCRIPTION
**Pull request by ananzh**
### Description
Update re2 to 83

Screen Shot 2022-04-13 at 11 53 52

 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1452
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
    - [ ] `yarn test:jest`
    - [ ] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by tmarkley — COMMENTED** [review]
Looks good to me, but can we add a test (functional test in this case) to cover this specific case that we're looking for?

**Review by kavilla — COMMENTED** [review]
Does this one address the node combability or is it more so bumping to the latest and greatest? If so we should update title of this PR.

**Comment by ananzh** [comment]
> Does this one address the node combability or is it more so bumping to the latest and greatest? If so we should update title of this PR.

This is a bump. But these three also have the incompatibility issue. If run OSD via `yarn start`, then no issue. If build OSD to an artifact, then unzip and run `./bin/opensearch-dashboards`, we would see similar version incompatibility issue. I will modify the title a bit to make it more clearer.

**Comment by ananzh** [comment]
> Looks good to me, but can we add a test (functional test in this case) to cover this specific case that we're looking for?

Will add a unit test. If run OSD via yarn start, then no issue. Issue only happens when run OSD with build artifact. Infra has some tests on this. I will add a unit test for the function I made changes. It will cover two things:
1)PatchNativeModules could download the correct package
2)PatchNativeModules could differentiate .tar.gz and .gz and unzip the package correctly

**Review by kavilla — APPROVED** [review]

**Review by tmarkley — APPROVED** [review]
Looks good! I think we can track the work needed to have BWC tests build an artifact and test for regressions.

**Pull request merged**
