### PR TITLE
[2.14][chore] update release notes

### PR DESCRIPTION
**Pull request by kavilla**
### Description

Updates releases notes. Partially populated with: `yarn release_note:generate`

And gathered the rest. Cleaned up changelog.

### Issues Resolved

related to: #6254

## Changelog
- skip

### CODE REVIEW

**Review by ananzh — APPROVED** [review]

**Review by SuZhou-Joe — APPROVED** [review]

**Comment by ruanyl** [comment]
@kavilla Does `yarn release_note:generate` consume all the changelog fragments? what about those changes which haven't been merged to release branch(`2.x`)?

**Comment by ashwin-pc** [comment]
@kavilla was this script run on 2.14? the flow should be, run it on 2.14 and the forward port those changes to 2.x and main. This way we only remove the changesets that went in 2.14

**Comment by kavilla** [comment]
> @kavilla was this script run on 2.14? the flow should be, run it on 2.14 and the forward port those changes to 2.x and main. This way we only remove the changesets that went in 2.14

yeah. unfortunately that work didn't get backported. added the backport labels here: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5718

**Review by ashwin-pc — APPROVED** [review]

**Comment by kavilla** [comment]
> @kavilla Does `yarn release_note:generate` consume all the changelog fragments? what about those changes which haven't been merged to release branch(`2.x`)?

yeah from my understanding it does. and it depends on the branch it was on. however, since the backports for the release notes stuff still needs to happen it. this was some manual effort so i did my best to verify everything going out to 2.14 is correct

**Review by ananzh — APPROVED** [review]

**Pull request merged**
