### PR TITLE
[Bug] Fix the tooltip display misalignment issue

### PR DESCRIPTION
**Pull request by yubonluo**
### Description
There will be a display issue of content misalignming when showing tooltip on the page.
image
image

Before showing tooltip:
image
After showing tooltip:
image

## Screenshot
After fixing the issue:
image
image
image

## Changelog

 - fix: [Bug] Fix the tooltip display misalignment issue
### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by yubonluo** [comment]
Hi @AMoo-Miki , the PR is related to your this PR（https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7637/files#diff-2d652eece8cdb99548e2f74430a037f961e4525379c683e551118e378f70f0bfR13）. If you have time, please take a look.

**Comment by ruanyl** [comment]
@AMoo-Miki Would be nice if you could take a look at this PR :), the style change was introduced in your previous commit 0a3bcd83b

**Comment by ruanyl** [comment]
The same fix was merged in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8223/files

**Comment by ruanyl** [comment]
Closing this one as fixed in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8223

**Pull request closed without merging**
