### PR TITLE
Removing incorrect CONTRIBUTING.md language and adding updated links

### PR DESCRIPTION
**Pull request by ahopp**
### Description
* Move ToC to top to match the OpenSearch repo
* Minor formatting changes
* Remove reference to pre-alpha state
* Add links for opening issues
* Remove "w00t!!!" from end of file
 
### Issues Resolved
Partially Resolve: Issue #592

### CODE REVIEW

**Review by kavilla — CHANGES_REQUESTED** [review]
Thanks for this. However, the commit needs to be signed https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/CONTRIBUTING.md#developer-certificate-of-origin.

Also, do we think this will be the only 'Update CONTRIBUTING.md' before GA, if so I'm fine with the commit message.

**Comment by ahopp** [comment]
> Thanks for this. However, the commit needs to be signed https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/CONTRIBUTING.md#developer-certificate-of-origin.

Thanks, added. 

> Also, do we think this will be the only 'Update CONTRIBUTING.md' before GA, if so I'm fine with the commit message. But might be nice to reference the git issue in the description for anyone using any tools.

I don't see any major changes but I've updated with a more descriptive title. Thanks!

**Review by boktorbb-amzn — APPROVED** [review]
LGTM

**Review by kavilla — APPROVED** [review]

**Review by mihirsoni — APPROVED** [review]
LGTM !!

**Pull request merged**
