### PR TITLE
create-additional-way-to-create-context-menus

### PR DESCRIPTION
**Pull request by sikhote**
Signed-off-by: David Sinclair <dsincla@rei.com>

### Description
This PR provides a way to create advanced context menus using actions. The current ways of adding groups does not allow deeper nesting and flexibility of items on the initial panel. See included example for how getContextMenuData for an action is utilized to create multiple panels and initial panel items with a single action.
 
### Issues Resolved
This PR supports the feature request https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2904

Eventually, this change will be used in the alerting plugin feature at https://github.com/opensearch-project/alerting-dashboards-plugin/pull/343
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [x] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ashwin-pc** [comment]
@sikhote Thanks for creating the PR. I see that you have linked an issue in the alerting plugin as a reason for opening this PR. Since contributors to OSD do not actively look at that repo and the context in that issue is sparse, can you open an issue in the dashboards repo outlining what the issue is and why this change is necessary in OpenSearch Dashbaords? This helps us understand the change and possibly suggest either existing or better alternatives for your issue.

**Comment by sikhote** [comment]
@ashwin-pc I have added in a feature request and linked in this PR 👍 Please let me know if I can provide additional context

**Comment by kavilla** [comment]
@joshuarrrr, @ashwin-pc, based on some of the discussion here: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2904, do we want to convert this to a draft and have further discussion? I believe we are planning on having public office hours do we want to have this discussion there and record it? Does @opensearch-project/opensearch-ux  need to weigh in on this?

**Comment by ashwin-pc** [comment]
@kavilla let's resolve the conversation on the issue but I don't think we need to convert this to a draft yet.

@sikhote can you update the readme for UI actions to indicate how a plugin should use this API? The example is great, but I want to make sure that all the plugin readmes are up to date too. 

Also coverage seems to be dropping with this PR. Can we add some tests here for this feature?

**Comment by sikhote** [comment]
Closing for now since we have new UX designs.

**Pull request closed without merging**
