### PR TITLE
[osd/std] Add additional recovery from false-positives in handling of long numerals

### LINKED ISSUE #5923: [BUG] JSON parsing issue in Discover since upgrade to v2.12
**Describe the bug**

We upgraded our OpenSearch cluster from version v2.11.1 to v2.12.0. Since then, for one of our index pattern we are not able to retrieve the entries in Discover. We are getting a red toast notification containing "Expected ',' or '}' after property value in JSON at position 3045 (line 1 column 3046)"

image

When looking at the network request in the browser console, we can see that OpenSearch returned the expected response. (I can share the JSON through more restricted channels if needed):

image

I tried also to replay the query in OpenSearch console with a similar behaviour. I have an exception even if the expected data from Opensearch is here:

image

I looked in Opensearch and Opensearch dashboards logs but I did not find any useful message to help troubleshooting this issue.

We are able to make queries log explorer using PPL without issue.

**Expected behavior**

**OpenSearch Version**
2.12.0

**Dashboards Version**
2.12.0

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - OS: WS2022
 - Edge and Chrome

**Additional context**

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description

The parsing of JSON strings with long numerals in @osd/std handled two false-positive scenarios. A new one was discovered where mixed escaped quotes inside a string value resulted in a different exception in browsers that the one already handled for Node.

### Issues Resolved

Fixes #5923

### Check List

- [X] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by ashwin-pc — COMMENTED** [review]
Can we add tests to the corresponding test file for this change? looks like there is already a `json.test.ts` file

**Comment by AMoo-Miki** [comment]
The particular exception is only thrown in browsers. I have created an issue to add functional test to handle the new exception. The existing unit tests cover this case already.

**Review by ashwin-pc — DISMISSED** [review]

**Comment by ashwin-pc** [comment]
@AMoo-Miki can you link that issue here?

**Comment by AMoo-Miki** [comment]
> @AMoo-Miki can you link that issue here?

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5957

**Review by ashwin-pc — APPROVED** [review]

**Review by manasvinibs — APPROVED** [review]

**Review by kavilla — APPROVED** [review]

**Comment by atreyd** [comment]
@AMoo-Miki  Could you please confirm if this is going to be released to 2.12.0 as it's already labeled as backport with 2.12.0 ?

**Comment by AMoo-Miki** [comment]
@atreyd the 2.12 branch is not going to receive a new release as 2.13.0 is just around the corner.

**Pull request merged**
