### PR TITLE
chore(oui): Bump OUI dependency to 1.2.0, remove breadcrumb styling

### PR DESCRIPTION
**Pull request by joshuarrrr**
### Description

Bump OUI version - don't merge until we update from release candidate.

OUI 1.2 includes all necessary breadcrumb styling, so OpenSearch Dashboards customizations are no longer necessary. So we're also essentially reverting the changes from:

- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1954/
- https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2085

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by joshuarrrr** [comment]
Converting to draft until v1.2.0 is released. But we can run the CI against the release candidate.

**Comment by joshuarrrr** [comment]
I opened a separate PR for the Link Checker failure: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4171

**Comment by BSFishy** [comment]
Breadcrumbs probably look wonky with current changes. New breadcrumb styling went into 1.2, so the styling is most likely being applied twice. I outlined how to fix in here: https://github.com/opensearch-project/oui/issues/796#issuecomment-1565064378

**Comment by joshuarrrr** [comment]
Thanks @BSFishy for the instructions - I'll update the PR accordingly.

**Review by ananzh — APPROVED** [review]

**Review by BSFishy — DISMISSED** [review]

**Comment by kavilla** [comment]
Discussed with @KrooshalUX:

Since anywhere project got bumped from 2.8 release. This PR is not required to get in and bake longer.

**Comment by kavilla** [comment]
I noticed the breadcrumb got a little bit blurrer:

From playground: with expanded header turned off:
Screenshot 2023-05-31 at 11 27 17 AM

After, my local with expanded header default value:
Screenshot 2023-05-31 at 11 27 30 AM

**Comment by joshuarrrr** [comment]
Converting to draft - we'll split the OUI changes into different releases so we can pull a clean v1.1.1 with just the icon changes.

**Comment by joshuarrrr** [comment]
This is ready for re-review. Discussed with @AMoo-Miki and we're ok to take some of the breadcrumb concerns in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4457 as a blocker for this in the `2.x` line, but we'll go ahead and merge to `main` so we can further test and validate prior to the 2.10 release.

**Comment by abbyhu2000** [comment]
@joshuarrrr Do you want to solve the conflicts? and also there are some test fails

**Comment by joshuarrrr** [comment]
Closing in favor of https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4621 - no need to bump to OUI 1.2, since we've already bumped `main` to OUI 1.3-rc.

**Pull request closed without merging**
