### PR TITLE
[GHSA-x565-32qp-m3vf] Bump `jimp` to remove phin dependency

### PR DESCRIPTION
**Pull request by AMoo-Miki**
[GHSA-x565-32qp-m3vf] Bump `jimp` to remove phin dependency

`jimp@0.22.0` removed all the code that used phin.

`load-bmfont`, a nested dependency of `jimp` imports `phin` but that is a functionality we don't use as we don't import AngleCode bitmap fonts. With an arbitrarily bump of `phin`, this commit avoids including an offending version in the dev-deps.

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by BionIT — DISMISSED** [review]

**Comment by ananzh** [comment]
jimp 0.22.12 is still using phin 2.9.1 right? 😃

**Comment by virajsanghvi** [comment]
> jimp 0.22.12 is still using phin 2.9.1 right? 😃

Does look like it:
```
└─ jimp@0.22.12
  ├─ @jimp/plugins@0.22.12
   │  ├─ @jimp/plugin-print@0.22.12
   │  │  ├─ load-bmfont@1.4.1
   │  │  │  ├─ phin@2.9.3
```

**Comment by AMoo-Miki** [comment]
`jimp@0.22.0` removed all the code that used `phin` but forgot to remove it from the deps list.

**Review by BionIT — APPROVED** [review]

**Comment by ananzh** [comment]
> a nested dependency of `jimp` imports `phin` but that is a functionality we don't use as we don't import AngleCode bitmap fonts. I will just arbitra

Cool.

**Review by ananzh — APPROVED** [review]

**Pull request merged**
