### PR TITLE
[Multiple DataSource] Codebase maintenance involves updating typos and removing unused imported packages

### PR DESCRIPTION
**Pull request by xinruiba**
### Description

Codebase maintenance involves updating typos and removing unused imported packages.

### Issues Resolved

#6142

## Screenshot

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/139305463/e51240e5-cc54-43b1-8102-393ca5f5f1f4

## Testing the changes

In this video, we test Username and Password auth type by executing following steps:
1. Fill in title, url, auth info into dataSource creation form 
2. Click on "Test connection" and test connection success
3. Click on "Create DataSource" and dataSource creation success
4. Navigate to home page and successfully add sample data into newly created dataSource 
5. Switch to dashboard tab and able to see dashboards successfully

Also test registered auth type locally and works fine. Verified no regressions.

Thanks

### Check List

- [x] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by Flyingliuhub — APPROVED** [review]

**Comment by Flyingliuhub** [comment]
Thanks @xinruiba for fixing this.

**Comment by tianleh** [comment]
Created an issue for improving our link checker for unused imports. https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6249

**Review by tianleh — APPROVED** [review]
Great maintenance work!

**Review by yujin-emma — APPROVED** [review]
LGTM

**Comment by ashwin-pc** [comment]
@xinruiba Thanks for these changes! I'm a little confused about the testing the changes section though. How does the testing the changes section relate to this PR?

**Comment by xinruiba** [comment]
> @xinruiba Thanks for these changes! I'm a little confused about the testing the changes section though. How does the testing the changes section relate to this PR?

Hey @ashwin-pc, thanks to the comments.

I include a full end-to-end testing scenario in the testing section to guard against any potential regressions in MD caused by this name change.

Thanks~

**Review by bandinib-amzn — APPROVED** [review]

**Pull request merged**
