### PR TITLE
Add SVG logo spinner

### PR DESCRIPTION
**Pull request by kgcreative**
Signed-off-by: kgcreative <kvngar@amazon.com>

### Description
Add SVG logo spinner, remove horizontal loader.
#### Before
spinner_before

#### After
spinner_after

Update primary dashboards card to use primary brand color.
#### Before
Screen Shot 2021-05-28 at 3 49 43 PM

#### After
Screen Shot 2021-05-28 at 3 14 13 PM
 

### Issues Resolved
- [x] Fix OpenSearch mark loading spinner line item on #372,
- [x] Change color on Primary "OpenSearch Dashboards" card in the main home landing page on #372

 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by tmarkley** [comment]
Hey Kevin, did you run tests as described in the [README](https://github.com/opensearch-project/OpenSearch-Dashboards#running-tests)?

**Comment by kgcreative** [comment]
> Hey Kevin, did you run tests as described in the [README](https://github.com/opensearch-project/OpenSearch-Dashboards#running-tests)?

All tests pass. Updated one snapshot.

Screen Shot 2021-05-28 at 2 22 27 PM
Screen Shot 2021-05-28 at 2 15 14 PM

**Comment by tmarkley** [comment]
Great! Can you also add some screenshots just for reference?

**Comment by kgcreative** [comment]
> Great! Can you also add some screenshots just for reference?

Done and done! updated original PR with before/after screenshots.

**Review by mihirsoni — DISMISSED** [review]
LGTM !! Thanks for making changes Kevin.

**Comment by kavilla** [comment]
@kgcreative looks great! Thanks!

Ran the functional tests and they all pass just so you know!

For the card do we think we can update it to look better in dark mode or did we just want to leave it since it already was hard to read in the previous view, it looks like this:

Screen Shot 2021-05-30 at 2 09 50 AM

In terms on the actual SVG, do you know if we have a polyfill for `animateTransform` somewhere hidden? Our is there specific documentation that calls out what browsers are supported for OpenSearch Dashboards? I'm not able to find it, as far as I am aware the source of the fork fully supported IE11 from a forum in 2018. But looking at the MDN web docs it looks like it isn't supported in IE11 [[link to doc](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animateTransform)]

Pretty weird but I pulled this down and ran the unit tests (even with the snapshot) and the unit tests keep failing with a date mismatch. So I ran on them on a pipeline and they _passed_, then I ran the main repo's main branch multiple times but that passes for me. It just keeps failing on the unit tests when I try your branch locally, even if I clear my node modules, which is weird. Could someone else give this a run as well locally? If another person's unit tests pass then I'm okay with merging.

Thanks!

**Review by kavilla — COMMENTED** [review]
Even though I left a comment if I want to mark this review with "With Comments" github requires me to enter a comment with the popup while responding to the review 😤.

**Comment by kgcreative** [comment]
Thanks @kavilla - Re: Browser support, as of 7.9, kibana (and EUI) no longer supports IE11. See this matrix: https://www.elastic.co/support/matrix#matrix_browsers - With that in mind, do we need to revisit or create a browser support list for OpenSearch Dshboards 1.0?

Re: Dark mode, let me dig into the CSS a bit and see what I can do - perhaps that might need to be a follow-up issue.

How did you trigger dark mode? Switch via the OS? (I just want to make sure I can reproduce and test visually locally)

**Comment by kgcreative** [comment]
> (even with the snapshot) and the unit tests keep failing with a date mismatch.

The weird thing is the date mismatch was happening on a component I didn't even touch. I'm wondering if something else is going on with that

**Comment by kavilla** [comment]
> With that in mind, do we need to revisit or create a browser support list for OpenSearch Dshboards 1.0?

Thanks! Yeah I think its worth it I think. Perhaps I can create a proposal in the docs repo.

> How did you trigger dark mode? Switch via the OS? (I just want to make sure I can reproduce and test visually locally)

Just go to Stack Management --> Advanced Settings --> Search for Dark Mode

> The weird thing is the date mismatch was happening on a component I didn't even touch. I'm wondering if something else is going on with that

Might be local setup thing. If someone else pulls this down and it passes with your commit then I'm fine with just merging and looking deeper post merge.

**Comment by tmarkley** [comment]
I pulled this PR down, ran `yarn osd clean` and `yarn osd bootstrap`, and then ran unit tests. Those two snapshot tests also failed for me due to a date mismatch.

**Comment by kavilla** [comment]
> I pulled this PR down, ran `yarn osd clean` and `yarn osd bootstrap`, and then ran unit tests. Those two snapshot tests also failed for me due to a date mismatch.

@kgcreative since this is the case, did we want to revert the updating snapshot commit. Also curious how your local setup.

**Comment by kgcreative** [comment]
> > I pulled this PR down, ran `yarn osd clean` and `yarn osd bootstrap`, and then ran unit tests. Those two snapshot tests also failed for me due to a date mismatch.
> 
> @kgcreative since this is the case, did we want to revert the updating snapshot commit. Also curious how your local setup.

Yeah, i can revert the snapshot update commit and see if that helps. For my local setup, I followed the developer guide verbatim. Is there anything I can provide you that might help troubleshoot if it's a local build issue?

**Comment by kgcreative** [comment]
@kavilla - After reverting the snapshot update, i'm getting a date mismatch on my jest test suite (There seems to be a 1 day date mismatch on two VegaVisualization snapshot tests, and I'm seeing the following message along with it: `● VegaVisualizations › VegaVisualization - basics › should show vegalite graph and update on resize (may fail in dev env)` - With that in mind, i'm tempted to leave that one alone on my end.

Screen Shot 2021-06-02 at 3 05 05 PM

**Comment by kgcreative** [comment]
@kavilla - I updated the CSS color reference in the card to use the primary color token so the Dark Mode contrast is a bit better:

Screen Shot 2021-06-02 at 4 34 19 PM

**Comment by kavilla** [comment]
> @kavilla - After reverting the snapshot update, i'm getting a date mismatch on my jest test suite (There seems to be a 1 day date mismatch on two VegaVisualization snapshot tests, and I'm seeing the following message along with it: `● VegaVisualizations › VegaVisualization - basics › should show vegalite graph and update on resize (may fail in dev env)` - With that in mind, i'm tempted to leave that one alone on my end.

Yeah I pull everything down so I can run it to verify, and we can potentially create an issue to figure out if we can recreate on other machines.

**Comment by kavilla** [comment]
> @kavilla - I updated the CSS color reference in the card to use the primary color token so the Dark Mode contrast is a bit better:


Looks really good thank you so much!

**Review by kavilla — APPROVED** [review]
linter, unit tests, integ test, and functional tests all good. looks really slick too! thank you

**Review by tmarkley — APPROVED** [review]

**Pull request merged**
