### PR TITLE
feat: add json worker and language implement in dashboards

### PR DESCRIPTION
**Pull request by SuZhou-Joe**
Signed-off-by: suzhou <suzhou@amazon.com>

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by AMoo-Miki — CHANGES_REQUESTED** [review]
Any reason this is not raised on `main`?

**Comment by SuZhou-Joe** [comment]
> Any reason this is not raised on `main`?

Good point. I thought we can merge to 2.x and add a `backport main` label to merge to main. But anyway I will raise a issue to discuss the reason why we introduce the new json language support first.

**Comment by joshuarrrr** [comment]
Yeah, @SuZhou-Joe all PRs should be raised against `main` first, and then we'll backport as necessary from there: https://github.com/opensearch-project/.github/blob/main/RELEASING.md#branching

But thanks for opening the issue first, that will provide helpful context.

**Comment by SuZhou-Joe** [comment]
#3133

**Pull request closed without merging**
