### PR TITLE
Bumps `percy-agent` to use non-beta version

### PR DESCRIPTION
**Pull request by kavilla**
### Description
Beta version of percy-agent utilized a dependency that had a dependency with a vulnerability.

Bumping to a non-beta version removes that problematic dependency.

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Resolved
n/a
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
    - [ ] `yarn test:jest`
    - [ ] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by kavilla** [comment]
I think it should be safe to backport as this dependency was introduced in 2.0.

**Review by ananzh — APPROVED** [review]

**Comment by joshuarrrr** [comment]
@kavilla This is failing the changelog check - it seems like a changelog update would make sense here.

**Review by abbyhu2000 — APPROVED** [review]

**Comment by ashwin-pc** [comment]
Why is the Vega plugin being updated too? In yarn.lock?

**Review by AMoo-Miki — APPROVED** [review]

**Comment by AMoo-Miki** [comment]
> Why is the Vega plugin being updated too? In yarn.lock?

I think that is my fault!

**Comment by joshuarrrr** [comment]
That was fixed in this PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2432

**Pull request merged**
