### PR TITLE
[Workspace] Only OSD admin can create/update/delete data source

### PR DESCRIPTION
**Pull request by yubonluo**
### Description

Only OSD admin can create/update/delete data source

### Issues Resolved

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6889

## Screenshot

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/71875999/8bc9937c-0558-4e5b-a3db-8c0b37c7588a

## Testing the changes

1. Clone the latest osd/security-dashboard plugin code and run yarn osd bootstrap
2. Modify config/opensearch_dashboards.yml
```yml
opensearchDashboards.dashboardAdmin.groups: ["dashboard_admin"]
opensearchDashboards.dashboardAdmin.users: ["username"]
workspace.enabled: true 
opensearch.username: "username"
opensearch.password: "password" 
opensearch.ssl.verificationMode: none
savedObjects.permission.enabled: true
data_source.enabled: true
```
3. Run yarn start --no-base-path
4. Operate data source.

## Changelog
- feat: [Workspace] Only OSD admin can create/update/delete data source

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by SuZhou-Joe — DISMISSED** [review]

**Comment by BionIT** [comment]
Hi @yubonluo , is this PR targeting 2.15 or 2.16?

**Comment by yubonluo** [comment]
> Hi @yubonluo , is this PR targeting 2.15 or 2.16?

Hi @BionIT this PR target 2.15.

**Comment by BionIT** [comment]
@ruanyl @yubonluo I saw the tag was changed to 2.16, just want to double check if it is correct

**Comment by yubonluo** [comment]
> @ruanyl @yubonluo I saw the tag was changed to 2.16, just want to double check if it is correct
Hi @BionIT due to the need to confirm some additional requirements, the PR will be released on 2.16.

**Review by raintygao — APPROVED** [review]

**Pull request closed without merging**
