### PR TITLE
Update README.md with the nvm, yarn setup steps

### PR DESCRIPTION
**Pull request by vchrombie**
### Description

This commit adds the installation steps of yarn and npm in the README.md file before the setup.
 
### Issues Resolved

Closes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/270
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

---

@seraphjiang, do you have any suggestions?

### CODE REVIEW

**Review by ananzh — APPROVED** [review]

**Review by kavilla — COMMENTED** [review]
Awesome! Thank you so much!

**Review by kavilla — DISMISSED** [review]

**Review by mihirsoni — DISMISSED** [review]
LGTM !! Thank you.

**Comment by vchrombie** [comment]
Thanks for the reviews. Let me know if I need to rebase the branch. I can do it.

**Comment by vchrombie** [comment]
Oops, I thought of rebasing the branch so that it is easy to merge but it seems all the approved reviews are reverted. :slightly_frowning_face: 
I'm sorry for the inconvenience. It would be great if you can review it again.

**Review by boktorbb-amzn — APPROVED** [review]
No problem. Looks good

**Review by kavilla — APPROVED** [review]

**Pull request merged**
