### PR TITLE
Update README.md

### LINKED ISSUE #297: [BUG]Readme OpenSearch Github Repo Link
**Describe the bug**

The READMe says to clone OpenSearch as a pre-requisite to run OpenSearch Dashboards but the link for OpenSearch Engine is of OpenSearch Dashboards. Can we rectify the README?

### PR DESCRIPTION
**Pull request by TheAlgo**
### Description
Update OpenSearch Github repository link.
 
### Issues Resolved
#297

### CODE REVIEW

**Review by kavilla — COMMENTED** [review]
LGTM. Thank you! However can you sign off on your commit, for example `git commit -s`.

**Review by kavilla — APPROVED** [review]
Thank you!

**Comment by TheAlgo** [comment]
@kavilla Can you add one more reviewer to the PR? Thanks.

**Review by seanneumann — APPROVED** [review]
LGTM. Thank you.

**Pull request merged**
