### PR TITLE
Rename kui-spaced class names

### LINKED ISSUE #3386: Remove KUI usage in `visualizations`

### PR DESCRIPTION
**Pull request by sayuree**
### Description

Replaced kui-spaced class names 
### Issues Resolved
closes #3386 

### Check List

- [ ] All tests pass
  - [x] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by joshuarrrr — CHANGES_REQUESTED** [review]
@sayuree This is a good start, but there are a couple of things we need to do first.

For any UI changes, it's important to know where (and under what circumstances the component in question is rendered). So the first step here is to figure out what you need to to to actually see the `<div className="visDisabledLabVisualization">` component rendered, so that you can effectively validate the changes and take screenshots.

Once you do that, I think it's likely we can refactor that component in a way to remove these classes altogether, and replace the bare `<div>` elements with the correct components from https://oui.opensearch.org/1.0/#/.

For example, The first div with the `kuiIcon` class will likely become an <OuiIcon> component: https://oui.opensearch.org/1.0/#/display/icons

**Comment by joshuarrrr** [comment]
@sayuree Just checking in to see if you're still able to make some of the changes requested.

**Comment by sayuree** [comment]
> @sayuree Just checking in to see if you're still able to make some of the changes requested.

@joshuarrrr I was busy with adding changes to other PRs, currently, working on this issue.

**Comment by BSFishy** [comment]
If you need help navigating OUI, feel free to ping me :)

**Comment by sayuree** [comment]
> If you need help navigating OUI, feel free to ping me :)
@joshuarrrr I have some issues with navigating a page where these elements are being used/rendered. Since it is not located in `components` folder, but rather in `embeddable` I was not able to find an exact place it is being used to capture and replace with OUI library items. I tried using logging to detect, I have looked through all possible pages. Can you please give some guidance on this issue?

**Comment by joshuarrrr** [comment]
> @joshuarrrr I have some issues with navigating a page where these elements are being used/rendered. Since it is not located in components folder, but rather in embeddable I was not able to find an exact place it is being used to capture and replace with OUI library items. I tried using logging to detect, I have looked through all possible pages. Can you please give some guidance on this issue?

@sayuree See this video - you'll need to navigate to a dashboard that's using a visualization type that's marked as experimental (after changing the advanced settings to disable experimental visualizations):

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/1679762/92be4683-299d-42a7-a5a4-687333211f87

But before you do any further mitigation, let's get some improved guidance from UX.

@KrooshalUX Can we get an updated design for this placeholder component, with a list of components to use? I'm leaning toward just https://oui.opensearch.org/1.0/#/display/text with paragraph tags 🤷

**Comment by KrooshalUX** [comment]
@joshuarrrr 

- [ ] This placeholder text and icon should be replaced with `OuiEmptyPrompt`https://oui.opensearch.org/1.2/#/display/empty-prompt
- [ ] The wording should be updated to remove "lab" and "lab mode" as those are Kibana terms. So it would read "[vispanel title] is an experimental visualization. Please turn on experimental visualization mode in [Advanced Settings](https://playground.opensearch.org/app/management/opensearch-dashboards/settings) to see experimental visualizations"
- [ ] Ideally we would also link to Advanced Settings within the message as well - ideally after #4329 is completed, Visualizations panel will have a pathway we can deep link to.

**Comment by joshuarrrr** [comment]
@sayuree I'm going to mark this as a draft for now until you have time to revisit it.

**Comment by yvonnewangg** [comment]
Hi, can I take this one?

**Comment by ananzh** [comment]
@sayuree Due to an extended period without updates, we're going to close this issue for now. We appreciate your contribution and understand that priorities and availability can change. Please feel free to reopen this issue when you have the opportunity to revisit it. Thank you for your understanding.

**Pull request closed without merging**
