### PR TITLE
Add CODE_OF_CONDUCT markdown file to fix broken link in README

### LINKED ISSUE #676: [BUG] README Section has broken link in Code of Conduct "Amazon Open Source Code of Conduct"
In the README .md > Code of Conduct > "Amazon Open Source Code of Conduct" link is broken. I believe we can use same CODE of CONDUCT for opensearch (https://github.com/opensearch-project/OpenSearch/blob/main/CODE_OF_CONDUCT.md).

### PR DESCRIPTION
**Pull request by sagar-rout**
Signed-off-by: Sagar Rout <sagar@sagarrout.com>

### Description
Fixes broken Code of Conduct markdown link in README.md
 
### Issues Resolved
Resolves #676 
 
### Check List
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by tmarkley — APPROVED** [review]
Thanks for this change Sagar!

**Review by kavilla — APPROVED** [review]
LGTM thank you!

**Comment by kavilla** [comment]
NIT: The commit message doesn't have a detailed description but I think the message is descriptive enough. Perhaps we can take 676 out of the message and link the issue in the git description so it's a little bit cleaner?

**Comment by sagar-rout** [comment]
> NIT: The commit message doesn't have a detailed description but I think the message is descriptive enough. Perhaps we can take 676 out of the message and link the issue in the git description so it's a little bit cleaner?

yes, you are right. I fixed the git commit message. Could you please have a look when you have sometime ? Thanks.

**Review by kavilla — APPROVED** [review]

**Review by tmarkley — APPROVED** [review]
LGTM, thanks!

**Comment by sagar-rout** [comment]
Hi, I don’t think I can merge the changes into main branch. Can someone please merge this PR who has write access ? Thanks

**Comment by kavilla** [comment]
Would you be able to backport to this into the `1.x` branch.

**Pull request merged**
