### PR TITLE
 Update locales.js for support pl language

### PR DESCRIPTION
**Pull request by fcientymeh**
### Description

Opensearch-dashboard uses two kinds of translating engines:

\<FormattedMessage> and  i18n.translate.

i18n.translate works from scratch, but  \<FormattedMessage> needs to have localization country shortcut in locales.js file. If not - opensearch-dashboards must be build from source with newly added new localization country. This is very problematic.
I didn't found other solution.

Ultimately, adding support for a new language should not force compilation of the product

### Check List

- [x] All tests pass
  - [x] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ashwin-pc** [comment]
Hi @fcientymeh Can you add details to the PR description's sections so that its clear what this change is addressing?

**Comment by fcientymeh** [comment]
@ashwin-pc   - thank you for your feedback. Generally speaking - we needs (I hope many others too) to have localized opensearch-dashboards. The problem is that adding translation support for \<FormattedMessage> requires recompiling the product,, if theres is no locale defined in locales.js file for some new country. 

I think this could be separated as a new issue.

**Comment by kavilla** [comment]
Thanks for doing this. Yes this is a known issue. It requires the update this for functional purposes along with the translation.

Looks good to me as much as I can verify.

**Review by kavilla — APPROVED** [review]

**Comment by ashwin-pc** [comment]
@fcientymeh looks like you want to add a new locale for the app. have you taken a look at the i18n plugin? https://github.com/opensearch-project/dashboards-i18n/blob/main/DEVELOPER_GUIDE.md

also here is a guide about i18n https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/packages/osd-i18n/README.md.

**Comment by ashwin-pc** [comment]
@kavilla im a little confused, do we have an open issue for this?

**Comment by fcientymeh** [comment]
Hello. 
Yes, we use a plugin i18n for translating  OpenSearch-Dashboards. As I'd said - it works great, but when we using i18n.translate func, not for<FormattedMessage>.
I will look for solution for this. One of my the idea is (at this time)  to use default en translation, if there is not proper language defined in locales.js, but I don't know , if it is possible.

ps.
I've started some work on translation Opensearch Dashboards (still have problem with DCO, but it was my fault, so PR hangs):
https://github.com/opensearch-project/dashboards-notifications/pull/180

**Comment by ashwin-pc** [comment]
Ah nice. Sorry we took so long. I think that this can go in for now to unblock you. @ananzh can you look into this later to see why we need to hardcode these?

**Review by ashwin-pc — APPROVED** [review]

**Comment by kavilla** [comment]
@fcientymeh I think we can squash all the commits on merged and make

```
Signed-off-by: Andrzej M. <karkoman@gmail.com>
```
The signed off if correct.

**Comment by fcientymeh** [comment]
I had problem with DCO because of using space and dot(.) in username. See below pls:
image



I fixed this already by changing username simply to AndrzejM

**Comment by BionIT** [comment]
Hi @ashwin-pc and @kavilla , should we mark this PR for 2.15?

**Pull request merged**
