### PR TITLE
[Manual Backport 2.x][CCI] Fix EUI/OUI type errors (#3798)

### PR DESCRIPTION
**Pull request by ashwin-pc**
cherrypick 0e25f2e6e0e906e2474e513a6784be9ac63b26da from #3798

### CODE REVIEW

**Comment by ashwin-pc** [comment]
Cypress tests will pass once the Data explorer changes are emerged to 2.x

**Review by AMoo-Miki — APPROVED** [review]

**Comment by joshuarrrr** [comment]
https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/804/ is merged now

**Comment by joshuarrrr** [comment]
@ashwin-pc This has conflicts now...

**Review by manasvinibs — DISMISSED** [review]

**Comment by kavilla** [comment]
@ashwin-pc, lemme know if you need help handling some of these conflicts.

**Review by joshuarrrr — APPROVED** [review]

**Pull request merged**
