### PR TITLE
[Backport 1.x] Add Windows CI to the GitHub workflow

### PR DESCRIPTION
**Pull request by manasvinibs**
Signed-off-by: Manasvini B Suryanarayana <manasvis@amazon.com>

### Description
Manual backport of the https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2966
 
### Issues Resolved
Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2451
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by AMoo-Miki** [comment]
Please see https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3128#pullrequestreview-1260927522

**Comment by kavilla** [comment]
we want to backport the renaming of the file?

**Comment by joshuarrrr** [comment]
> we want to backport the renaming of the file?

Are you suggesting that we also want the rename backported? If so, I agree that the answer is "yes". Having the workflow files have the same name would make other backport changes easier.

**Comment by manasvinibs** [comment]
> we want to backport the renaming of the file?

Here it is https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3293

**Review by AMoo-Miki — DISMISSED** [review]

**Review by joshuarrrr — DISMISSED** [review]

**Review by joshuarrrr — APPROVED** [review]

**Review by AMoo-Miki — APPROVED** [review]

**Review by joshuarrrr — APPROVED** [review]

**Pull request merged**
