### PR TITLE
[Build][Tests] handle painless scripts update

### PR DESCRIPTION
**Pull request by kavilla**
### Description
Sample data and functional tests were utilizing deprecated
methods for painless scripts.

However these deprecated methods were removed in:
https://github.com/opensearch-project/OpenSearch/pull/3346

This is to ensure sample data and ftr tests work but end users
saved objects might contain painless scripts that we might not
be able to address. So we should research if this it is
possible to help mitigate this.

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Related
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1600

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by tmarkley — APPROVED** [review]
LGTM!

How did you find these instances of the deprecated methods? Was there a particular error? Did you have to search across the code base for each one?

**Review by reta — APPROVED** [review]

**Comment by reta** [comment]
Thanks @kavilla !

**Comment by kavilla** [comment]
> LGTM!
> 
> How did you find these instances of the deprecated methods? Was there a particular error? Did you have to search across the code base for each one?

Pretty much. But for the sample data, pretty straight forward. Just checked the index patterns for the scripted fields. Now I wonder how can we best deliver this information to 3.0 users when they upgrade.

**Comment by reta** [comment]
> > LGTM!
> > How did you find these instances of the deprecated methods? Was there a particular error? Did you have to search across the code base for each one?
> 
> Pretty much. But for the sample data, pretty straight forward. Just checked the index patterns for the scripted fields. Now I wonder how can we best deliver this information to 3.0 users when they upgrade.

Release Notes with noting the breaking changes?

**Review by ananzh — APPROVED** [review]
LGTM

what errors would we see? for example, during oncall, how can we know it is related to getMillis() issue?

**Comment by kavilla** [comment]
> LGTM
> 
> what errors would we see? for example, during oncall, how can we know it is related to getMillis() issue?

Right now it comes back as a general `search_phase` exception. It's easier to see on the Discover page because the popup complains with it not knowing what this function is. If you pull down main currently, run `yarn opensearch snapshot` and add sample flights data and navigate to the Discover page you will see the exception.

But given that is just sample data and anyone can create their scripted fields to be used by visualizations it might not be complete transparent for us in 3.0 right away. It might require telling end users to check their index patterns and verifying their scripts are up to date.

**Comment by kavilla** [comment]
> > > LGTM!
> > > How did you find these instances of the deprecated methods? Was there a particular error? Did you have to search across the code base for each one?
> > 
> > 
> > Pretty much. But for the sample data, pretty straight forward. Just checked the index patterns for the scripted fields. Now I wonder how can we best deliver this information to 3.0 users when they upgrade.
> 
> Release Notes with noting the breaking changes?

True that will be great on the OpenSearch side but for OpenSearch Dashboards it wouldn't be breaking change from us but it would appear that it's something breaking on our side. Plus we can probably do something in application to warn people ahead of time.

Will tag UI/UX with to see if they have an opinions.

**Comment by joshuarrrr** [comment]
A migration guide would be super useful - given that the scripts here were likely more basic than what many other folks have, we'd probably want to identify a more complex/realistic painless script to use as the example. If we had a migration guide on the docs site, it would also be easy to link to from some sort of helpful UI error message.

**Pull request merged**
