### PR TITLE
Bump `agentkeepalive` to v4.5.0

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description

Bump `agentkeepalive` to v4.5.0 to solve a problem preventing the use `https://ip` in `opensearch.hosts`.

The `elasticsearch` client uses a flaws version that incorrectly sets `servername` on a `tls` connection using IPs.

Expect a deprecation warning while bootstrapping:
```
[agentkeepalive:deprecated] options.freeSocketKeepAliveTimeout is deprecated, please use options.freeSocketTimeout instead
```

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by kavilla** [comment]
should we consider this a breaking change?

**Comment by AMoo-Miki** [comment]
> should we consider this a breaking change?

The functionality has been broken for as long as `elasticsearch` client has used `agentkeepalive@^3.0.0` - so since `elasticsearch@14.2.0`, first used in `kibana@7.0.0`. This is a fix to that.

**Review by ananzh — DISMISSED** [review]

**Comment by ananzh** [comment]
@AMoo-Miki should we also backport to 1.3?

**Comment by AMoo-Miki** [comment]
> @AMoo-Miki should we also backport to 1.3?

1.3 receiving only security patches and bug fixes, I don't think this needs to go there.

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Comment by joshuarrrr** [comment]
@AMoo-Miki I _think_ the link checker failure is spurious, but could you check?

**Comment by joshuarrrr** [comment]
whitesource issue tracked separately in https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5178

**Comment by CarterPape** [comment]
Is the deprecation warning expected to be permanent?

**Comment by qubec26** [comment]
Is the deprecation warning expected to be permanent?

**Pull request merged**
