### PR TITLE
Feat (home): Add new theme dashboard screenshots

### PR DESCRIPTION
**Pull request by joshuarrrr**
### Description

- Add `next` theme variant screenshots of sample dashboards with `_new` suffix
- Add chromed screenshots of flights dashboard to use as the images in the new theme modal and replace placeholders
- Tweak gutter size in new theme modal
- Add `hasNewThemeImages` optional boolean to sample dataset registry interface
- Update sample data cards image path logic to fetch themed images if available via `hasNewThemeImages` prop

The approach to the sample dataset registry was a bit lazy; but I didn't want to introduce any more props than necessary, while also not breaking any other sample dataset registrations that won't have themed variants.

### Issues Resolved

Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4673
Completes TODOs from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4715

## Screenshot

Screenshot 2023-09-01 at 17-28-22 Home - OpenSearch Dashboards
Screenshot 2023-09-01 at 17-29-11 Home - OpenSearch Dashboards
Screenshot 2023-09-01 at 17-29-37 Home - OpenSearch Dashboards
Screenshot 2023-09-01 at 17-30-04 Home - OpenSearch Dashboards
Screenshot 2023-09-01 at 17-31-17 Home - OpenSearch Dashboards
Screenshot 2023-09-01 at 17-31-39 Home - OpenSearch Dashboards

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by kavilla — APPROVED** [review]
Nice. Thanks!

**Comment by joshuarrrr** [comment]
> Josh thanks for this. I minified the updated images.

Can you document the procedure for doing this?

**Comment by AMoo-Miki** [comment]
> > Josh thanks for this. I minified the updated images.
> 
> Can you document the procedure for doing this?

I usually use `pngquant` with `pngcrush`. However, these were made with [TingPNG](https://tinypng.com/).

**Review by AMoo-Miki — APPROVED** [review]

**Comment by kgcreative** [comment]
Looks so good!

**Review by kavilla — APPROVED** [review]

**Pull request merged**
