### PR TITLE
[VisBuilder] Change VisBuilder from experimental to production

### PR DESCRIPTION
**Pull request by ananzh**
### Description
* no experiment icon on saved visbuilder
Screenshot 2024-04-12 at 4 03 11 PM

* no experiment banner
Screenshot 2024-04-12 at 4 03 47 PM

* no experiment icon on visbuilder in vis panel
Screenshot 2024-04-12 at 4 04 01 PM

* when turn on `visualize:enableLabs`, visbuilder can still be loaded in dashboard
Screenshot 2024-04-12 at 4 04 23 PM

### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6435

## Changelog
- feat: [VisBuilder] Change VisBuilder from experimental to production

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ananzh** [comment]
cypress/integration/core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/experimental.spec.js would need to be removed after merge. Right now this cypress test is expected to fail.

**Review by ashwin-pc — DISMISSED** [review]
LGTM

**Comment by kavilla** [comment]
@ananzh should we add the 2.15 label or did we want to not commit to a specific release incase anything pops up from 2.14 to 2.15?

**Review by ruanyl — DISMISSED** [review]

**Comment by BionIT** [comment]
@ananzh Could you resolve the conflict?

**Review by ashwin-pc — APPROVED** [review]

**Review by virajsanghvi — APPROVED** [review]

**Review by ruanyl — APPROVED** [review]

**Comment by ruanyl** [comment]
Seems DCO check failed.

**Pull request merged**
