### PR TITLE
[Manual][Backport 2.x] add multi selectable data source component

### PR DESCRIPTION
**Pull request by BionIT**
### Description
This manually backports 6aa59b246a9b835387eba7a3895b58b9fc7ac74e

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by zhongnansu — APPROVED** [review]
lgtm

**Review by xinruiba — APPROVED** [review]

**Comment by zhongnansu** [comment]
@BionIT actually saw one test CI is failing, others are running,  please also take a look and see if it's related to the change of this PR.

**Comment by xinruiba** [comment]
> @BionIT actually saw one test CI is failing, others are running, please also take a look and see if it's related to the change of this PR.

+1, let's wait for all CI testing success. Thanks

**Comment by bandinib-amzn** [comment]
Re-run failed job.

**Comment by BionIT** [comment]
> > @BionIT actually saw one test CI is failing, others are running, please also take a look and see if it's related to the change of this PR.
> 
> +1, let's wait for all CI testing success. Thanks

Thanks @zhongnansu  @xinruiba @bandinib-amzn ! Yeah, it's due to another backport PR which is not merged, just merged that one and will wait until all tests pass

**Pull request merged**
