### PR TITLE
Fix visAugmenter forming empty key-value pairs in its calls to the SavedObject API

### LINKED ISSUE #5187: [BUG] Dashboards 2.9 is sending request with extra & for request
Dashboards 2.9 is sending request with extra & for this request, e.g.  

GET /_dashboards/api/saved_objects/_find?default_search_operator=AND&&has_reference=%7B%22type%22%3A%22visualization%22%2C%22id%22%3A%22334084f0-52fd-11e8-a160-89cc2ad9e8e2%22%7D&page=1&per_page=100```&&t```ype=augment-vis

this will break functionality of downstream service rely on standard query string pattern, which single question mark is used as a separator

https://en.wikipedia.org/wiki/Query_string

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description

`visAugmenter` sent empty arrays to `SavedObjectsClient.find()` which were converted to zero-length parameters in the query-string of the request being sent to the SavedObject API.

I will be following up this PR with another one for general hardening of `SavedObjectsClient.find`. 

Fixes #5187

### Check List

- [X] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by joshuarrrr — DISMISSED** [review]
LGTM

**Review by seanneumann — DISMISSED** [review]
👍

**Comment by joshuarrrr** [comment]
@AMoo-Miki Why would we backport to 2.9?

**Comment by ohltyler** [comment]
@AMoo-Miki thanks a lot for finding this issue. It looks like a few UTs need to be updated from empty arrs to undefined.

**Comment by AMoo-Miki** [comment]
> @AMoo-Miki Why would we backport to 2.9?

I will explain it offline to you :D

**Comment by AMoo-Miki** [comment]
> @AMoo-Miki thanks a lot for finding this issue. It looks like a few UTs need to be updated from empty arrs to undefined.

Right. Will handle it.

**Review by kavilla — DISMISSED** [review]

**Review by kavilla — APPROVED** [review]

**Review by abbyhu2000 — APPROVED** [review]

**Pull request merged**
