### PR TITLE
fix (startup): fix font theme key

### PR DESCRIPTION
**Pull request by joshuarrrr**
### Description

Fixes `undefined` value in font family for next theme. The key should be `v8` not `default`. Skipping changelog entry as this is a follow-up fix to https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5652, which hasn't yet been released.

## Screenshot

Before:

Screenshot 2024-05-02 at 10-48-44 Home - OpenSearch Dashboards

After:
Screenshot 2024-05-02 at 10-36-29 Home - OpenSearch Dashboards

## Testing the changes

Validated locally. Reviewers can test by inspecting the generated `/startup.js` file when using the next theme and validating that the font-family starts with `Source Sans 3`, not `undefined`.

## Changelog

- skip

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by kavilla — APPROVED** [review]

**Comment by seraphjiang** [comment]
we might need to figure out how to test effectively and ensure a way to automate regression test. considering it is blocking 2.14, could we merge and test manually?

**Comment by seraphjiang** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6704

**Review by seraphjiang — APPROVED** [review]

**Comment by BionIT** [comment]
Want to understand better, is this a bug fix? If yes, what was the issue and how do we know it is fixed?

**Comment by BionIT** [comment]
Approve to unblock release, but we need more details

**Review by BionIT — APPROVED** [review]

**Comment by kavilla** [comment]
> we might need to figure out how to test effectively and ensure a way to automate regression test. considering it is blocking 2.14, could we merge and test manually?

Yeah we felt the same:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4465

However, haven't had the bandwidth.

**Review by Flyingliuhub — APPROVED** [review]

**Pull request merged**
