### PR TITLE
Add border for header navigation on right

### LINKED ISSUE #5449: [BUG] HeaderNavControl missing border at right
**Describe the bug**

When register more than one navControl on header, the border is missing between them.

image

**To Reproduce**

**Expected behavior**

Border should displayed 
image

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

### PR DESCRIPTION
**Pull request by Hailong-am**
### Description

Add border for header navigation control on right

### Issues Resolved
#5449

## Screenshot

image

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by AMoo-Miki — DISMISSED** [review]
Thanks. I would however wait to hear from @kgcreative before merging this.

**Comment by kgcreative** [comment]
> Thanks. I would however wait to hear from @kgcreative before merging this.

Make it so!

**Comment by kgcreative** [comment]
Also nitpick, but when adding this item, it should to all the way to the right

**Comment by Hailong-am** [comment]
> Also nitpick, but when adding this item, it should to all the way to the right

Current Nav don't support register Nav to farthest right, will have another issue #5458 to track

**Review by joshuarrrr — APPROVED** [review]
Thanks for this fix!

**Review by AMoo-Miki — APPROVED** [review]

**Pull request merged**
