### PR TITLE
[Version] Increment to 2.0

### PR DESCRIPTION
**Pull request by kavilla**
### Description
Version bump from 1.2 to 2.0

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Resolved
n/a
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [x] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by kavilla** [comment]
Screen Shot 2021-11-22 at 10 55 01 AM

**Comment by kavilla** [comment]
We don't have to go this route of bumping `main` to `2.0.0` but at least this starts the conversation. OpenSearch is on `2.0.0` on `main` and `1.3.0` on `1.x`, which I was thinking we can mimic so that we keep `main` and `1.x` latest and greatest.

**Review by tmarkley — APPROVED** [review]
I think this is the right move considering the upcoming Node.js upgrade that we'll be pushing to `main`. Thanks!

**Review by boktorbb-amzn — APPROVED** [review]
Looks good

**Pull request merged**
