### PR TITLE
[MD][IP] Update configure data source per UX input

### PR DESCRIPTION
**Pull request by kristenTian**
Signed-off-by: Kristen Tian <tyarong@amazon.com>

### Description
Update configure data source per UX input
 
### Issues Resolved
image

image

 
### Check List

- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by zengyan-amazon — APPROVED** [review]

**Comment by noCharger** [comment]
Found a issue for index pattern management creation flow. Please take a look, thanks! https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2048

**Comment by kristenTian** [comment]
> Found a issue for index pattern management creation flow. Please take a look, thanks! #2048

What's the reason you linked that issue to data source related changes? 

They are from legacy code base which can be track separately.

**Comment by noCharger** [comment]
> Found a issue for index pattern management creation flow. Please take a look, thanks! #2048



> > Found a issue for index pattern management creation flow. Please take a look, thanks! #2048
> 
> What's the reason you linked that issue to data source related changes?
> 
> They are from legacy code base which can be track separately.

What do you mean by legacy code base? It's the pulled from the current feature branch.

**Comment by noCharger** [comment]
> > Found a issue for index pattern management creation flow. Please take a look, thanks! #2048
> 
> What's the reason you linked that issue to data source related changes?
> 
> They are from legacy code base which can be track separately.

Verified it's existing issue on main branch as well. Removed the multi data source label.

**Pull request merged**
