### PR TITLE
Upgrade chromedriver to fix bootstrapping errors

### PR DESCRIPTION
**Pull request by derek-ho**
### Description

Bumps chromdriver dependency causing errors during bootstrap due to URL change.

### Issues Resolved

Potentially #5925 

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by derek-ho** [comment]
@AMoo-Miki @kavilla can you folks take a look and leave any thoughts? I don't know how we are determining the URL of chromedriver internally, so not sure if this will fix the whole issue.

**Comment by derek-ho** [comment]
I found this link: https://googlechromelabs.github.io/chrome-for-testing/#stable, looks like the URL changed

**Comment by kavilla** [comment]
Thanks @derek-ho,

Sometimes we have issues with Chrome not be available on GitHub envs. So we have a script

```
node scripts/upgrade_chromedriver.js
```

and then run `yarn osd bootstrap`. But doesn't hurt to bump it up if the GitHub env is available. Thank you!

**Review by kavilla — APPROVED** [review]

**Comment by derek-ho** [comment]
> Thanks @derek-ho,
> 
> Sometimes we have issues with Chrome not be available on GitHub envs. So we have a script
> 
> ```
> node scripts/upgrade_chromedriver.js
> ```
> 
> and then run `yarn osd bootstrap`. But doesn't hurt to bump it up if the GitHub env is available. Thank you for doing this, will wait for the CI to finish.

I see. I took a quick look at the script, and it doesn't seem like it is hard coding any links. The fundamental issue seems to be chromedriver moved locations from
`https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/XXX`
to:
`https://storage.googleapis.com/chrome-for-testing-public/XXX`

So would this PR actually fix anything? Where is the `https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/XXX ` coming from?

**Review by bandinib-amzn — APPROVED** [review]

**Comment by BionIT** [comment]
> > Thanks @derek-ho,
> > Sometimes we have issues with Chrome not be available on GitHub envs. So we have a script
> > ```
> > node scripts/upgrade_chromedriver.js
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then run `yarn osd bootstrap`. But doesn't hurt to bump it up if the GitHub env is available. Thank you for doing this, will wait for the CI to finish.
> 
> I see. I took a quick look at the script, and it doesn't seem like it is hard coding any links. The fundamental issue seems to be chromedriver moved locations from `https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/XXX` to: `https://storage.googleapis.com/chrome-for-testing-public/XXX`
> 
> So would this PR actually fix anything? Where is the `https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/XXX ` coming from?

Looks like the upgrade chromedriver only runs for a few tasks but not `build and verify` which might be why the tests pass but build and verify fails https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.github/workflows/build_and_test_workflow.yml#L32C5-L32C9

**Comment by kavilla** [comment]
Manual backport https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5928

**Comment by AMoo-Miki** [comment]
This should not have been backported since it breaks Node 14.

**Pull request merged**
