### PR TITLE
Support for TLS v1.3

### LINKED ISSUE #838: Support for tls v1.3 in opensearch-dashboards
Description: 

(link to [original query]( https://discuss.opendistrocommunity.dev/t/support-for-tls-v1-3-in-opensearch-dashboards/6624/2))
Opensearch supports TLS v1.3 for both http and transport-layer communication. 
(Ref - https://github.com/opensearch-project/OpenSearch/blob/0ba0e7cc26060f964fcbf6ee45bae53b3a9941d0/libs/ssl-config/src/main/java/org/opensearch/common/ssl/SslConfiguration.java#L69)

However, **opensearch-dashboards also does not support tls 1.3 yet.** (Ref - https://github.com/opensearch-project/OpenSearch-Dashboards/blob/9a2d3e6918760c4bba8b44b9e8dfcd14e459a916/src/core/server/http/ssl_config.ts#L72)

Issue: As a result, if opensearch runs with tls 1.3 enabled for http communication, opensearch-dashboard would fail to connect to opensearch and wont start.
Note - In kibana, TLS 1.3 is supported only from 7.11.0 and not available in older versions i.e. 7.10 from which opensearch-dashboards is derived.

This feature is to request support for tls 1.3.

### PR DESCRIPTION
**Pull request by kajetan-nobel**
### Description

Adds support to TLS v1.3

### Issues Resolved

closes #838 

## Testing the changes

1. Create a certificate that fulfills the requirements 
2. Fill needed configuration in `config/opensearch_dashboards.yml`
```yml
opensearch.ssl.verificationMode: full
server.ssl.enabled: true
server.ssl.certificate: <path/to/client.pem>
server.ssl.key: <path/to/client-key.pem>
server.ssl.certificateAuthorities: <path/to/root-ca.pem>
opensearch.ssl.certificateAuthorities: <path/to/root-ca.pem>
```
3. Run dashboards

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by ananzh — APPROVED** [review]

**Comment by kajetan-nobel** [comment]
Can any other maintainers of this repository review this PR for me please? Thank you.

**Comment by davidlago** [comment]
@seanneumann could you please help us get this one reviewed? thanks!

**Comment by kajetan-nobel** [comment]
A recent main has been merged, a review will be really appreciated 😅 . Thanks!

**Comment by AMoo-Miki** [comment]
Prior to the change:
```
 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    offered (OK)
 TLS 1.3    offered (OK): final
 NPN/SPDY   not offered
 ALPN/HTTP2 http/1.1 (offered)
```

With this PR and after including `server.ssl.supportedProtocols: ["TLSv1.3"]`
```
 SSLv2      not offered (OK)
 SSLv3      not offered (OK)
 TLS 1      not offered
 TLS 1.1    not offered
 TLS 1.2    not offered
 TLS 1.3    offered (OK): final
 NPN/SPDY   not offered
 ALPN/HTTP2 not offered
```

**Pull request merged**
