### PR TITLE
Upgrade Cypress to v12

### PR DESCRIPTION
**Pull request by d-rowe**
### Description
This is to merge the cypress v12 upgrade work into main.

## Changelog
- skip

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by LDrago27 — APPROVED** [review]

**Review by ananzh — APPROVED** [review]

**Comment by skumawat2025** [comment]
Hi @d-buckner this change will cause build failures for plugins due to cypress version conflicts. Do we have any recommendation for plugin for cypress version upgrade?

**Comment by d-buckner** [comment]
Hi @skumawat2025, there's detail migration instructions for the v12 cypress upgrade [here](https://docs.cypress.io/app/references/migration-guide#Migrating-to-Cypress-120).

The idea here is to ensure our platform has a unified version of cypress to avoid compatibility issues. If you share an example build failure I'm happy to provide more detailed recommendations for your use-case.

**Comment by skumawat2025** [comment]
@d-buckner For example this PR has failing build due to cypress version conflicts. 
https://github.com/opensearch-project/index-management-dashboards-plugin/pull/1244

**Comment by d-buckner** [comment]
Hi @skumawat2025, apologies for the delay. Just want to confirm that the work you've recently done to upgrade to Cypress 12 in the index management dashboards plugin resolved you issue.

If not, please don't hesitate to reach out and I can help to get you unblocked.

**Pull request merged**
