### PR TITLE
Move TopNavLinks to new Nav Bar Discover

### PR DESCRIPTION
**Pull request by LDrago27**
### Description

This PR aims to introduce a new Nav bar in Discover that would contain the Date Picker as well as the Navigation links that are currently part of headers. The Navigation Links have been replaced with the corresponding Icons to provide a modern UX. These setting are currently controlled by **query:enhancements:enabled** Advanced Setting Flag and would be visible when the above flag is turned on. 

## Screenshot

image

image

## Testing the changes

- Turn on the **query:enhancements:enabled** Setting in the Advanced Settings Section of Dashboards
- Navigate to Discover Page
- Check the updated UI 

## Changelog

- feat: Add a New Nav Bar to Discover

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ashwin-pc** [comment]
When the toggle is off, i can see this bar at the top of discover:
image

**Comment by ashwin-pc** [comment]
https://github.com/user-attachments/assets/e76a0723-0698-44ad-93ee-50aa44383659

The icons also dont have a tooltip indicating what they are right now

**Comment by LDrago27** [comment]
@ashwin-pc Thanks for feedback. I have fixed the issues highlighted above and migrated the date Picker to the Nav bar too.

**Review by kavilla — APPROVED** [review]

**Review by ashwin-pc — APPROVED** [review]

**Review by kavilla — APPROVED** [review]

**Comment by LDrago27** [comment]
Manual backport was done in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7477

**Pull request merged**
