### PR TITLE
Update readme for dashboards 1.0.0

### PR DESCRIPTION
**Pull request by ananzh**
### Description

Update RC state to GA state

### Issues Resolved
[#577](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/577)

Signed-off-by: Anan Zhuang <ananzh@amazon.com>

 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by kavilla — DISMISSED** [review]

**Comment by kavilla** [comment]
@seanneumann can you confirm?

**Comment by seanneumann** [comment]
> @seanneumann can you confirm?

Let me get you some updated text. Hold for now.

**Comment by ahopp** [comment]
@ananzh I think we should pull reference to the fork and GA then keep the content simple. Something like;

> OpenSearch Dashboards aims to be the best community-driven, open source search and analytics visualization platform available.
>   
> Feel free to take a look at what the community has been up to, and then head over to the [Project Board](https://github.com/opensearch-project/OpenSearch-Dashboards/projects) to track release targets, or jump in and [start opening issues](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/new/choose) or [contributing](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/CONTRIBUTING.md).

We may also want to add a callout to the license like this; 

## License
This project is licensed under the Apache v2.0 License.

**Comment by ananzh** [comment]
> @ananzh I think we should pull reference to the fork and GA then keep the content simple. Something like;
> 
> > OpenSearch Dashboards aims to be the best community-driven, open source search and analytics visualization platform available.
> > Feel free to take a look at what the community has been up to, and then head over to the [Project Board](https://github.com/opensearch-project/OpenSearch-Dashboards/projects) to track release targets, or jump in and [start opening issues](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/new/choose) or [contributing](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/CONTRIBUTING.md).
> 
> We may also want to add a callout to the license like this;
> 
> ## License
> This project is licensed under the Apache v2.0 License.

We will format the sentences. For the license, we have it [here ](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/LICENSE.txt#L192). Do we want to repeat them in readme?

**Review by kavilla — APPROVED** [review]

**Review by seanneumann — APPROVED** [review]
Great!

**Pull request merged**
