### PR TITLE
Feature (home): Update visual consistency sample dashboard with more vis

### PR DESCRIPTION
**Pull request by joshuarrrr**
### Description

- Add more sample visualizations to the visual consistency dashboard
- Save time range with dashboard
- Make naming consistent

### Issues Resolved

N/A

## Screenshot

Screenshot 2023-07-17 at 15-33-18 Visual Consistency Dashboard - OpenSearch Dashboards

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by manasvinibs — APPROVED** [review]
Just curious to know how are you generating this data? Is it manual or imported from existing Dashboards?

**Comment by joshuarrrr** [comment]
> Just curious to know how are you generating this data? Is it manual or imported from existing Dashboards?

Great question! I'm running a local version of Dasbhoards, and manually creating these visualizations through the UI, because they're intended to represent the "default" look and feel of our many visualization types. After I create new visualizations and save them to the dashboard, I go to Advanced Settings, and export the dashboard saved object, with the option to include all linked objects (the visualizations). That ndjosn can then just be converted to json via `replace('\n',','`, and then copy pasted on top of the current definition of these objects in the file changed here.

**Comment by kavilla** [comment]
> > Just curious to know how are you generating this data? Is it manual or imported from existing Dashboards?
> 
> Great question! I'm running a local version of Dasbhoards, and manually creating these visualizations through the UI, because they're intended to represent the "default" look and feel of our many visualization types. After I create new visualizations and save them to the dashboard, I go to Advanced Settings, and export the dashboard saved object, with the option to include all linked objects (the visualizations). That ndjosn can then just be converted to json via `replace('\n',','`, and then copy pasted on top of the current definition of these objects in the file changed here.

This is where I cross my fingers that no tests outside this repo was query the dom for specific titles that include brackets 😓

**Comment by joshuarrrr** [comment]
> This is where I cross my fingers that no tests outside this repo was query the dom for specific titles that include brackets 😓

Oh, just to clarify all of these saved objects are new (both the visualizations and dashboards), introduced in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4339. So there's no change to historical sample dashboards or visualizations.

**Review by BSFishy — APPROVED** [review]

**Pull request merged**
