### PR TITLE
[Feature] Allow order control in `createAggConfig`

### LINKED ISSUE #3159: `createAggConfig` should allow order-specific additions
**Is your feature request related to a problem? Please describe.**

When creating a new `AggConfig`, the default behavior is to also add the newly created `AggConfig` to the existing list of `aggConfigs`: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/bfc59d44daf8b3891f1e89afff4dcaed048f3b49/src/plugins/data/common/search/aggs/agg_configs.ts#L149

However, order matters when specifying aggregations, and the aggregation `Schema` [supports the property `mustBeFirst`](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/bfc59d44daf8b3891f1e89afff4dcaed048f3b49/src/plugins/vis_default_editor/public/schemas.ts#L54), which [is used by the pie chart ](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/vis_type_vislib/public/pie.ts#L113)to ensure that slices are calculated accurately. The simplest, and likely best, fix is to update `createAggConfig` to take an additional parameter that allows the new AggConfig to be added to the beginning of the aggConfigs array rather than the end. 

**Describe the solution you'd like**

Maintain existing behavior of `createAggConfig`, but add a new parameter that can switch the insertion point from the end of the array to the beginning.

**Describe alternatives you've considered**

The existing logic to enforce `mustBeFirst` constraints [is in the `vis_default_editor` plugin](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/bfc59d44daf8b3891f1e89afff4dcaed048f3b49/src/plugins/vis_default_editor/public/components/agg_group_helper.tsx#L54-L74). But for adding pie charts to VisBuilder, we'd have to recreate this logic, since VisBuilder doesn't use the `vis_default_editor`.  In addition, we'd just like to always order the aggs correctly, rather than displaying and error message and forcing the user to reorder (as the current Pie chart visualization does)

Doing so downstream of the agg service means separating the creation of the new `AggConfig` from the process of adding it to the existing `aggConfigs`, and ends up with lots of duplication of the order checking logic and direct manipulation of the `aggConfigs` array. For example, one implementation might look something like this:

```
       const aggConfig = aggConfigs?.createAggConfig(
        {
          type: allowedAggTypes[0] || validAggTypes[0],
          schema: schema.name,
          params: {
            field: fieldName,
          },
        },
        {
          addToAggConfigs: false,
        }
      );

      const newAggs = schema.mustBeFirst ? [aggConfig, ...aggs] : [...aggs, aggConfig];
      const newAggConfigs = aggService.createAggConfigs(indexPattern, cloneDeep(newAggs));
```

Conceptually, the agg service should provide the right methods and tooling to add, remove, and reorder agg configs without requiring lots of manual array manipulation and cloning.

**Additional context**

Blocks https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1619

### PR DESCRIPTION
**Pull request by joshuarrrr**
### Description

Add new optional boolean param `mustBeFirst` that adds the newly created `AggConfig` to the beginning of the array rather than the end. Makes it easier to work with Pie or other visualizations with `Schemas` that set `mustBeFirst`

### Issues Resolved

fixes #3159
 
### Check List
- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [x] `yarn test:ftr`
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by manasvinibs** [comment]
LGTM!

Just curious to understand the use case for which this feature is being added. I see in the description some of the visualizations with schemas will make use of this new flag. I'm not familiar with most of the viz. Can you add screenshots or more details on how the config position in the list makes difference to the viz?

**Review by manasvinibs — APPROVED** [review]

**Comment by joshuarrrr** [comment]
> LGTM!
> 
> Just curious to understand the use case for which this feature is being added. I see in the description some of the visualizations with schemas will make use of this new flag. I'm not familiar with most of the viz. Can you add screenshots or more details on how the config position in the list makes difference to the viz?

@manasvinibs I made a demonstration video to better illustrate the use case:

https://user-images.githubusercontent.com/1679762/211126284-6d970ba8-1c61-40da-8528-c284b71b7459.mov

It's actually specific to the pie chart visualization, as you can see by searching for `mustbefirst`: https://github.com/search?q=repo%3Aopensearch-project%2FOpenSearch-Dashboards%20mustbefirst&type=code

The idea behind this PR is that any order dependency is important, and should be handled by the agg service itself, not by a UI component (such as the `vis_default_editor`).

**Review by ashwin-pc — APPROVED** [review]
Love the change, any reason why you didn't apply this change to the `vis_default_editor` component?

**Comment by joshuarrrr** [comment]
> any reason why you didn't apply this change to the `vis_default_editor` component?

I think that would require a deeper UX dive - I think it would be better to just always add them in the right order, but the fact that the default editor implies that users have full control over agg order might make that flow a bit weird, by forcing a chart split agg to the top of the list. It's do-able, but needs more thought.

**Comment by manasvinibs** [comment]
> > LGTM!
> > Just curious to understand the use case for which this feature is being added. I see in the description some of the visualizations with schemas will make use of this new flag. I'm not familiar with most of the viz. Can you add screenshots or more details on how the config position in the list makes difference to the viz?
> 
> @manasvinibs I made a demonstration video to better illustrate the use case:
> 
>  pie-must-come-first-480.mov 
> It's actually specific to the pie chart visualization, as you can see by searching for `mustbefirst`: https://github.com/search?q=repo%3Aopensearch-project%2FOpenSearch-Dashboards%20mustbefirst&type=code
> 
> The idea behind this PR is that any order dependency is important, and should be handled by the agg service itself, not by a UI component (such as the `vis_default_editor`).


Nice! Thanks for the demo video, really helpful!

**Review by manasvinibs — APPROVED** [review]

**Pull request merged**
