### PR TITLE
Fold last AL2 releases of EUI and Charts into OSD

### LINKED ISSUE #787: Bump EUI library to last AL2 release
There are some bug fixes, improvements, etc. in the last AL2 release that the OpenSearch-Dashboards doesn't have.

I see there is ongoing effort for forking https://github.com/opensearch-project/OpenSearch-Dashboards/issues/653

If the effort is minimal it would be nice to also bump the current EUI dep to the last AL2 release. (If it would take a lot of effort, then can ignore wasted work and just focus on #653)

### PR DESCRIPTION
**Pull request by AMoo-Miki**
### Description
* Folded `@elastic/eui` v34.6.0 
* Folded `@elastic/charts` v31.1.0
* Bumped some dependencies
* Changed some code to address changed features

PS, the new packages come with their histories.
 
### Issues Resolved
Fixes #787 and #1136 
 
### Check List
- [X] New functionality includes testing.
  - [ ] All tests pass
    - [ ] `yarn test:jest`
    - [ ] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by tmarkley** [comment]
Would it be possible to first upgrade to the newer versions and then fold that code in after? I don't quite understand why we need to merge in over 4,500 commits.

**Comment by mihirsoni** [comment]
I would also recommend to do first just PR to fold into OSD and then incrementally change as required and get it reviewed in an individual PRs, much easy to track , review.

**Comment by AMoo-Miki** [comment]
> Would it be possible to first upgrade to the newer versions and then fold that code in after? I don't quite understand why we need to merge in over 4,500 commits.

@tmarkley, the ask was to bring in the history along; the 4000+ commits are the entire history of the 2 packages.

**Comment by AMoo-Miki** [comment]
@mihirsoni and @tmarkley: 
* I am not sure if I can maintain history with folding and then upgrading since the remote repos are moved to a folder and Charts looses its folder structure.
* I can certainly upgrade and then fold in; this would simply reorder some commits. Another benefit (or maybe con) of this would be splitting the effort into two PRs.

**Comment by tmarkley** [comment]
> > Would it be possible to first upgrade to the newer versions and then fold that code in after? I don't quite understand why we need to merge in over 4,500 commits.
> 
> @tmarkley, the ask was to bring in the history along; the 4000+ commits are the entire history of the 2 packages.

Ah okay, I didn't realize that was a required part of the process. Understood.

**Comment by AMoo-Miki** [comment]
Closing in favor of separate bumping and folding PRs.

**Pull request closed without merging**
