### PR TITLE
[Build] restore visTypeVega

### PR DESCRIPTION
**Pull request by kavilla**
### Description
Restoring the visTypeVega.config from openSearchDashboards to
kibana and then updated the tests. This is allowable because this is
for functional purposes and for clusters/plugins that will migrate
to Dashboards. Their index will not require re-indexing for 1.0.0
and won't require migration after further updates.

Primarily, from what I can tell, impacted saved maps.

This needs to be back-ported into `1.x` and `1.0`

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Resolved
Partial: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/334
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by kavilla** [comment]
Screen Shot 2021-06-15 at 10 48 01 PM

**Review by tmarkley — APPROVED** [review]
Looks good to me, but can you clarify what would happen if we didn't revert these changes back to `kibana`? Would re-indexing be required?

**Comment by kavilla** [comment]
Needed to update the sample data while installing.

**Review by ananzh — APPROVED** [review]
LGTM

**Review by tmarkley — APPROVED** [review]

**Comment by kavilla** [comment]
> Looks good to me, but can you clarify what would happen if we didn't revert these changes back to `kibana`? Would re-indexing be required?

It wouldn't be able to reindex for this one. It is saved within the index as a value so when it parses the value it failed to find config.opensearchDashboards on saved maps so it actually will show just an error in replacement of the map with an error message stating it couldn't find another property of the visualization.

**Pull request merged**
