### PR TITLE
[Bug]Change JetBeats --> BeatsWest to avoid trademark violation

### PR DESCRIPTION
**Pull request by ananzh**
Signed-off-by: Anan Zhuang <ananzh@amazon.com>

### Description
This PR replaces the word "JetBeats" to "BeatsWest" in the sample data and code base to avoid trademark violation. 
Sample data in flights.json.gz is unzipped first then changed and re-zip by gzip command. After change, the images and logs all show "BeatsWest".

1)Images change
Screen Shot 2021-06-09 at 11 13 40 AM

2)logs change
Screen Shot 2021-06-09 at 12 13 18 PM

 
### Issues Resolved
[#432 ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/432)

### Tests
Although changing sample data should not affect tests, I added test results just for reference.
1)unit
Screen Shot 2021-06-09 at 12 03 47 PM
2)integration
Screen Shot 2021-06-09 at 12 01 51 PM
3)functional
Screen Shot 2021-06-09 at 12 09 26 PM

 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by stockholmux — APPROVED** [review]
LGTM :)

**Review by kavilla — CHANGES_REQUESTED** [review]
Could you take a screen shot and update the images in this directory: https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/home/public/assets/sample_data_resources/flights

what I did when updating these was just screen shot it in dark mode and regular mode and resized the image.

**Comment by kavilla** [comment]
Also could you please update the following:

* https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/test/functional/fixtures/opensearch_archiver/opensearch_dashboards_sample_data_flights/data.json.gz
* https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/test/functional/fixtures/opensearch_archiver/opensearch_dashboards_sample_data_flights_index_pattern/data.json.gz

**Comment by ananzh** [comment]
> Could you take a screen shot and update the images in this directory: https://github.com/opensearch-project/OpenSearch-Dashboards/tree/main/src/plugins/home/public/assets/sample_data_resources/flights
> 
> It's hard to tell but it references JetBeats and when you add sample data you can kind of see it. What I did when updating these was just screen shot it in dark mode and regular mode and resized the image.

will do

**Comment by ananzh** [comment]
> Also could you please update the following:
> 
> * https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/test/functional/fixtures/opensearch_archiver/opensearch_dashboards_sample_data_flights/data.json.gz
> * https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/test/functional/fixtures/opensearch_archiver/opensearch_dashboards_sample_data_flights_index_pattern/data.json.gz

will do. thank you rocky

**Review by boktorbb-amzn — APPROVED** [review]
Looks good

**Comment by kavilla** [comment]
Not a comment to be fixed but a question: I noticed different values in the images? Did you have different filters on while taking them? Just curious to make sure visiting the page different times after switching settings didn't cause different values to show up (which could be problem we need to look into).

**Review by kavilla — APPROVED** [review]
LGTM, more nitpick but don't let this block the PR from being merged if you do not have time due to the problem this commit is trying to solve. The dimension is a little off and it isn't aligned with the other sample data perhaps a followup to align it.

Thank you!

Screen Shot 2021-06-11 at 11 09 35 AM

**Pull request merged**
