### PR TITLE
[Workspace]Change workspace description field to textarea

### PR DESCRIPTION
**Pull request by wanglam**
### Description

1. Change workspace description to textarea component
2. Remove workspace description field validation logic

## Screenshot
image

## Testing the changes

- Clone branch code and run `yarn osd bootstrap`
- Add below configuration to `config/opensearch_dashboards.yml`
```yaml
opensearchDashboards.dashboardAdmin.users: ['admin']
workspace.enabled: true
```
- Login with admin user and visit [workspace create page](http://localhost:5601/app/workspace_create)
- Workspace description will become textarea and symbol like "." "_" can be input
- Click Create workspace then workspace can be created.
- Will navigate to workspace overview page, new added description will be dispalyed.

## Changelog

- feat: [Workspace] Change description field to textarea

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by BionIT** [comment]
Hi @wanglam, is this PR for 2.15 or 2.16?

**Comment by wanglam** [comment]
> Hi @wanglam, is this PR for 2.15 or 2.16?

Hi @BionIT , this PR is for 2.15. Feel free to help me add a label. Thank you.

**Review by SuZhou-Joe — APPROVED** [review]

**Review by ruanyl — DISMISSED** [review]

**Comment by lauralexis** [comment]
Looks good to me

**Comment by wanglam** [comment]
@ruanyl @SuZhou-Joe I've tweaked the UI slightly. Now the new UI can be signoff. Could you help me take a look?

**Review by SuZhou-Joe — APPROVED** [review]

**Review by ruanyl — APPROVED** [review]

**Pull request merged**
