### PR TITLE
Bump to version 2.2.2

### PR DESCRIPTION
**Pull request by qreshi**
Signed-off-by: Mohammad Qureshi <47198598+qreshi@users.noreply.github.com>

### Description
Bump 2.2 branch to `2.2.2` to be up-to-date with the newest tracked version on the branch.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by qreshi** [comment]
Can anyone comment on the WhiteSource errors? How are new issues being introduced in this branch from a version increment?

**Comment by ashwin-pc** [comment]
@qreshi it looks like these fixes werent backported to this branch. So all future changes to this version will contain these vulnerabilities unless those fixes are backported. Do we plan on having another patch release for this minor version?

**Comment by qreshi** [comment]
> @qreshi it looks like these fixes werent backported to this branch. So all future changes to this version will contain these vulnerabilities unless those fixes are backported. Do we plan on having another patch release for this minor version?
> 
> As for backporting those changes, the policy we currently follow for security fixes is that we only backport vulnerabilities to the latest minor versions of the supported major versions of the software. i.e. 2.4 and 1.3 in this case. I've opened an issue in the project website repo to clarify these instructions to make it clear what versions we will backport these fixes to. [opensearch-project/project-website#1249](https://github.com/opensearch-project/project-website/issues/1249). Add you comments there if you feel like those fixes need to go into other minor versions as well.

We bump every branch to the next tracking version after a release. This is regardless of whether or not a version release is actually planned. So since 2.2.1 has released, all `2.2` branches *should* be on `2.2.2` to track the next patch version. If this is an existing issue, let's get the version bump in and any dependency upgrades can be done as follow-ups by the OSD team.

**Review by ashwin-pc — APPROVED** [review]

**Review by joshuarrrr — APPROVED** [review]

**Comment by joshuarrrr** [comment]
Yeah, I believe this was missed as a follow-up task from the `2.2.1` patch release.

**Pull request merged**
