### PR TITLE
Bump node-sass to address LibSass vulnerabilities

### PR DESCRIPTION
**Pull request by tmarkley**
### Description
There are a few known security vulnerabilities related to the version of node-sass used in the repo. Both node-sass and LibSass are deprecated, but replacing node-sass with dart-sass fails because EUI does not follow the standard Sass spec. This results in a SassError: `Top-level selectors may not contain the parent selector "&"`. Resolving this problem will have to be done in the long-term, but for now there are branches of node-sass that exist with a newer version of LibSass that does not contain any known security vulnerabilities. Unfortunately, these changes don't exist in any of the main releases, so we must use a specific branch (v5).

Details are on the main Sass website: https://sass-lang.com/blog/libsass-is-deprecated

Node-sass Issue for LibSass 3.6: https://github.com/sass/node-sass/issues/2685

node-sass v5 branch: https://github.com/sass/node-sass/tree/v5

Signed-off-by: Tommy Markley <markleyt@amazon.com>
 
### Issues Resolved
N/A

### Testing

Screen Shot 2021-06-18 at 3 02 42 PM
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by ananzh — APPROVED** [review]
LGTM. Nice to learn.

**Review by boktorbb-amzn — APPROVED** [review]
LGTM

**Comment by tmarkley** [comment]
All tests are passing after rebasing.

Screen Shot 2021-06-22 at 4 26 05 PM

**Review by ananzh — APPROVED** [review]

**Review by kavilla — APPROVED** [review]
Smoke tested it, LGTM.  We have an issue open for the long term fix?

**Pull request merged**
