### PR TITLE
Update folder names for pre-installed plugins to kebab-case

### PR DESCRIPTION
**Pull request by VachaShah**
### Description
This PR updates the folder names for pre-installed plugins in `src/plugins` to kebab-case to maintain consistency as described in Issue #322. 

### Testing
The following commands succeeded:
* `yarn test:jest`
* `TEST_OPENSEARCH_FROM=/path/to/extracted/build/artifact yarn test:jest_integration`

### Issues Resolved
Part 2 of #322.
 
### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by mihirsoni** [comment]
@VachaShah  Thanks for the PR, I see 5k files changes, are these expected?

**Comment by mihirsoni** [comment]
Also, if we decide to go with this approach, we will need to break the the PRs in smaller one, else Git will not be able to carry forward the history. IMO we should do this change as part of 2.0.

**Comment by VachaShah** [comment]
> @VachaShah Thanks for the PR, I see 5k files changes, are these expected?

@mihirsoni Yes, there are so many files since the rename is for all the pre-installed plugins folders inside `src/plugins`.

**Comment by VachaShah** [comment]
> Also, if we decide to go with this approach, we will need to break the the PRs in smaller one, else Git will not be able to carry forward the history. IMO we should do this change as part of 2.0.

I tried to break the PR for each with a bunch of plugins in each but there are files which would be common in each of them, making it harder to break down. I thought it would be easier if the rename is just in one PR in terms of commit history, LMK what you think.

**Comment by dblock** [comment]
This is a bunch of renaming and LGTM.

**Review by dblock — APPROVED** [review]

**Comment by dblock** [comment]
@mihirsoni I wonder whether it's worth putting this in 1.0 to make it easier for upgrades 1.0 -> 1.x.

**Comment by mihirsoni** [comment]
> @mihirsoni I wonder whether it's worth putting this in 1.0 to make it easier for upgrades 1.0 -> 1.x.
Hi @dblock this is my concerns
I think we don't need to make it right now in RC we can hit for GA. 
* We need this to be broken down in smaller PR , this is too big PR and can't review throughly
* Need to ensure all the integration / functional tests are passing. 
* I don't see harm in doing it gradually.

**Comment by VachaShah** [comment]
@mihirsoni I will work on breaking down this PR into smaller ones, mostly one for each plugin. I have also updated the description for testing as well.

**Comment by kavilla** [comment]
Can this PR be closed?

**Comment by VachaShah** [comment]
> Can this PR be closed?

Yes I have created the smaller PRs for all the plugins, closing this PR now.

**Pull request closed without merging**
