### PR TITLE
Implement nested support for histograms aggregations

### PR DESCRIPTION
**Pull request by MerwaneHAMADI**
Signed-off-by: Merwane Hamadi <merwanehamadi@gmail.com>

### Description
This change allows the user to select a nested field on all histograms visualizations. This voluntarily a limited scope. I suggest we add more fields in the future. To add another field, all you have to do is change this array : 
nestedAggregationsSupported = ['histogram'];
After running a query on a nested field, opensearch dashboard will automatically generate the correct elasticsearch query, send it to elasticsearch and return back nested visualizations.
### Issues Resolved
This PR is a part of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/657
 
### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by MerwaneHAMADI** [comment]
There are 5 tests suites failing : 
[test.txt](https://github.com/opensearch-project/OpenSearch-Dashboards/files/7147161/test.txt)

It doesn't look related to my feature.

**Comment by ahopp** [comment]
@tmarkley do we have any bandwidth to support this?

**Comment by tmarkley** [comment]
From your `test.txt` file: 
```
3 snapshots failed from 2 test suites. Inspect your code changes or run `yarn run test:jest -u` to update them.
```

Can you update the snapshots?

**Comment by MerwaneHAMADI** [comment]
@tmarkley yes, no problem

**Comment by MerwaneHAMADI** [comment]
Snapshots updated. These are the new tests failing.
[tests.txt](https://github.com/opensearch-project/OpenSearch-Dashboards/files/7316812/tests.txt)

**Comment by tmarkley** [comment]
Hey @MerwaneHAMADI just checking in again. Is there anything we can do to help get this PR merged?

**Comment by kavilla** [comment]
Hello @MerwaneHAMADI, this pull request has not had activity recently. We will close this in 7 days if no further updates. If it closes by the time you make the requested updates then please re-open the pull request. Thank you!

**Pull request closed without merging**
