### PR TITLE
Upgrade glob-parent related dependencies

### PR DESCRIPTION
**Pull request by tmarkley**
### Description
Addresses https://github.com/advisories/GHSA-ww39-953v-wcq6

There are additional dependencies that have a downstream dependency on older versions of `glob-parent`, but those packages either don't have a newer version or the newer versions introduce breaking changes. One example is `globby`, which introduces many breaking changes. A manual resolution for `glob-parent` works in this case to address the CVE.

**Before**
```
$ yarn why glob-parent
yarn why v1.22.10
[1/4] Why do we have the module "glob-parent"...?
[2/4] Initialising dependency graph...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~3.7.2"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "glob-parent@5.1.1"
info Has been hoisted to "glob-parent"
info Reasons this module exists
   - "workspace-aggregator-bc8ee24d-e89b-418c-8e89-123b176ac8b2" depends on it
   - Hoisted from "_project_#eslint#glob-parent"
   - Hoisted from "_project_#chokidar#glob-parent"
   - Hoisted from "_project_#@osd#storybook#copy-webpack-plugin#glob-parent"
   - Hoisted from "_project_#mocha#chokidar#glob-parent"
   - Hoisted from "_project_#@percy#agent#globby#fast-glob#glob-parent"
   - Hoisted from "_project_#@osd#storybook#copy-webpack-plugin#fast-glob#glob-parent"
   - Hoisted from "_project_#del#globby#fast-glob#glob-parent"
   - Hoisted from "_project_#@osd#config-schema#tsd#globby#fast-glob#glob-parent"
   - Hoisted from "_project_#backport#del#globby#fast-glob#glob-parent"
   - Hoisted from "_project_#@elastic#safer-lodash-set#dependency-check#globby#fast-glob#glob-parent"
   - Hoisted from "_project_#chromedriver#del#globby#fast-glob#glob-parent"
   - Hoisted from "_project_#eslint-plugin-jest#@typescript-eslint#experimental-utils#@typescript-eslint#typescript-estree#globby#fast-glob#glob-parent"
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: "48KB"
info Disk size with transitive dependencies: "64KB"
info Number of shared dependencies: 2
=> Found "fast-glob#glob-parent@3.1.0"
info This module exists because "_project_#fast-glob" depends on it.
=> Found "@types/globby#glob-parent@3.1.0"
info Reasons this module exists
   - "_project_#@types#globby#fast-glob" depends on it
   - Hoisted from "_project_#@types#globby#fast-glob#glob-parent"
   - in the nohoist list ["/_project_/**/@types/*","/_project_/**/@types/*/**","/_project_/**/grunt-*","/_project_/**/grunt-*/**","/_project_/@elastic/eui/rehype-react","/_project_/@elastic/eui/remark-rehype","/_project_/@elastic/eui/remark-rehype/**"]
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: "28KB"
info Disk size with transitive dependencies: "28KB"
info Number of shared dependencies: 3
=> Found "glob-stream#glob-parent@3.1.0"
info This module exists because "_project_#vinyl-fs#glob-stream" depends on it.
=> Found "glob-base#glob-parent@2.0.0"
info This module exists because "_project_#@osd#storybook#@storybook#core#glob-base" depends on it.
=> Found "@osd/pm#glob-parent@3.1.0"
info Reasons this module exists
   - "_project_#@osd#pm#@types#globby#fast-glob" depends on it
   - Hoisted from "_project_#@osd#pm#@types#globby#fast-glob#glob-parent"
   - in the nohoist list ["/_project_/**/@types/*","/_project_/**/@types/*/**","/_project_/**/grunt-*","/_project_/**/grunt-*/**","/_project_/@elastic/eui/rehype-react","/_project_/@elastic/eui/remark-rehype","/_project_/@elastic/eui/remark-rehype/**"]
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: "28KB"
info Disk size with transitive dependencies: "28KB"
info Number of shared dependencies: 3
=> Found "@osd/optimizer#glob-parent@3.1.0"
info Reasons this module exists
   - "_project_#@osd#optimizer#@types#watchpack#chokidar" depends on it
   - Hoisted from "_project_#@osd#optimizer#@types#watchpack#chokidar#glob-parent"
   - in the nohoist list ["/_project_/**/@types/*","/_project_/**/@types/*/**","/_project_/**/grunt-*","/_project_/**/grunt-*/**","/_project_/@elastic/eui/rehype-react","/_project_/@elastic/eui/remark-rehype","/_project_/@elastic/eui/remark-rehype/**"]
info Disk size without dependencies: "28KB"
info Disk size with unique dependencies: "28KB"
info Disk size with transitive dependencies: "28KB"
info Number of shared dependencies: 3
=> Found "glob-watcher#glob-parent@3.1.0"
info Reasons this module exists
   - "_project_#@osd#storybook#glob-watcher#chokidar" depends on it
   - Hoisted from "_project_#@osd#storybook#glob-watcher#chokidar#glob-parent"
=> Found "babel-plugin-add-module-exports#glob-parent@3.1.0"
info Reasons this module exists
   - "_project_#@osd#babel-preset#babel-plugin-add-module-exports#chokidar" depends on it
   - Hoisted from "_project_#@osd#babel-preset#babel-plugin-add-module-exports#chokidar#glob-parent"
=> Found "webpack-dev-server#glob-parent@3.1.0"
info Reasons this module exists
   - "_project_#@osd#ui-framework#webpack-dev-server#chokidar" depends on it
   - Hoisted from "_project_#@osd#ui-framework#webpack-dev-server#chokidar#glob-parent"
=> Found "@babel/cli#glob-parent@3.1.0"
info Reasons this module exists
   - "_project_#@osd#interpreter#@babel#cli#chokidar" depends on it
   - Hoisted from "_project_#@osd#interpreter#@babel#cli#chokidar#glob-parent"
=> Found "watchpack-chokidar2#glob-parent@3.1.0"
info Reasons this module exists
   - "_project_#@osd#optimizer#watchpack#watchpack-chokidar2#chokidar" depends on it
   - Hoisted from "_project_#@osd#optimizer#watchpack#watchpack-chokidar2#chokidar#glob-parent"
Done in 1.45s.
```

### Testing

Screen Shot 2021-06-24 at 11 49 14 PM
 
### Issues Resolved
N/A
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ananzh** [comment]
I see it has conflicting files. I see` packages/osd-ui-framework/package.json` has been modified. Is there other issues cause the conflicts?

**Review by ananzh — COMMENTED** [review]
I see it has conflicting files.

```
This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
packages/osd-ui-framework/package.json
yarn.lock
```
I see packages/osd-ui-framework/package.json has been modified. Is there other issues cause the conflicts?

**Review by kavilla — DISMISSED** [review]
LGTM thanks! Noticed my yarn.lock file updated while building to be  "@types/glob@^7.1.3"

**Review by ananzh — APPROVED** [review]
LGTM. thanks.

**Review by kavilla — APPROVED** [review]

**Review by ananzh — APPROVED** [review]

**Pull request merged**
