### PR TITLE
[nodejs] remove native realm from code base

### PR DESCRIPTION
**Pull request by ananzh**
### Description
Native realm is not supported by current nodejs client. Remove all native realm code and tests. After removing native realm, integration tests all pass.

### Partically Resolved:https://github.com/opensearch-project/OpenSearch-Dashboards/issues/837

Signed-off-by: Anan Zhuang <ananzh@amazon.com>

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by tmarkley — APPROVED** [review]

**Comment by kavilla** [comment]
I believe looks good to me. Seems like Native Realm was something originally for x-pack. That said, I don't think this should be a blocker for OpenSearch JS. But I think it should just target the main branch (the removing), then rebased, and then the feature branch can just switch the client. It would make the delta smaller.

WDYT?

**Comment by ananzh** [comment]
> I believe looks good to me. Seems like Native Realm was something originally for x-pack. That said, I don't think this should not be a blocker for OpenSearch JS. But I think it should just target the main branch (the removing), then rebased onto the feature branch, and then the feature branch can just switch the client. It would make the delta smaller.
> 
> WDYT?

I agree. I found this Native Realm in our code base due to some integration tests fail after nodejs client hooked up. For example:
```
yarn test:jest_integration /home/ubuntu/work_osd/OpenSearch-Dashboards/src/core/server/ui_settings/create_or_upgrade_saved_config/integration_tests/create_or_upgrade.test.ts
 
FAIL  src/core/server/ui_settings/create_or_upgrade_saved_config/integration_tests/create_or_upgrade.test.ts (16.421 s)   ● createOrUpgradeSavedConfig() › upgrades the previous version on each increment 
TypeError: Cannot read property 'info' of undefined
116 |             features       
117 |           }     > 
118 |         } = await this._client.xpack.info({           |                                      ^      
119 |           categories: 'features'       
120 |         });       
121 |         return features.security && features.security.enabled && features.security.available;
at fn (packages/osd-opensearch/target/utils/native_realm.js:118:38)       
at NativeRealm._autoRetry (packages/osd-opensearch/target/utils/native_realm.js:139:20)       
at NativeRealm._autoRetry (packages/osd-opensearch/target/utils/native_realm.js:153:25)       
at NativeRealm._autoRetry (packages/osd-opensearch/target/utils/native_realm.js:153:14)       
at NativeRealm.isSecurityEnabled (packages/osd-opensearch/target/utils/native_realm.js:113:14)       
at NativeRealm.setPasswords (packages/osd-opensearch/target/utils/native_realm.js:86:11)       
at packages/osd-opensearch/target/cluster.js:392:7          
at async Promise.all (index 1)       
at Cluster.start (packages/osd-opensearch/target/cluster.js:260:5)       
at OpenSearchTestCluster.start (packages/osd-test/src/legacy_opensearch/legacy_opensearch_test_cluster.js:108:7)       
at Object.startOpenSearch (src/core/test_helpers/osd_server.ts:269:7)       
at Object.<anonymous> (src/core/server/ui_settings/create_or_upgrade_saved_config/integration_tests/create_or_upgrade.test.ts:58:24)

```
Cluster.start waits for native realm to setup and opensearch to be started
Native realm is not supported by current nodejs client because it is a x-pack feature. Therefore we see those errors. Although it is found due to nodejs client hook up, native realm should be removed from our code base. How about I create a PR for main and close this one? @tmarkley @kavilla

**Comment by kavilla** [comment]
> How about I create a PR for main and close this one? @tmarkley @kavilla

Thanks for the insight. Sounds like a plan.

Thanks! \m/

**Comment by ananzh** [comment]
close and open [PR](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1307)

**Pull request closed without merging**
