### PR TITLE
Fix query editor cursor alignment by removing monaco css overrides

### PR DESCRIPTION
**Pull request by d-rowe**
### Description

Monaco editor computes the cursor position internally and does not account for any css overrides that change the position of the line (padding, margin, etc). This change removes the css override while we implement these styles with the monaco api directly.

## Changelog
- fix: ensure query editor cursor is aligned with text

### Before
before

### After
after

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by ashwin-pc — APPROVED** [review]

**Review by Hailong-am — DISMISSED** [review]

**Comment by Hailong-am** [comment]
Can you fix the lint?

**Review by d-rowe — COMMENTED** [review]
Adding new line to resolve linting issue

**Comment by d-rowe** [comment]
> Can you fix the lint?

Sure thing, I've fixed the linting issue.

**Review by virajsanghvi — APPROVED** [review]
can you post a screenshot of the before/after of padding

approving to unblock assuming it passes ci

**Comment by d-rowe** [comment]
> can you post a screenshot of the before/after of padding

Yup, I've added before and after screenshots in the PR description

**Review by Hailong-am — APPROVED** [review]

**Comment by luisfavila** [comment]
Is there any reason why this is still reproducible in AWS-hosted "Opensearch UI Dashboards"?

image

**Pull request merged**
