### PR TITLE
[Look&Feel] Update Popover Padding Size

### PR DESCRIPTION
**Pull request by danieldong51**
### Description

Set popover padding size to small for instances of non-context menu popovers. Did not change popovers that had no padding to begin with.

## Screenshots
| Area | Before (v7Light) | After (v7Light) | Before (v8Dark) | After (v8Dark) |
| ----- | ----- | ----- | ----- | ----- |
| Appearance | Appearance v7 Light Before | Appearance v7 Light After | Appearance v8 Dark Before | Appearance v8 Dark After |
| Discover Field | Discover Field v7 Light Before | Discover Field v7 Light After | Discover Field v8 Dark Before | Discover Field v8 Dark After |
| Help | Help v7 Light Before | Help v7 Light After | Help v8 Dark Before | Help v8 Dark After |
| Syntax | Syntax v7 Light Before | Syntax v7 Light After | Syntax v8 Dark Before | Syntax v8 Dark After 
| Visualize | Visualize Fields v7 Light Before | Visualize Field v7 Light After | Visualize Field v8 Dark Before | Visualize Field v8 Dark After |

## Changelog
- refactor: [Look&Feel] Update Popover Padding Size

### Check List

- [x] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by virajsanghvi** [comment]
Know this is a draft, but one comment - do you know why the padding for "Syntax" look condensed in the after? I'm guessing we're not using the component correctly?

**Comment by danieldong51** [comment]
> Know this is a draft, but one comment - do you know why the padding for "Syntax" look condensed in the after? I'm guessing we're not using the component correctly?

The font size for the syntax menu is larger than the other popovers (16px vs 14px), that could be partly why the margins seem condensed? Here's what the syntax menu looks like with 14px font:

Syntax Font Change


And here's what the popover looks like with the Help Menu with small padding:
Comparison

**Comment by virajsanghvi** [comment]
Can you get checks passing.

For changelog, think you want to install https://github.com/apps/opensearch-changeset-bot in your repo so it automatically gets created here

**Comment by virajsanghvi** [comment]
Restarted failed test to see if it passes

**Review by AMoo-Miki — APPROVED** [review]

**Review by virajsanghvi — APPROVED** [review]

**Pull request merged**
