### PR TITLE
Fix bug that prevents selected join field to be used

### LINKED ISSUE #2888: [Bug] Issues with RegionMaps plugin
Hello,

I think I found multiple issues with region maps after adding support for custom import map vector.

First, from debugging the current code, looks like if you chose default map you can't use Name as join Field and iso_3166_2 is default selected:
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/region_map/public/region_map_visualization.js#L159

And the second one is using custom vector map, when getting vector map, size is not set so only first 10 Features are returned.
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/region_map/server/routes/opensearch.ts#L67
I got all results by adding size in params:
`const params = { index, body: {} ,size: 30};`

Thank you

### PR DESCRIPTION
**Pull request by VijayanB**
### Description
Remove updating join field to first field always.

Signed-off-by: Vijayan Balasubramanian <balasvij@amazon.com>
 
### Issues Resolved
#2888  
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by VijayanB** [comment]
@ashwin-pc Can you please get review on this PR? Thanks

**Review by ashwin-pc — APPROVED** [review]

**Review by manasvinibs — APPROVED** [review]

**Comment by VijayanB** [comment]
Thanks for merging this PR.  @ashwin-pc @manasvinibs Can you a back port to 2.4 as well?

**Comment by joshuarrrr** [comment]
@VijayanB Should this fix also be backported to `1.x`/`1.3`? Or was the bug introduced only in `2.x` features?

**Comment by VijayanB** [comment]
@joshuarrrr This is only introduced in 2.x.

**Pull request merged**
