### PR TITLE
Fix: Update button position when number of rows per page is large

### PR DESCRIPTION
**Pull request by curq**
### Description
After the fix the table component no longer renders unused space for extra rows. Before the fix when the option max rows per page was larger than actual number of results, the table component was rendered with height that could fit max number of rows per page and not the actual number. Screenshot from the issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3756:
image
The number of results in this screen is 50, while the max number of rows per page is 100. As the result, half of the table component is empty and the update button is pushed far below. I have checked the component from the docs in the sandbox and this is expected behavior. 
Therefore, to prevent this bug I assumed that we need to ensure that max number of rows is never larger than number of rows in resulting table. This fix does exactly that. The same case (50 resulting rows, 100 max number of rows), 
image
The fix is achieved by updating `usePagination` hook.
### Issues Resolved

Fixes https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3756

### Check List

- [ ] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [X] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ananzh** [comment]
Add comment here 
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3737#issuecomment-1500723388

Let me know if you want to combine the bug fixes into one PR. I am okay with one or two PRs.

**Comment by curq** [comment]
@ananzh I decided to make two PR instead of combining both. I made separate PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3816. and added more explanation [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3737#issuecomment-1502151199)

**Review by ananzh — APPROVED** [review]

**Comment by ananzh** [comment]
> @ananzh I decided to make two PR instead of combining both. I made separate PR #3816. and added more explanation [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3737#issuecomment-1502151199) I'm also open to updating unit tests when the PR you mentioned will be merged.

Got it. I approved.

**Comment by joshuarrrr** [comment]
@curq Thanks for the fix!

> I have checked the component from the docs in the sandbox and this is expected behavior.

This strikes me as not ideal. Do you mind [opening an issue in OUI](https://github.com/opensearch-project/oui/issues/new/choose) where we can discuss whether this behavior is actually desired or useful?

**Review by joshuarrrr — APPROVED** [review]

**Comment by curq** [comment]
> This strikes me as not ideal. Do you mind [opening an issue in OUI](https://github.com/opensearch-project/oui/issues/new/choose) where we can discuss whether this behavior is actually desired or useful?

@joshuarrrr as you requested, I opened a [new issue in OUI repo](https://github.com/opensearch-project/oui/issues/699) where I have provided a more detailed description of the behavior, along with examples.

**Comment by joshuarrrr** [comment]
all checks passed, but I need to resolve a changelog conflict

**Review by joshuarrrr — APPROVED** [review]

**Review by ananzh — APPROVED** [review]

**Comment by joshuarrrr** [comment]
data source manager cypress test failures are safe to ignore.

**Comment by joshuarrrr** [comment]
No need to backport - incorporated into https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3397

**Pull request merged**
