### PR TITLE
[CCI] Bug fix for eui select in firefox browser using onclick

### LINKED ISSUE #3134: [BUG] Firefox - the "Legend position" selector in Vis Builder doesn't allow changes
**Describe the bug**

In Firefox, it's impossible to change the Legend position in VisBuilder.

**To Reproduce**
1. Go to https://playground.opensearch.org/app/vis-builder#/ in a Firefox browser
2. Drag `Count` to Y-axis
3. Drag `category.keyword` to X-axis
4. Try to change the legend position by selecting a value other than "Right"

https://user-images.githubusercontent.com/1679762/209255163-ba90a7f3-65c1-40fb-8487-0bc51ffb53d5.mov

**Expected behavior**
The legend position selection should work, as it does on Chrome

https://user-images.githubusercontent.com/1679762/209255409-f6bedd3b-871b-444d-b287-a8c3a3cf61c0.mov

**OpenSearch Version**
2.4.0

**Dashboards Version**
2.4.0

**Plugins**
Standard distribution

**Host/Environment (please complete the following information):**
 - OS: MacOS
 - Browser and version: 102.6.0esr (64-bit)

### PR DESCRIPTION
**Pull request by Nicksqain**
### Description
Use this code to bypass the error in eui select. Now select input works in firefox browser
 
### Issues Resolved
Fixes #3134
 
### Check List
- [x] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by AMoo-Miki** [comment]
@Nicksqain Do you know what was preventing `onChange` from working? I ask because this could be happening in other places as well and maybe we should look for a wider solution.

**Comment by Nicksqain** [comment]
@AMoo-Miki I haven't quite figured out the EUI library yet, but all I've figured out is that for some reason in mozilla event.target the onChange event returns an initialised value. I'm trying to work on this issue.

**Comment by ashwin-pc** [comment]
@Nicksqain Thanks for taking a look at this. Your fix actually made me question whats actually happening here and I realized that the issue was a little more complicate that it seems on the surface. The chart option is not the issue here because other parts of the app use it without this issue on firefox. e.g the Vertical bar visualization in Visualize. Taking a closer look, it looks like the issue is because of a race condition. The [`EuiResizableContainer`](https://github.com/opensearch-project/OpenSearch-Dashboards/blob/c35dadb0cbf97a751d5bee650a4189e7005b590a/src/plugins/vis_builder/public/application/app.tsx#L46) in the app causes re-renders constantly (even when the mouse simply moves over the UI). This seems to be resetting the select box value. I think that the re-render in firefox happens a little faster than it does in chrome, which is why I think its a race condition.  

You change does fix the issue, but it only covers up the bigger issue here. Can you look to prevent the unnecessary rerenders on the child components caused by the `EuiResizableContainer` ?

**Comment by Nicksqain** [comment]
@ashwin-pc 
Yes, I noticed the constant rendering of components as the mouse moves. 
I'll see what I can do, right after fixing the type issue.

**Comment by ashwin-pc** [comment]
closing this PR since #3732 fixes the issue

**Pull request closed without merging**
