### PR TITLE
Revert "[Manual Backport 2.x][MD] Support SigV4 as a new auth type of datasource"

### PR DESCRIPTION
**Pull request by joshuarrrr**
Bumping `@opensearch-project/opensearch` from `^1.1.0` to `^2.1.0` is a breaking change for plugins and CI, and should not have been backported to `2.x`

Fixes https://github.com/opensearch-project/opensearch-build/issues/3210

### CODE REVIEW

**Comment by kavilla** [comment]
I think we can remove the 2.6 label here as well right: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3465?

**Review by kavilla — APPROVED** [review]
I agree with reverting this. I don't think the call was to bump to a major version. I think if sigv4 support was a minor change for 2.x it can also be a minor change for 1.x and request can be made to support.

There is no indication that the 1.x version of OpenSearch JS is deprecated: https://www.npmjs.com/package/@opensearch-project/opensearch/v/1.1.0.

We should request if this: https://github.com/opensearch-project/opensearch-js/pull/279 can be backported to 1.x. So that we can get the new feature without causing a breaking change.

**Review by ananzh — APPROVED** [review]

**Comment by ananzh** [comment]
I think 2.6 is too rushy. We should revert it. Then we should discuss whether we could treat client as a special package and relax the restrict version match.

**Comment by seraphjiang** [comment]
Not clear on what specific functionality break changes have occurred that justify the revert

We should have a retrospective to revisit and align with the community on the definition break change perf SemVer to improve the process. Otherwise, it will decrease productivity and erode the community's trust.

@seanneumann @dblock @CEHENKLE @bbarani

**Pull request merged**
