### PR TITLE
docs: remove `attributes.` in SavedObjectsFindOptions.fields example

### PR DESCRIPTION
**Pull request by joshuali925**
### Description

Corrects the example in the comment for SavedObjectsFindOptions. The comment is misleading because it includes `attributes`, which will be a field in the response

```json
{
  "id": "my-pattern",
  "type": "index-pattern",
  "version": 1,
  "attributes": {
    "title": "my-pattern-*"
  }
}
```

But the raw document does not include `attributes` field, saved object client will put fields under saved object type in the raw document as the `attributes` field. 

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/471877f8ff45b216806a8038d9466f671f446ce1/src/core/server/saved_objects/serialization/serializer.ts#L89

Raw document sample:

```json
      {
        "_index": ".kibana_92668751_admin_5",
        "_id": "custom-type:185348a0-3239-11ee-b9f0-0fc7f32be0b4",
        "_seq_no": 106,
        "_primary_term": 2,
        "_score": null,
        "_source": {
          "custom-type": {
            "title": "custom title",
            "version": 1,
            "createdTimeMs": 1691093129770,
          },
          "type": "custom-type",
          "references": [],
          "updated_at": "2023-08-03T20:05:29.770Z"
        }
      },
```

So including `attributes.<field>` (e.g. `attributes.title`) in find options will not give correct results. Using `<field>` (e.g. `title`) is enough because the type will be prepended.

https://github.com/opensearch-project/OpenSearch-Dashboards/blob/471877f8ff45b216806a8038d9466f671f446ce1/src/core/server/saved_objects/service/lib/included_fields.ts#L48

### Check List

- [x] All tests pass
  - [x] `yarn test:jest`
  - [x] `yarn test:jest_integration`
  - [x] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by joshuali925** [comment]
> `+ Coverage   66.10%   66.14%   +0.03%     `

why does coverage change when the commit only changes a comment?

**Comment by joshuarrrr** [comment]
> > `+ Coverage   66.10%   66.14%   +0.03%     `
> 
> why does coverage change when the commit only changes a comment?

CodeCov has some margin of error - we often see diffs for changes that have no test changes at all. Don't worry about it.

**Review by joshuarrrr — APPROVED** [review]
LGTM

**Comment by kavilla** [comment]
@joshuali925 do you think there is a potential for some recent change to have modified this behavior or is it a potential weird behavior in the current client?

Was playing around with the import saved objects API and attempting to hit that endpoint with a POST without `attributes` actually got rejected explicitly telling me i need to include attributes.

If I was to implement an OpenSearch Dashboards client I would probably ensure that the usage is consistent so users don't have to modify data to include specific keys that we already map in another endpoint.

To be honest your point makes more sense but it makes me question if something off is happening somewhere.

**Comment by joshuali925** [comment]
@kavilla I'm not sure why the rest API and saved object js client are inconsistent, I've not used the rest API much. But I don't think it's a recent change on the client, the related code I posted has not changed for more than 4 years

side question, where is the documentation for saved object rest API? I couldn't find them in https://opensearch.org/docs/latest/dashboards/index/

**Comment by joshuarrrr** [comment]
> side question, where is the documentation for saved object rest API? I couldn't find them in https://opensearch.org/docs/latest/dashboards/index/

https://github.com/opensearch-project/documentation-website/issues/3799 😢

**Comment by kavilla** [comment]
> side question, where is the documentation for saved object rest API? I couldn't find them in https://opensearch.org/docs/latest/dashboards/index/

Yeah as @joshuarrrr commented it is to be added. I can try to scrap something together today.

**Comment by joshuarrrr** [comment]
@kavilla Assigning to you to either finish the final review or provide updated docs and close.

**Comment by kavilla** [comment]
@joshuali925, could this be the result of the type of `dashboard` is a container of other saved objects and so it is has different fields whereas the index pattern is a little bit more simplified?

If so then perhaps we can update this PR so that it references both examples

**Review by ananzh — APPROVED** [review]

**Comment by kavilla** [comment]
im currently looking into this area so I'm going to move it to 2.15 and add it to the the saved objects OE.

**Pull request merged**
