### PR TITLE
Dashboard Lists Integration

### PR DESCRIPTION
**Pull request by pjfitzgibbons**
### Description
* Configure types for registration of Dashboard List "Providers" and "Creators"

* Add Left-Nav "top-level" category for Observability

These changes enable the interactions demonstrated in this animation:

Dashboard List Integration

### Issues WIP

[[FEATURE] Dashboards List Extensibility & Integrate Observability Apps/Panels/EventAnalytics](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1866)
- includes alternate solutions, example animation, and further explanation of this solution.

## Related PR
[[Feature] Observability - Dashboard Lists Integration #1180 ](https://github.com/opensearch-project/observability/issues/1180)
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by joshuarrrr** [comment]
@pjfitzgibbons It looks like this PR needs some snapshot and test updates.

**Comment by pjfitzgibbons** [comment]
> Also @pjfitzgibbons can you create an issue in OSD for this PR that outlines the issue and why this change is necessary in Dashboards
- Also updated example animation.

@ashwin-pc https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1866

**Comment by ashwin-pc** [comment]
Oops, my bad. I thought it was referencing an issue on the observability repo. Thanks!

**Comment by pjfitzgibbons** [comment]
Need to rebase to branch 2.x.  Too much churn.  PR recreated as #2980

**Pull request closed without merging**
