### PR TITLE
Fix test failures in #5177

### PR DESCRIPTION
**Pull request by AMoo-Miki**
Re #5177 

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ashwin-pc** [comment]
I'm looking at the last test run for #5177 and no test failed there. Also savedSearch is declared twice yes, but can you remove the other declaration of it instead of this one? A fix anan made will have a conflict here otherwise.

**Comment by kavilla** [comment]
I think the sequence of merges caused an issue that wasn't caught as a conflict but likely succeeded in a previous run

**Comment by kavilla** [comment]
> I'm looking at the last test run for #5177 and no test failed there. Also savedSearch is declared twice yes, but can you remove the other declaration of it instead of this one? A fix anan made will have a conflict here otherwise.

i think the fix might have gotten merged prior to the deangular.

**Review by kavilla — APPROVED** [review]
do the other changes from the original PR have no impact?

**Pull request closed without merging**
