### PR TITLE
[Test] Enable schema_error.test.ts

### PR DESCRIPTION
**Pull request by ananzh**
Signed-off-by: Anan Zhuang <ananzh@amazon.com>

### Description
This is skipped because in 2017 there is no decision around error handling in the new platform. We can enable the unit test for error handling. 

The error message is:
```
    { Error: test
        at Object.<anonymous>.it (/home/anan/work/OpenSearch-Dashboards/packages/osd-config-schema/src/errors/schema_error.test.ts:61:11)
        at Object.asyncJestTest (/home/anan/work/OpenSearch-Dashboards/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
        at resolve (/home/anan/work/OpenSearch-Dashboards/node_modules/jest-jasmine2/build/queueRunner.js:45:12)
        at new Promise (<anonymous>)
        at mapper (/home/anan/work/OpenSearch-Dashboards/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
        at promise.then (/home/anan/work/OpenSearch-Dashboards/node_modules/jest-jasmine2/build/queueRunner.js:75:41)
        at process._tickCallback (internal/process/next_tick.js:68:7) cause: undefined }

      at Object.<anonymous>.it (packages/osd-config-schema/src/errors/schema_error.test.ts:63:13)
```

After clean and select, following message will be compare to snapshot
```
    Error: test
        at Object.<anonymous>.it (packages/osd-config-schema/src/errors/schema_error.test.ts:61:11)
        at new Promise (<anonymous>)
```

 
### Issues Resolved
[#486 ](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/486)

### Test results
unit test for schema_error.test.ts
```
$ node scripts/jest /packages/osd-config-schema/src/errors/schema_error.test.ts
 PASS  packages/osd-config-schema/src/errors/schema_error.test.ts
  ✓ includes stack (5 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        1.659 s
```

overall unit test:
```
Test Suites: 22 skipped, 1412 passed, 1412 of 1434 total
Tests:       257 skipped, 9 todo, 10358 passed, 10624 total
Snapshots:   2364 passed, 2364 total
Time:        44.997 s
```
integration test:
```
Test Suites: 50 passed, 50 total
Tests:       3 skipped, 434 passed, 437 total
Snapshots:   73 passed, 73 total
Time:        314.149 s
```

functional test: see below image
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ananzh** [comment]
Screen Shot 2021-06-17 at 9 21 18 AM

**Comment by kavilla** [comment]
> Screen Shot 2021-06-17 at 9 21 18 AM

Should be able to run the full pipeline, no cherry picking as long as you rebased main.

**Comment by kavilla** [comment]
From reading the comment it seems like related to unknown aspects about node versions and if the test fails on different node versions. Could I get some clarity on that?

**Comment by kavilla** [comment]
Could the commit description have some details about why we are able to re-enable it.

**Comment by ananzh** [comment]
> > Screen Shot 2021-06-17 at 9 21 18 AM
> 
> Should be able to run the full pipeline, no cherry picking as long as you rebased main. Can we actually run this fully on the CI pipeline as well. Some tests like to work locally but fail on the CI.

will do

**Comment by tmarkley** [comment]
> Could the commit description have some details about why we are able to re-enable it.

Agreed, let's make sure we're adding helpful details to the commit messages.

**Comment by ananzh** [comment]
> From reading the comment it seems like related to unknown aspects about node versions and if the test fails on different node versions. Could I get some clarity on that?

Yes. As mentioned in issue [here](https://github.com/elastic/kibana/issues/12947), there is a discussion about error handling in 'new platform'. I am not sure the exact reason this test is skipped initially but I think two reasons are related: 1) I see there is a bump from nodejs6 to nodejs 8 in March,2018. As mentioned in this article [here ](https://medium.com/the-node-js-collection/node-js-errors-changes-you-need-to-know-about-dc8c82417f65), there are changes in nodejs error handling. 2) Another error handling mentioned in the above issue is to use boom to handle HTTP errors. boom provides a set of error response object for returning HTTP errors. boom also depends on nodejs.

**Comment by ananzh** [comment]
> From reading the comment it seems like related to unknown aspects about node versions and if the test fails on different node versions. Could I get some clarity on that?

will amend the commit msg for this PR. thanks for the comment

**Comment by ananzh** [comment]
> > Could the commit description have some details about why we are able to re-enable it.
> 
> Agreed, let's make sure we're adding helpful details to the commit messages.

Will amend the commit message. Thanks for the comment.

**Review by kavilla — APPROVED** [review]

**Review by tmarkley — APPROVED** [review]

**Pull request merged**
