### PR TITLE
Bump yeoman-generator from 1.1.1 to 4.13.0

### PR DESCRIPTION
**Pull request by tmarkley**
### Description
Addresses security vulnerabilities related to versions of `diff` before v3.5.0: 
* https://github.com/advisories/GHSA-h6ch-v84p-w6p9
* https://github.com/advisories/GHSA-hr2v-3952-633q

v4.13.0 is the most recent version that supports Node v10.
None of the breaking changes listed impact the build.
- [Release notes](https://github.com/yeoman/generator/releases)
- [Commits](https://github.com/yeoman/generator/compare/v1.1.1...v4.13.0)

**Before**
```$ yarn why diff
yarn why v1.22.10
[1/4] Why do we have the module "diff"...?
[2/4] Initialising dependency graph...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~3.7.2"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "diff@3.5.0"
info Has been hoisted to "diff"
info Reasons this module exists
   - "workspace-aggregator-a4686603-bc1a-441b-8267-e07788467e7b" depends on it
   - Hoisted from "_project_#mocha#diff"
   - Hoisted from "_project_#sinon#diff"
   - Hoisted from "_project_#@osd#ui-framework#yo#yeoman-environment#diff"
info Disk size without dependencies: "680KB"
info Disk size with unique dependencies: "680KB"
info Disk size with transitive dependencies: "680KB"
info Number of shared dependencies: 0
=> Found "@osd/test#diff@4.0.1"
info This module exists because "_project_#@osd#test" depends on it.
info Disk size without dependencies: "700KB"
info Disk size with unique dependencies: "700KB"
info Disk size with transitive dependencies: "700KB"
info Number of shared dependencies: 0
=> Found "yeoman-environment#diff@2.2.3"
info This module exists because "_project_#@osd#ui-framework#yeoman-generator#yeoman-environment" depends on it.
info Disk size without dependencies: "416KB"
info Disk size with unique dependencies: "416KB"
info Disk size with transitive dependencies: "416KB"
info Number of shared dependencies: 0
Done in 1.39s.
```

**After**
```
$ yarn why diff
yarn why v1.22.10
[1/4] Why do we have the module "diff"...?
[2/4] Initialising dependency graph...
warning Resolution field "typescript@4.0.2" is incompatible with requested version "typescript@~3.7.2"
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "diff@3.5.0"
info Has been hoisted to "diff"
info Reasons this module exists
   - "workspace-aggregator-ea7391ac-a7be-430c-9abb-85f99242170f" depends on it
   - Hoisted from "_project_#mocha#diff"
   - Hoisted from "_project_#sinon#diff"
   - Hoisted from "_project_#@osd#ui-framework#yo#yeoman-environment#diff"
info Disk size without dependencies: "680KB"
info Disk size with unique dependencies: "680KB"
info Disk size with transitive dependencies: "680KB"
info Number of shared dependencies: 0
=> Found "@osd/test#diff@4.0.1"
info This module exists because "_project_#@osd#test" depends on it.
info Disk size without dependencies: "700KB"
info Disk size with unique dependencies: "700KB"
info Disk size with transitive dependencies: "700KB"
info Number of shared dependencies: 0
=> Found "yeoman-generator#diff@4.0.1"
info This module exists because "_project_#@osd#ui-framework#yeoman-generator" depends on it.
=> Found "yeoman-generator#yeoman-environment#diff@3.5.0"
info This module exists because "_project_#@osd#ui-framework#yeoman-generator#yeoman-environment" depends on it.
Done in 1.39s.
```

### Testing

Screen Shot 2021-06-23 at 6 02 52 PM
 
### Issues Resolved
N/A
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by ananzh — APPROVED** [review]
LGTM

**Comment by kavilla** [comment]
Is this used for the application or plugin generation?

**Comment by tmarkley** [comment]
> Is this used for the application or plugin generation?

@kavilla as far as I can tell it's used for generating KUI components, for example: https://github.com/tmarkley/OpenSearch-Dashboards/blob/24ceae6f7a01ad5fc8e0765a68f159e016567ba1/packages/osd-ui-framework/package.json#L9

**Review by kavilla — COMMENTED** [review]
> @kavilla as far as I can tell it's used for generating KUI components, for example: https://github.com/tmarkley/OpenSearch-Dashboards/blob/24ceae6f7a01ad5fc8e0765a68f159e016567ba1/packages/osd-ui-framework/package.json#L9

Sounds good.

Just conflict and will approve.

**Review by ananzh — DISMISSED** [review]

**Review by ananzh — APPROVED** [review]

**Review by kavilla — APPROVED** [review]

**Pull request merged**
