### PR TITLE
[Version] Increment 1.x to 1.2

### PR DESCRIPTION
**Pull request by kavilla**
### Description
Version bump from 1.1 to 1.2.

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Resolved
N/A

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by kavilla** [comment]
Screen Shot 2021-09-16 at 3 28 24 AM

**Comment by kavilla** [comment]
OpenSearch on 1.2 [[here](https://github.com/opensearch-project/OpenSearch/blob/1.x/buildSrc/version.properties#L1)[

**Review by ananzh — APPROVED** [review]
thanks rocky

**Review by tmarkley — APPROVED** [review]

**Comment by kavilla** [comment]
In favor of main having all the latest commits will close this PR and backport a commit from main.

**Pull request closed without merging**
