### PR TITLE
Enhance the Build and Test workflow

### PR DESCRIPTION
**Pull request by AMoo-Miki**
* Run GitHub workflow unit tests in band (#1306)
* Fix JUnit Reporter test (#1338)
* Add src/test_utils/ and src/core paths to the target clean patterns (#1442)
* Add code coverage reporting (#1478)
* Add release build verification workflow (#1502)
* Add Windows CI to the workflow (#2966)
* Add retrying flaky jest tests (#2967)
* Record functional test artifacts in case of failure (#3190)
* Increase timeout waiting for the exiting of an optimizer worker (#3193)
* Improve yarn's performance in workflows by caching yarn's cache folder (#3194)
* Fix the version of Chrome to 107 to match `chromedriver@107.0.1`, the last that works on NodeJS v10
* Prevent `AbortError` from breaking unit tests for ExecutionContract

Signed-off-by: Miki <miki@amazon.com>

 
### Check List
- [X] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [X] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by joshuarrrr — APPROVED** [review]
There are a lot of changes here, but nothing of concern jumped out at me. It will be a huge improvement to bring these workflows and tests more inline with our other branches.

**Comment by AMoo-Miki** [comment]
While this has passed several times in the past, on Windows this PR has failed twice with
```
UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

expect(jest.fn()).toBeCalledTimes(expected)

Expected number of calls: 1
Received number of calls: 0
    at emitWarning (internal/process/promises.js:99:15)
    at emitPromiseRejectionWarnings (internal/process/promises.js:143:7)
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

Wish I knew where that was coming from.

**Review by manasvinibs — APPROVED** [review]

**Comment by kavilla** [comment]
Nice! With the retry and increasing of timeout it enables us to run the CI at full speed without capping it to prevent failures.

**Comment by AMoo-Miki** [comment]
i'll manually backport this.

**Comment by joshuarrrr** [comment]
backport: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3310

**Pull request merged**
