### PR TITLE
[Workspace] Recover data source management in workspace

### PR DESCRIPTION
**Pull request by raintygao**
### Description

Data source is a global level saved object, so we disable data source management when in workspace. 
For now, data source is a workspace level object, so we should recover data source management in workspace and disable create/update/delete operation in frontend(https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7214 has implemented).

## Screenshot

image

## Testing the changes
Enter a workspace then you can visit data source management then will see workspace level data source objects and there is not entry for creating/updating/deleting.

## Changelog

- feat: Recover data source management in workspace

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by SuZhou-Joe** [comment]
Hi @raintygao I think we can close this PR because:
When new navigation is enabled, we will show data source in each of the use case.
When new navigation is disabled, we had a assumption that workspace should be disabled as well.

**Review by SuZhou-Joe — APPROVED** [review]

**Comment by ZilongX** [comment]
Pick up the main and re-running all checks

**Comment by ZilongX** [comment]
> Hi @raintygao I think we can close this PR because: When new navigation is enabled, we will show data source in each of the use case. When new navigation is disabled, we had a assumption that workspace should be disabled as well.

So do we still need this change to be merged as part of 2.16.0 ?

**Comment by raintygao** [comment]
> > Hi @raintygao I think we can close this PR because: When new navigation is enabled, we will show data source in each of the use case. When new navigation is disabled, we had a assumption that workspace should be disabled as well.
> 
> So do we still need this change to be merged as part of 2.16.0 ?

Yes, after discussing we can merge it in 2.16 as this is a very tiny change. CC @SuZhou-Joe @ruanyl

**Review by ruanyl — APPROVED** [review]

**Pull request merged**
