### PR TITLE
[De-Angular] Clean angular context in Data plugin

### LINKED ISSUE #5021: [De-Angular] Clean angular context in Data plugin
- [ ] Update `toAngularJSON(filter.input.query))` to `toAngularJSON(filter.input.query))` in `src/plugins/data/common/search/aggs/buckets/filters.ts.` 
- [ ] Remove `src/plugins/data/common/search/aggs/utils/to_angular_json.ts` and clean `src/plugins/data/common/search/aggs/utils/index.ts`.

### PR DESCRIPTION
**Pull request by ShatilKhan**
### Description

- Renamed the `toAngularJSON` function into `toJSON` 
- Renamed the `to_angular_json` file into `to_json`
- Renamed the reference  in index.ts from `to_angular_json` to `to_json`

### Issues Resolved

Closes #5021 

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [X] Update [CHANGELOG.md](./../CHANGELOG.md)
- [X] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by joshuarrrr** [comment]
@ShatilKhan There's a conflict to resolve. Let me know if you need assistance resolving it.

**Comment by ShatilKhan** [comment]
> @ShatilKhan There's a conflict to resolve. Let me know if you need assistance resolving it.

Thanks, I'm not done with all the updates for this PR yet, once that's done, I resolve the conflicts

**Review by ananzh — CHANGES_REQUESTED** [review]
I don't think we could directly remove this file, since `toAngularJSON` is still used in src/plugins/data/common/search/aggs/buckets/filters.ts right? We need to replace the usage of  `toAngularJSON` in this file as well.

**Review by ananzh — COMMENTED** [review]
@ShatilKhan just see ur comment. makes sense to me. if you haven't done all the work, you could turn this PR into a draft so people won't start reviewing it.

**Comment by ShatilKhan** [comment]
Thanks @ananzh 
I'll draft this & make the necessary updates

**Comment by ShatilKhan** [comment]
I don't think I have permission to draft
Please draft this PR until I've completed all changes

**Comment by ShatilKhan** [comment]
I'm trying to understand this section in [`src/plugins/data/common/search/aggs/utils/to_angular_json.ts`](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5417/commits/6b70af3cb244902da412a595be721d7304600493#diff-43c7eda4e2c1820b1e11a915ae54b3b76a2b229004b4cff711d9535e77cd28b3)
image
I see the `toAngularJSON` function returns a `JSON.stringify()` method
Should I rename `toAngularJSON` to `JSON.stringify()` here? 
I understand what the function is doing, but It would be helpfull to understand the desired changes
@ananzh can you help me understand this?

**Comment by ShatilKhan** [comment]
I found the reference to `to_angular_json` on [`src/plugins/data/common/search/aggs/utils/index.ts`](https://github.com/ShatilKhan/OpenSearch-Dashboards/blob/dangular/src/plugins/data/common/search/aggs/utils/index.ts) here:
image
I understand it's imported from [`src/plugins/data/common/search/aggs/utils/to_angular_json.ts`](https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5417/commits/6b70af3cb244902da412a595be721d7304600493#diff-43c7eda4e2c1820b1e11a915ae54b3b76a2b229004b4cff711d9535e77cd28b3)

**Comment by ShatilKhan** [comment]
I'm trying out renaming the function
We can also try using only json.stringify method but that could cause some errors I believe ( I tried)

**Comment by ShatilKhan** [comment]
Changed the name of the function
Didn't see any error mesaages
I tried running `yarn test : jest` twice
But both time my laptop hangs up :(

**Pull request closed without merging**
