### PR TITLE
[WS-2021-0638][Security] bump mocha to 10.1.0

### PR DESCRIPTION
**Pull request by ananzh**
### Description
In our current repo, most mocha tests have been changed to jest in this issue:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/215

The fix for the above issue
(https://github.com/mochajs/mocha/commit/61b4b9209c2c64b32c8d48b1761c3b9384d411ea) is only released in the latest version v10.1.0:
https://github.com/mochajs/mocha/blob/5f96d511dbf913f135b92198aab721a27f6b44fe/lib/utils.js#L79

Though it is a bump from 7.2.0 to 10.1.0, I don't see breaking changes for plugins or users.

### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2269

### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by ananzh** [comment]
test fail but locally it is fine:

```
yarn test:jest packages/osd-test/src/functional_test_runner/integration/failure_hooks.test.js
yarn run v1.22.19
$ node scripts/jest packages/osd-test/src/functional_test_runner/integration/failure_hooks.test.js
  console.log
    lines.shift():      └-> $FAILING_TEST$

      at Object.assert (packages/osd-test/src/functional_test_runner/integration/failure_hooks.test.js:58:19)

 PASS  packages/osd-test/src/functional_test_runner/integration/failure_hooks.test.js
  failure hooks
    ✓ runs and prints expected output (1112 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        2.329 s
Ran all test suites matching /packages\/osd-test\/src\/functional_test_runner\/integration\/failure_hooks.test.js/i.
Done in 3.90s.
```
will re-run this test

**Comment by joshuarrrr** [comment]
> Though it is a bump from 7.2.0 to 10.1.0, I don't see breaking changes for plugins or users.

This is a good reminder that we need to clearly communicate to plugins that we plan to deprecate and remove mocha in the future. While we've migrated all the core dashboards tests to jest, plugins may still well be using mocha tests/depending on mocha directly. With the above, are you saying that you reviewed the changes  between 7.2.0 and 10.1.0 and there are no breaking changes in the mocha API?

**Comment by AMoo-Miki** [comment]
To Josh's point, we should make sure `mocha@^10.1.0` is backwards compatible with `mocha@^7.2.0`. I propose we don't rush this through 2.4.

**Comment by kavilla** [comment]
+1 to what Miki said given that it's just for tests and it won't be in releases then we can do this post release.

**Review by joshuarrrr — APPROVED** [review]

**Comment by joshuarrrr** [comment]
I removed the `backport 2.x` label because this fix cannot be safely backported.

**Review by ashwin-pc — APPROVED** [review]

**Pull request merged**
