### PR TITLE
[Tests] update expected value for percentile ranks

### PR DESCRIPTION
**Pull request by kavilla**
### Description
Origin:
https://github.com/opensearch-project/OpenSearch/pull/3634

The previous value was actually incorrect after OpenSearch bumped t-digest
the value is now the correct value.

Signed-off-by: Kawika Avilla <kavilla414@gmail.com>
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1821
 
### Check List
- [ ] New functionality includes testing.
  - [x] All tests pass
    - [x] `yarn test:jest`
    - [x] `yarn test:jest_integration`
    - [x] `yarn test:ftr`
- [ ] New functionality has been documented.
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by manasvinibs — APPROVED** [review]
Thanks @kavilla for the fix! LGTM

**Review by mihirsoni — DISMISSED** [review]

**Review by joshuarrrr — DISMISSED** [review]

**Comment by joshuarrrr** [comment]
Is this a `3.0` only change, or will we backport?

**Comment by kaddy645** [comment]
Looks like one more was failing yesterday !      **metric chart should show Percentiles:** should we also update values for it ?

**Comment by kavilla** [comment]
> Looks like one more was failing yesterday ! **metric chart should show Percentiles:** should we also update values for it ?
> 
> https://github.com/opensearch-project/OpenSearch-Dashboards/blob/4ea645e86193de9fd25d6cecf199d48ce033bd55/test/functional/apps/visualize/_metric_chart.js#L188

Updated!

**Comment by kavilla** [comment]
> Is this a `3.0` only change, or will we backport?

This is expected to only be a `3.0` change since this was not backported: https://github.com/opensearch-project/OpenSearch/pull/3634

**Comment by kaddy645** [comment]
it might fail again! I see more missing values. can we run these functional tests locally ? 

expected
```
 [ '2,147,483,648',
               │   '1st percentile of machine.ram',
               │   '3,221,225,472',
               │   '5th percentile of machine.ram',
               │   '7,516,192,768',
               │   '25th percentile of machine.ram',
               │   '12,884,901,888',
               │   '50th percentile of machine.ram',
               │   '18,253,611,008',
               │   '75th percentile of machine.ram',
               │   '32,212,254,720',
               │   '95th percentile of machine.ram',
               │   '32,212,254,720',
               │   '99th percentile of machine.ram' ] 
               
              
                '2,147,483,648',
               │   '1st percentile of machine.ram',
               │   '3,221,225,472',
               │   '5th percentile of machine.ram',
               │   '7,516,192,768',
               │   '25th percentile of machine.ram',
               │   '12,884,901,888',
               │   '50th percentile of machine.ram',
               │   '18,179,771,104.788',
               │   '75th percentile of machine.ram',
               │   '31,704,016,923.307',
               │   '95th percentile of machine.ram',
               │   '32,212,254,720',
               │   '99th percentile of machine.ram' ]

**Comment by kavilla** [comment]
> it might fail again! I see more missing values. can we run/test these functional tests locally ?
> 
> expected
> 
> ```
>  [ '2,147,483,648',
>                │   '1st percentile of machine.ram',
>                │   '3,221,225,472',
>                │   '5th percentile of machine.ram',
>                │   '7,516,192,768',
>                │   '25th percentile of machine.ram',
>                │   '12,884,901,888',
>                │   '50th percentile of machine.ram',
>                │   '18,253,611,008',
>                │   '75th percentile of machine.ram',
>                │   '32,212,254,720',
>                │   '95th percentile of machine.ram',
>                │   '32,212,254,720',
>                │   '99th percentile of machine.ram' ] 
>                
>               
>                 '2,147,483,648',
>                │   '1st percentile of machine.ram',
>                │   '3,221,225,472',
>                │   '5th percentile of machine.ram',
>                │   '7,516,192,768',
>                │   '25th percentile of machine.ram',
>                │   '12,884,901,888',
>                │   '50th percentile of machine.ram',
>                │   '18,179,771,104.788',
>                │   '75th percentile of machine.ram',
>                │   '31,704,016,923.307',
>                │   '95th percentile of machine.ram',
>                │   '32,212,254,720',
>                │   '99th percentile of machine.ram' ]
>                
> ```

Yeah I might have to skip this test now and re-open the issue on OpenSearch. The values returned are flaky.

**Review by kaddy645 — APPROVED** [review]

**Pull request merged**
