### PR TITLE
[Backport 2.x] Change wizard to vis_builder in file names and paths (#2587)

### PR DESCRIPTION
**Pull request by abbyhu2000**
Change all wizard reference in file names and paths to vis_builder

Signed-off-by: abbyhu2000 <abigailhu2000@gmail.com>

Signed-off-by: abbyhu2000 <abigailhu2000@gmail.com>
(cherry picked from commit f29f734453709d4b9065485525a5dbd17c73dcf1)

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by joshuarrrr — APPROVED** [review]

**Review by ashwin-pc — APPROVED** [review]

**Comment by joshuarrrr** [comment]
@abbyhu2000 I think this is missing the `CHANGELOG.md` change? If you fixed a merge conflict, maybe it didn't get added to this commit.

**Comment by manasvinibs** [comment]
@abbyhu2000 Do you want to update change log file?

**Comment by abbyhu2000** [comment]
For some reason, the changelog already have information for this PR. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.x/CHANGELOG.md

Maybe the previous backport PR already added it? @joshuarrrr @manasvinibs

**Comment by manasvinibs** [comment]
> For some reason, the changelog already have information for this PR. https://github.com/opensearch-project/OpenSearch-Dashboards/blob/2.x/CHANGELOG.md
> 
> Maybe the previous backport PR already added it? @joshuarrrr @manasvinibs

I think it got added here in this PR https://github.com/opensearch-project/OpenSearch-Dashboards/commit/b17f5c4074cdf4379b3bb81a685fc668159ccea8

**Review by manasvinibs — APPROVED** [review]

**Comment by joshuarrrr** [comment]
@abbyhu2000 Looks like there are a couple unit test failures (and unit tests that still reference `wizard`...)

**Comment by abbyhu2000** [comment]
> @abbyhu2000 Looks like there are a couple unit test failures (and unit tests that still reference `wizard`...)

The unit test references to wizard are updated in the later PR. The unit tests fail here because a previous PR needs to be backported first. Will backport that PR right now.

**Review by kavilla — APPROVED** [review]
Lgtm i think we can handle conflicts in github.

**Comment by AMoo-Miki** [comment]
Closing in favor of #2719

**Pull request closed without merging**
