### PR TITLE
Fix colors of visualizations with more than 10 items

### LINKED ISSUE #5422: The colors of the visualizations are not displayed correctly
**Describe the bug**

In opensearch 2.10.0 the colors of the visualizations are not displayed correctly.

**To Reproduce**
1. Go to Visualize
2. Create a visualization

**Dashboards Version**

2.10.0

**Screenshots**

image

image (7)

**Host/Environment (please complete the following information):**
 - OS: [Macos]
 - Browser and version [Google Chrome version 118.0.5993.117]

### PR DESCRIPTION
**Pull request by evamillan**
### Description

This PR changes the OUI palette settings used by the visualizations so that they always use the original colors first.

### Issues Resolved

Fixes #5422

## Screenshot
Before changes:
palette-before

After changes:
palette-after

## Testing the changes

A visualization should use the colors in the same order regardless of how many rotations of the color palette it needs.

## Changelog
- fix: Fix colors of the visualizations with more than 10 items

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by joshuarrrr — APPROVED** [review]
shipit! Thanks @evamillan, this is definitely an improvement. I still think we want to change the behavior for when we need more than 30 colors, as it's a bit weird to stack the dark variations directly against the light variations. But this is the right fix for 10 to 20 colors.

**Review by virajsanghvi — APPROVED** [review]

**Comment by ananzh** [comment]
@evamillan seems there is some changelog error to block merging. could you install https://github.com/apps/opensearch-changeset-bot and remove the changelog file? there should be another auto generated changelog file created in changelogs/fragments

**Review by ananzh — APPROVED** [review]

**Comment by ananzh** [comment]
@evamillan loll I just remove the blank line and seems working now.

**Review by ananzh — APPROVED** [review]

**Review by ashwin-pc — APPROVED** [review]

**Comment by ashwin-pc** [comment]
Rebasing the branch to see if it fixes the CIgroup 3 failure since it seems unrelated to this PR

**Pull request merged**
