### PR TITLE
Dashboard Lists Integration

### PR DESCRIPTION
**Pull request by pjfitzgibbons**
### Description

* Configure types for registration of Dashboard List "Providers" and "Creators"

* Add Left-Nav "top-level" category for Observability

Signed-off-by: Peter Fitzgibbons <pjfitz@amazon.com>

These changes enable the interactions demonstrated in this animation:

Dashboard List Integration

### Issues WIP

[[FEATURE] Dashboards List Extensibility & Integrate Observability Apps/Panels/EventAnalytics](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1866)
- includes alternate solutions, example animation, and further explanation of this solution.

 
### Check List
- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
  - [ ] `yarn test:ftr`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by AMoo-Miki** [comment]
Thanks for raising this PR. Why would this not go to `main`?

**Comment by pjfitzgibbons** [comment]
> Why would this not go to `main`?
@AMoo-Miki This PR is also related to Observability opensearch-project/observability#1314 .   We are targeting 2.x on both sides.
I'll be happy to backport this once we get it correctly merged.

**Comment by ashwin-pc** [comment]
@pjfitzgibbons can we close this since we have #3090?

**Comment by pjfitzgibbons** [comment]
Duplicate of #3090

**Pull request closed without merging**
