### PR TITLE
Adds src/test_utils/ and src/core paths to the target clean patterns

### LINKED ISSUE #1418: [FEATURE] yarn osd clean script should clean targets
Is your feature request related to a problem? Please describe.

Currently, we need to manually remove target directories that have outdated files that stop `yarn osd bootstrap` from running.

This most commonly happens with `Cheerio` and the type definitions in `enzyme-helpers`

Describe the solution you'd like

The current yarn osd clean script should find and clean targets across the dashboards codebase

Describe alternatives you've considered

n/a

Additional context

n/a

### PR DESCRIPTION
**Pull request by boktorbb-amzn**
Signed-off-by: Bishoy Boktor <boktorbb@amazon.com>

### Description
Adds the src/test_utils and src/core directories to the list of paths that should have their target directories cleaned. This fixes the Cheerio failure during `yarn osd bootstrap` and is recommended for the extensive restyling that comes with the stylelint change.
 
### Issues Resolved
#1418 
 
### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
    - [X] `yarn test:jest`
    - [X] `yarn test:jest_integration`
    - [ ] `yarn test:ftr`
- [ ] New functionality has been documented.
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Review by tmarkley — APPROVED** [review]

**Review by kavilla — DISMISSED** [review]
Temporary blocking to ensure stability for 2.0.0-rc1

**Comment by tmarkley** [comment]
Are we targeting 2.0?

**Comment by boktorbb-amzn** [comment]
> Are we targeting 2.0?

This can be added in 2.0 since it’s not breaking but it’s also not high priority

**Review by ashwin-pc — APPROVED** [review]
Yay!

**Pull request merged**
