### PR TITLE
Add datasource readonly feature flag and disable certain routes

### PR DESCRIPTION
**Pull request by zhyuanqi**
### Description

Add datasource readonly feature flag and disable certain routes 
* /create
* configure/opensearch

### When datasource is enabled and readonly is false, customer should be able to create and configure opensearch.
```
data_source.enabled: true
data_source.readonly: false
```

https://github.com/user-attachments/assets/4969e10b-1cac-4b94-afe3-ecc79e13bdf6

### When datasource is enabled and readonly is true, customer should not be able to create and configure openSearch.
```
data_source.enabled: true
data_source.readOnly: true
```

https://github.com/user-attachments/assets/fb4050f5-1ece-4ab5-8dec-b8bf5a8e46aa

### When datasource is diabled and readonly is disable, datasource section should be hidden
```
data_source.enabled: false
data_source.readOnly: false
```
Screenshot 2024-07-15 at 11 18 55 PM
Screenshot 2024-07-15 at 11 19 04 PM

### When datasource is diabled and readonly is  true , datasource section should still be hidden
```
data_source.enabled: false
data_source.readOnly: true
```

Screenshot 2024-07-15 at 11 20 07 PM
Screenshot 2024-07-15 at 11 20 16 PM

## Changelog
- feat: Add datasource readonly feature flag and disable certain routes

### Check List

- [ ] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] Update [CHANGELOG.md](./../CHANGELOG.md)
- [ ] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by BionIT** [comment]
> #7214 It seems we are doing the same thing on restrict user from creating data source. Could we merge the codes from both PRs?

Thanks @SuZhou-Joe ! Will sync offline and see if this can be combined efforts

**Comment by huyaboo** [comment]
Overall looks good although I have a question about accessing `/configure/OpenSearch`. Is it expected behavior to render the page if `configure/OpenSearch` is accessed (or `/configure/*` in general)?

**Comment by zhyuanqi** [comment]
close this PR as will use feature flag from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7214

**Comment by zhyuanqi** [comment]
close this PR as will use feature flag from https://github.com/opensearch-project/OpenSearch-Dashboards/pull/7214

**Comment by zhyuanqi** [comment]
> Overall looks good although I have a question about accessing `/configure/OpenSearch`. Is it expected behavior to render the page if `configure/OpenSearch` is accessed (or `/configure/*` in general)?

Hi Huy. Thanks for noticing that. I am not sure if it is a expected behavior. Need to check with flint team on it.

**Pull request closed without merging**
